// Centralized export for custom hooks
export { useLibraryFilter } from './useLibraryFilter'
export type { LibraryType } from './useLibraryFilter'
export { useMediaProgress, useWatchedList } from './useProgress'
export { useMediaPlayback } from './useMediaPlayback'
export { useDebounce } from './useDebounce'
export { useGridNavigation } from './useGridNavigation'
export { useGlobalKeyboardShortcuts } from './useGlobalKeyboardShortcuts'
export type { GlobalKeyboardShortcutsOptions } from './useGlobalKeyboardShortcuts'
export { useMediaImages, useMovieImages, useTVShowImages, useTVSeasonImages, useEpisodeImages, useMusicAlbumImages, useMusicArtistImages } from './useMediaImages'
export { BatchImagesProvider, useBatchImages, useBatchImagesIfAvailable } from './useBatchImages'
export { BatchProgressProvider, useBatchProgress, useBatchProgressIfAvailable } from './useBatchProgress'
export { useInfiniteMovies, flattenMovies } from './useInfiniteMovies'
export type { UseInfiniteMoviesOptions } from './useInfiniteMovies'
export { useInfiniteTVShows, flattenTVShows } from './useInfiniteTVShows'
export type { UseInfiniteTVShowsOptions } from './useInfiniteTVShows'
export { useInfiniteArtists, flattenArtists } from './useInfiniteArtists'
export type { UseInfiniteArtistsOptions } from './useInfiniteArtists'
export { useVirtualGrid } from './useVirtualGrid'
export { useQualityRecommendation } from './useQualityRecommendation'
export type { UseQualityRecommendationOptions, QualityRecommendationState } from './useQualityRecommendation'
export { useQualityPreferences } from './useQualityPreferences'
export type { VideoQualityPreferences } from './useQualityPreferences'
export { useNetworkMonitor } from './useNetworkMonitor'
export type { UseNetworkMonitorOptions, UseNetworkMonitorReturn } from './useNetworkMonitor'
export { useAutoQuality } from './useAutoQuality'
export type { UseAutoQualityOptions, UseAutoQualityReturn } from './useAutoQuality'
export { usePlaybackAnalytics } from './usePlaybackAnalytics'
export type { UsePlaybackAnalyticsOptions, UsePlaybackAnalyticsReturn } from './usePlaybackAnalytics'
export { useBadgePreferences } from './useBadgePreferences'
export { useStreamStats } from './useStreamStats'
export type { UseStreamStatsOptions, UseStreamStatsReturn } from './useStreamStats'
export { useHlsPlayer } from './useHlsPlayer'
export type { UseHlsPlayerOptions, UseHlsPlayerReturn, QualityLevel, AudioTrack } from './useHlsPlayer'
export { useVideoEvents } from './useVideoEvents'
export type { UseVideoEventsOptions } from './useVideoEvents'
export { useVideoKeyboard } from './useVideoKeyboard'
export type { UseVideoKeyboardOptions } from './useVideoKeyboard'
export { useVideoControls } from './useVideoControls'
export type { UseVideoControlsOptions, VideoControlHandlers } from './useVideoControls'
export { useSSE } from './useSSE'
export type { UseSSEOptions, UseSSEReturn, SSEConnectionState } from './useSSE'
export { useEnrichmentProgress } from './useEnrichmentProgress'
export type { UseEnrichmentProgressOptions, UseEnrichmentProgressReturn, EnrichmentProgressState, CurrentEnrichmentItem, OverallProgress } from './useEnrichmentProgress'
export { useScanProgress } from './useScanProgress'
export type { UseScanProgressOptions, UseScanProgressReturn, ScanProgressState, ScanProgressData } from './useScanProgress'
export { useLocationSettings } from './useLocationSettings'
export type { LocationResult } from './useLocationSettings'
export { useActiveSessions } from './useActiveSessions'
export { useStreamingAction } from './useStreamingAction'
export type {
  StreamingProgress,
  UseStreamingActionOptions,
  UseStreamingActionReturn,
} from './useStreamingAction.types'
export { useListData } from './useListData'
export type { ListItem, UseListDataOptions, UseListDataReturn } from './useListData.types'
export { useDeleteAction } from './useDeleteAction'
export type {
  DeleteActionConfig,
  UseDeleteActionOptions,
  UseDeleteActionReturn,
} from './useDeleteAction.types'
