root = "."
tmp_dir = "tmp"

[build]
# Build command - includes plugin rebuilding
cmd = "go build -o ./tmp/main ./backend/cmd/viewra/main.go"
# Binary to run
bin = "tmp/main"
# Custom arguments
args_bin = []
# Watch these file extensions
include_ext = ["go", "tpl", "tmpl", "html", "cue"]
# Exclude these directories
exclude_dir = ["assets", "tmp", "vendor", "frontend", "node_modules", ".git", "viewra-data/transcoding", "viewra-data/plugins"]
# Watch these directories
include_dir = ["backend/internal", "backend/cmd", "sdk"]
# Exclude files matching these patterns
exclude_file = []
# Exclude unchanged files
exclude_unchanged = true
# This log file will be placed in tmp_dir
log = "air_errors.log"
# Poll interval (ms)
poll = false
# Poll interval (ms)
poll_interval = 500
# Delay after change before rebuild (ms)
delay = 1000
# Stop running after build error
stop_on_error = true
# Send Interrupt signal before killing process
send_interrupt = true
# Delay after sending Interrupt signal (ms)
kill_delay = 2000

[log]
# Show log timestamps
time = true
# Only show main log
main_only = false

[color]
# Colorize output
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"
app = "blue"

[misc]
# Delete tmp directory on start
clean_on_exit = false

# Pre-build commands (commented out due to TOML parsing issue)
# [[build.pre_cmd]]
# cmd = "if find plugins -name '*.go' -newer tmp/.plugins_built 2>/dev/null | grep -q .; then echo 'Rebuilding plugins...'; make build-plugins && touch tmp/.plugins_built; fi"

[notify]
# Enable desktop notifications on build
enabled = false