# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  # Timeout for analysis
  timeout: 5m
  
  # Go version compatibility
  go: '1.23'
  
  # Include test files
  tests: true

linters:
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    
    # Additional linters
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - nakedret
    - prealloc
    - scopelint
    - gocritic
    - gochecknoinits
    - whitespace
    - gosec
    - gocyclo
    - gocognit
    - bodyclose
    - dupl
    
  disable:
    # Disable deprecated linters
    - maligned
    - interfacer
    - golint
    
    # Disable overly strict linters
    - wsl
    - godox
    - funlen
    - gomnd
    - lll
    - gochecknoglobals
    - godot
    - nestif
    - testpackage
    - goerr113
    - exhaustive
    - nlreturn
    - wrapcheck
    - errorlint
    - makezero
    - tparallel

linters-settings:
  errcheck:
    # Report about not checking of errors in type assertions
    check-type-assertions: true
    
  govet:
    # Enable shadow check
    enable:
      - shadow
    
  gofmt:
    # Simplify code
    simplify: true
    
  goimports:
    # Put local imports after 3rd party packages
    local-prefixes: github.com/mantonx/viewra
    
  gocyclo:
    # Minimal cyclomatic complexity
    min-complexity: 15
    
  gocognit:
    # Minimal cognitive complexity
    min-complexity: 20
    
  misspell:
    # Locale to use
    locale: US
    
  unused:
    # Treat exported fields as used
    check-exported: false
    
  unparam:
    # Inspect exported functions
    check-exported: false
    
  nakedret:
    # Max length of function to check for naked returns
    max-func-lines: 30
    
  prealloc:
    # Use prealloc with for loops
    simple: true
    range-loops: true
    for-loops: true
    
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated
    disabled-checks:
      - whyNoLint
      - commentedOutCode
      - dupImport

issues:
  # Exclude directories
  exclude-dirs:
    - vendor
    - third_party
    - testdata
    - examples
    - generated
    - .git
    - node_modules
    
  # Maximum issues count per one linter
  max-issues-per-linter: 50
  
  # Maximum count of issues with the same text
  max-same-issues: 10
  
  # Exclude known issues
  exclude-rules:
    # Exclude error checks in tests
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gosec
        
    # Exclude certain linters for generated files
    - path: generated
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        
    # Allow init functions in main packages
    - path: cmd/.*/main\.go
      linters:
        - gochecknoinits
        
    # Allow global variables in main packages
    - path: cmd/.*/main\.go
      linters:
        - gochecknoglobals