services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - '${BACKEND_PORT:-8080}:8080'
      - '${GRPC_PORT:-50051}:50051'
    # user: '${UID:-1000}:${GID:-1000}'  # Temporarily disabled for permission fix
    environment:
      - GIN_MODE=${GIN_MODE:-debug}
      - DATABASE_TYPE=${DATABASE_TYPE:-sqlite}
      - VIEWRA_DATA_DIR=/app/viewra-data
      - VIEWRA_TRANSCODING_DIR=/viewra-data/transcoding
      - VIEWRA_DATABASE_PATH=${VIEWRA_DATABASE_PATH:-/app/viewra-data/viewra.db}
      - VIEWRA_PLUGIN_DIR=/app/data/plugins
      - PORT=8080
      - PLUGIN_DIR=/app/data/plugins
      - TMDB_API_KEY=${TMDB_API_KEY:-}
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
      - ./viewra-data:/app/viewra-data
      - ./viewra-data/transcoding:/viewra-data/transcoding
      - /cifs/fictionalserver/music:/media/music:ro
      - /cifs/fictionalserver/tv:/media/tv:ro
      - /cifs/fictionalserver/movies:/media/movies:ro
    networks:
      - viewra-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - '${FRONTEND_PORT:-5175}:5173'
    # user: '${UID:-1000}:${GID:-1000}'  # Temporarily disabled for permission fix
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8080}
    volumes:
      - ./frontend:/app
      - frontend-node-modules:/app/node_modules
      # Temporarily disabled NFS mounts for dev environment startup
      # - /nfs/fictionalserver/music:/media/music:ro
    depends_on:
      - backend
    networks:
      - viewra-network
    restart: unless-stopped

  sqliteweb:
    image: coleifer/sqlite-web:latest
    ports:
      - '${SQLITEWEB_PORT:-8081}:8080'
    volumes:
      - ./viewra-data:/data
    command: ['sqlite_web', '/data/viewra.db', '--host', '0.0.0.0', '--port', '8080']
    networks:
      - viewra-network
    restart: unless-stopped
    profiles:
      - dev
      - all

volumes:
  backend-data:
  frontend-node-modules:

networks:
  viewra-network:
    driver: bridge
