services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - '${BACKEND_PORT:-8080}:8080'
    environment:
      - GIN_MODE=${GIN_MODE:-debug}
      - DATABASE_TYPE=${DATABASE_TYPE:-sqlite}
      - SQLITE_PATH=${SQLITE_PATH:-/app/data/viewra.db}
      - PORT=8080
      - PLUGIN_DIR=/app/data/plugins
    volumes:
      - ./backend:/app
      - backend-data:/app/data
      - /nfs/fictionalserver/music:/media/music:ro
    networks:
      - viewra-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - '${FRONTEND_PORT:-5175}:5173'
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8080}
    volumes:
      - ./frontend:/app
      - frontend-node-modules:/app/node_modules
      - /nfs/fictionalserver/music:/media/music:ro
    depends_on:
      - backend
    networks:
      - viewra-network
    restart: unless-stopped

volumes:
  backend-data:
  frontend-node-modules:

networks:
  viewra-network:
    driver: bridge
