services:
  backend:
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
      - ./viewra-data:/app/viewra-data
      # Temporarily comment out NFS mounts to fix startup issue
      # - /nfs/fictionalserver/music:/media/music:ro
      # - /nfs/fictionalserver/tv:/media/tv:ro
      # - /nfs/fictionalserver/movies:/media/movies:ro

  frontend:
    volumes:
      - ./frontend:/app
      - frontend-node-modules:/app/node_modules
      # Temporarily comment out NFS mounts to allow frontend startup
      # - /nfs/fictionalserver/music:/media/music:ro
    # Override the main docker-compose.yml to remove the NFS mount
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8080}
