version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - GIN_MODE=debug
    volumes:
      # Future: Mount media directories here
      # - /path/to/media:/media:ro
      - ./backend:/app
    working_dir: /app
    command: go run cmd/viewra/main.go
    networks:
      - viewra-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev -- --host
    depends_on:
      - backend
    networks:
      - viewra-network

networks:
  viewra-network:
    driver: bridge
