services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - '${BACKEND_PORT:-8081}:8080'
    environment:
      - GIN_MODE=${GIN_MODE:-debug}
      - DATABASE_TYPE=${DATABASE_TYPE:-sqlite}
      - SQLITE_PATH=${SQLITE_PATH:-/app/data/viewra.db}
      - PORT=8080
    volumes:
      - ./backend:/app
      - backend-data:/app/data
    networks:
      - viewra-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - '${FRONTEND_PORT:-5175}:5173'
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8081}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - viewra-network
    restart: unless-stopped

volumes:
  backend-data:

networks:
  viewra-network:
    driver: bridge
