// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/proto/plugin/plugin_core.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthStatus_Status int32

const (
	HealthStatus_UNKNOWN   HealthStatus_Status = 0
	HealthStatus_HEALTHY   HealthStatus_Status = 1
	HealthStatus_DEGRADED  HealthStatus_Status = 2
	HealthStatus_UNHEALTHY HealthStatus_Status = 3
)

// Enum value maps for HealthStatus_Status.
var (
	HealthStatus_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "HEALTHY",
		2: "DEGRADED",
		3: "UNHEALTHY",
	}
	HealthStatus_Status_value = map[string]int32{
		"UNKNOWN":   0,
		"HEALTHY":   1,
		"DEGRADED":  2,
		"UNHEALTHY": 3,
	}
)

func (x HealthStatus_Status) Enum() *HealthStatus_Status {
	p := new(HealthStatus_Status)
	*p = x
	return p
}

func (x HealthStatus_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_plugin_plugin_core_proto_enumTypes[0].Descriptor()
}

func (HealthStatus_Status) Type() protoreflect.EnumType {
	return &file_api_proto_plugin_plugin_core_proto_enumTypes[0]
}

func (x HealthStatus_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus_Status.Descriptor instead.
func (HealthStatus_Status) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_core_proto_rawDescGZIP(), []int{3, 0}
}

type PluginInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for this plugin (e.g., "tmdb", "musicbrainz")
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Human-readable name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Semantic version (e.g., "1.2.0")
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// Minimum ViewRA version required
	MinHostVersion string `protobuf:"bytes,4,opt,name=min_host_version,json=minHostVersion,proto3" json:"min_host_version,omitempty"`
	// Plugin author
	Author string `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	// License (e.g., "MIT", "Apache-2.0")
	License string `protobuf:"bytes,6,opt,name=license,proto3" json:"license,omitempty"`
	// Categories this plugin implements (e.g., ["enricher"], ["notification_sink"])
	Categories []string `protobuf:"bytes,7,rep,name=categories,proto3" json:"categories,omitempty"`
	// Permissions this plugin requires
	Permissions   []string `protobuf:"bytes,8,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_api_proto_plugin_plugin_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_core_proto_rawDescGZIP(), []int{0}
}

func (x *PluginInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginInfo) GetMinHostVersion() string {
	if x != nil {
		return x.MinHostVersion
	}
	return ""
}

func (x *PluginInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PluginInfo) GetLicense() string {
	if x != nil {
		return x.License
	}
	return ""
}

func (x *PluginInfo) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *PluginInfo) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type InitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Host version for compatibility checking
	HostVersion string `protobuf:"bytes,1,opt,name=host_version,json=hostVersion,proto3" json:"host_version,omitempty"`
	// Path to plugin's data directory
	DataDir string `protobuf:"bytes,2,opt,name=data_dir,json=dataDir,proto3" json:"data_dir,omitempty"`
	// Initial configuration (if any)
	Config        []byte `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_api_proto_plugin_plugin_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_core_proto_rawDescGZIP(), []int{1}
}

func (x *InitRequest) GetHostVersion() string {
	if x != nil {
		return x.HostVersion
	}
	return ""
}

func (x *InitRequest) GetDataDir() string {
	if x != nil {
		return x.DataDir
	}
	return ""
}

func (x *InitRequest) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_api_proto_plugin_plugin_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_core_proto_rawDescGZIP(), []int{2}
}

func (x *InitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InitResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HealthStatus struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Status  HealthStatus_Status    `protobuf:"varint,1,opt,name=status,proto3,enum=viewra.plugin.v1.HealthStatus_Status" json:"status,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Optional metrics
	RequestsTotal int64   `protobuf:"varint,3,opt,name=requests_total,json=requestsTotal,proto3" json:"requests_total,omitempty"`
	ErrorsTotal   int64   `protobuf:"varint,4,opt,name=errors_total,json=errorsTotal,proto3" json:"errors_total,omitempty"`
	AvgLatencyMs  float64 `protobuf:"fixed64,5,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthStatus) Reset() {
	*x = HealthStatus{}
	mi := &file_api_proto_plugin_plugin_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthStatus) ProtoMessage() {}

func (x *HealthStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthStatus.ProtoReflect.Descriptor instead.
func (*HealthStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_core_proto_rawDescGZIP(), []int{3}
}

func (x *HealthStatus) GetStatus() HealthStatus_Status {
	if x != nil {
		return x.Status
	}
	return HealthStatus_UNKNOWN
}

func (x *HealthStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthStatus) GetRequestsTotal() int64 {
	if x != nil {
		return x.RequestsTotal
	}
	return 0
}

func (x *HealthStatus) GetErrorsTotal() int64 {
	if x != nil {
		return x.ErrorsTotal
	}
	return 0
}

func (x *HealthStatus) GetAvgLatencyMs() float64 {
	if x != nil {
		return x.AvgLatencyMs
	}
	return 0
}

type SettingsSchema struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON Schema for plugin settings
	JsonSchema    []byte `protobuf:"bytes,1,opt,name=json_schema,json=jsonSchema,proto3" json:"json_schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingsSchema) Reset() {
	*x = SettingsSchema{}
	mi := &file_api_proto_plugin_plugin_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingsSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsSchema) ProtoMessage() {}

func (x *SettingsSchema) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingsSchema.ProtoReflect.Descriptor instead.
func (*SettingsSchema) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_core_proto_rawDescGZIP(), []int{4}
}

func (x *SettingsSchema) GetJsonSchema() []byte {
	if x != nil {
		return x.JsonSchema
	}
	return nil
}

type Settings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON-encoded settings
	Json          []byte `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Settings) Reset() {
	*x = Settings{}
	mi := &file_api_proto_plugin_plugin_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Settings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Settings) ProtoMessage() {}

func (x *Settings) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Settings.ProtoReflect.Descriptor instead.
func (*Settings) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_core_proto_rawDescGZIP(), []int{5}
}

func (x *Settings) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

type ConfigureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_api_proto_plugin_plugin_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_core_proto_rawDescGZIP(), []int{6}
}

func (x *ConfigureResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigureResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type EventSubscriptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event types to subscribe to (e.g., ["media.added", "playback.started"])
	EventTypes    []string `protobuf:"bytes,1,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventSubscriptions) Reset() {
	*x = EventSubscriptions{}
	mi := &file_api_proto_plugin_plugin_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventSubscriptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventSubscriptions) ProtoMessage() {}

func (x *EventSubscriptions) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventSubscriptions.ProtoReflect.Descriptor instead.
func (*EventSubscriptions) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_core_proto_rawDescGZIP(), []int{7}
}

func (x *EventSubscriptions) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	TimestampUnix int64                  `protobuf:"varint,3,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"` // JSON-encoded payload
	CorrelationId string                 `protobuf:"bytes,5,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_api_proto_plugin_plugin_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_core_proto_rawDescGZIP(), []int{8}
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Event) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *Event) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type EventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handled       bool                   `protobuf:"varint,1,opt,name=handled,proto3" json:"handled,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventResponse) Reset() {
	*x = EventResponse{}
	mi := &file_api_proto_plugin_plugin_core_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponse) ProtoMessage() {}

func (x *EventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_core_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponse.ProtoReflect.Descriptor instead.
func (*EventResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_core_proto_rawDescGZIP(), []int{9}
}

func (x *EventResponse) GetHandled() bool {
	if x != nil {
		return x.Handled
	}
	return false
}

func (x *EventResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_api_proto_plugin_plugin_core_proto protoreflect.FileDescriptor

const file_api_proto_plugin_plugin_core_proto_rawDesc = "" +
	"\n" +
	"\"api/proto/plugin/plugin_core.proto\x12\x10viewra.plugin.v1\x1a\x1dapi/proto/plugin/common.proto\"\xe8\x01\n" +
	"\n" +
	"PluginInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12(\n" +
	"\x10min_host_version\x18\x04 \x01(\tR\x0eminHostVersion\x12\x16\n" +
	"\x06author\x18\x05 \x01(\tR\x06author\x12\x18\n" +
	"\alicense\x18\x06 \x01(\tR\alicense\x12\x1e\n" +
	"\n" +
	"categories\x18\a \x03(\tR\n" +
	"categories\x12 \n" +
	"\vpermissions\x18\b \x03(\tR\vpermissions\"c\n" +
	"\vInitRequest\x12!\n" +
	"\fhost_version\x18\x01 \x01(\tR\vhostVersion\x12\x19\n" +
	"\bdata_dir\x18\x02 \x01(\tR\adataDir\x12\x16\n" +
	"\x06config\x18\x03 \x01(\fR\x06config\">\n" +
	"\fInitResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x98\x02\n" +
	"\fHealthStatus\x12=\n" +
	"\x06status\x18\x01 \x01(\x0e2%.viewra.plugin.v1.HealthStatus.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0erequests_total\x18\x03 \x01(\x03R\rrequestsTotal\x12!\n" +
	"\ferrors_total\x18\x04 \x01(\x03R\verrorsTotal\x12$\n" +
	"\x0eavg_latency_ms\x18\x05 \x01(\x01R\favgLatencyMs\"?\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aHEALTHY\x10\x01\x12\f\n" +
	"\bDEGRADED\x10\x02\x12\r\n" +
	"\tUNHEALTHY\x10\x03\"1\n" +
	"\x0eSettingsSchema\x12\x1f\n" +
	"\vjson_schema\x18\x01 \x01(\fR\n" +
	"jsonSchema\"\x1e\n" +
	"\bSettings\x12\x12\n" +
	"\x04json\x18\x01 \x01(\fR\x04json\"C\n" +
	"\x11ConfigureResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"5\n" +
	"\x12EventSubscriptions\x12\x1f\n" +
	"\vevent_types\x18\x01 \x03(\tR\n" +
	"eventTypes\"\x9b\x01\n" +
	"\x05Event\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12%\n" +
	"\x0etimestamp_unix\x18\x03 \x01(\x03R\rtimestampUnix\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12%\n" +
	"\x0ecorrelation_id\x18\x05 \x01(\tR\rcorrelationId\"?\n" +
	"\rEventResponse\x12\x18\n" +
	"\ahandled\x18\x01 \x01(\bR\ahandled\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xd7\x04\n" +
	"\n" +
	"PluginCore\x12@\n" +
	"\aGetInfo\x12\x17.viewra.plugin.v1.Empty\x1a\x1c.viewra.plugin.v1.PluginInfo\x12K\n" +
	"\n" +
	"Initialize\x12\x1d.viewra.plugin.v1.InitRequest\x1a\x1e.viewra.plugin.v1.InitResponse\x12<\n" +
	"\bShutdown\x12\x17.viewra.plugin.v1.Empty\x1a\x17.viewra.plugin.v1.Empty\x12F\n" +
	"\vHealthCheck\x12\x17.viewra.plugin.v1.Empty\x1a\x1e.viewra.plugin.v1.HealthStatus\x12N\n" +
	"\x11GetSettingsSchema\x12\x17.viewra.plugin.v1.Empty\x1a .viewra.plugin.v1.SettingsSchema\x12L\n" +
	"\tConfigure\x12\x1a.viewra.plugin.v1.Settings\x1a#.viewra.plugin.v1.ConfigureResponse\x12Q\n" +
	"\x10GetSubscriptions\x12\x17.viewra.plugin.v1.Empty\x1a$.viewra.plugin.v1.EventSubscriptions\x12C\n" +
	"\aOnEvent\x12\x17.viewra.plugin.v1.Event\x1a\x1f.viewra.plugin.v1.EventResponseB8Z6github.com/mantonx/viewra/api/proto/plugin/v1;pluginv1b\x06proto3"

var (
	file_api_proto_plugin_plugin_core_proto_rawDescOnce sync.Once
	file_api_proto_plugin_plugin_core_proto_rawDescData []byte
)

func file_api_proto_plugin_plugin_core_proto_rawDescGZIP() []byte {
	file_api_proto_plugin_plugin_core_proto_rawDescOnce.Do(func() {
		file_api_proto_plugin_plugin_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_plugin_plugin_core_proto_rawDesc), len(file_api_proto_plugin_plugin_core_proto_rawDesc)))
	})
	return file_api_proto_plugin_plugin_core_proto_rawDescData
}

var file_api_proto_plugin_plugin_core_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_plugin_plugin_core_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_proto_plugin_plugin_core_proto_goTypes = []any{
	(HealthStatus_Status)(0),   // 0: viewra.plugin.v1.HealthStatus.Status
	(*PluginInfo)(nil),         // 1: viewra.plugin.v1.PluginInfo
	(*InitRequest)(nil),        // 2: viewra.plugin.v1.InitRequest
	(*InitResponse)(nil),       // 3: viewra.plugin.v1.InitResponse
	(*HealthStatus)(nil),       // 4: viewra.plugin.v1.HealthStatus
	(*SettingsSchema)(nil),     // 5: viewra.plugin.v1.SettingsSchema
	(*Settings)(nil),           // 6: viewra.plugin.v1.Settings
	(*ConfigureResponse)(nil),  // 7: viewra.plugin.v1.ConfigureResponse
	(*EventSubscriptions)(nil), // 8: viewra.plugin.v1.EventSubscriptions
	(*Event)(nil),              // 9: viewra.plugin.v1.Event
	(*EventResponse)(nil),      // 10: viewra.plugin.v1.EventResponse
	(*Empty)(nil),              // 11: viewra.plugin.v1.Empty
}
var file_api_proto_plugin_plugin_core_proto_depIdxs = []int32{
	0,  // 0: viewra.plugin.v1.HealthStatus.status:type_name -> viewra.plugin.v1.HealthStatus.Status
	11, // 1: viewra.plugin.v1.PluginCore.GetInfo:input_type -> viewra.plugin.v1.Empty
	2,  // 2: viewra.plugin.v1.PluginCore.Initialize:input_type -> viewra.plugin.v1.InitRequest
	11, // 3: viewra.plugin.v1.PluginCore.Shutdown:input_type -> viewra.plugin.v1.Empty
	11, // 4: viewra.plugin.v1.PluginCore.HealthCheck:input_type -> viewra.plugin.v1.Empty
	11, // 5: viewra.plugin.v1.PluginCore.GetSettingsSchema:input_type -> viewra.plugin.v1.Empty
	6,  // 6: viewra.plugin.v1.PluginCore.Configure:input_type -> viewra.plugin.v1.Settings
	11, // 7: viewra.plugin.v1.PluginCore.GetSubscriptions:input_type -> viewra.plugin.v1.Empty
	9,  // 8: viewra.plugin.v1.PluginCore.OnEvent:input_type -> viewra.plugin.v1.Event
	1,  // 9: viewra.plugin.v1.PluginCore.GetInfo:output_type -> viewra.plugin.v1.PluginInfo
	3,  // 10: viewra.plugin.v1.PluginCore.Initialize:output_type -> viewra.plugin.v1.InitResponse
	11, // 11: viewra.plugin.v1.PluginCore.Shutdown:output_type -> viewra.plugin.v1.Empty
	4,  // 12: viewra.plugin.v1.PluginCore.HealthCheck:output_type -> viewra.plugin.v1.HealthStatus
	5,  // 13: viewra.plugin.v1.PluginCore.GetSettingsSchema:output_type -> viewra.plugin.v1.SettingsSchema
	7,  // 14: viewra.plugin.v1.PluginCore.Configure:output_type -> viewra.plugin.v1.ConfigureResponse
	8,  // 15: viewra.plugin.v1.PluginCore.GetSubscriptions:output_type -> viewra.plugin.v1.EventSubscriptions
	10, // 16: viewra.plugin.v1.PluginCore.OnEvent:output_type -> viewra.plugin.v1.EventResponse
	9,  // [9:17] is the sub-list for method output_type
	1,  // [1:9] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_plugin_plugin_core_proto_init() }
func file_api_proto_plugin_plugin_core_proto_init() {
	if File_api_proto_plugin_plugin_core_proto != nil {
		return
	}
	file_api_proto_plugin_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_plugin_plugin_core_proto_rawDesc), len(file_api_proto_plugin_plugin_core_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_plugin_plugin_core_proto_goTypes,
		DependencyIndexes: file_api_proto_plugin_plugin_core_proto_depIdxs,
		EnumInfos:         file_api_proto_plugin_plugin_core_proto_enumTypes,
		MessageInfos:      file_api_proto_plugin_plugin_core_proto_msgTypes,
	}.Build()
	File_api_proto_plugin_plugin_core_proto = out.File
	file_api_proto_plugin_plugin_core_proto_goTypes = nil
	file_api_proto_plugin_plugin_core_proto_depIdxs = nil
}
