// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/proto/plugin/plugin_ai.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SemanticSearchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Natural language query
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Filter by entity types (empty = all types)
	// Values: "movie", "tv_show", "tv_episode", "music_artist", "music_album", "music_track"
	EntityTypes []string `protobuf:"bytes,2,rep,name=entity_types,json=entityTypes,proto3" json:"entity_types,omitempty"`
	// Maximum number of results (default: 20, max: 100)
	Limit int32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// User ID for context enrichment (optional)
	// When provided, enables location-aware recommendations if the user has opted in
	UserId        string `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemanticSearchRequest) Reset() {
	*x = SemanticSearchRequest{}
	mi := &file_api_proto_plugin_plugin_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticSearchRequest) ProtoMessage() {}

func (x *SemanticSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticSearchRequest.ProtoReflect.Descriptor instead.
func (*SemanticSearchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_ai_proto_rawDescGZIP(), []int{0}
}

func (x *SemanticSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SemanticSearchRequest) GetEntityTypes() []string {
	if x != nil {
		return x.EntityTypes
	}
	return nil
}

func (x *SemanticSearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SemanticSearchRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SemanticSearchResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Results       []*SemanticSearchResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Total         int32                   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // Total matching results (may be more than returned)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemanticSearchResponse) Reset() {
	*x = SemanticSearchResponse{}
	mi := &file_api_proto_plugin_plugin_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticSearchResponse) ProtoMessage() {}

func (x *SemanticSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticSearchResponse.ProtoReflect.Descriptor instead.
func (*SemanticSearchResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_ai_proto_rawDescGZIP(), []int{1}
}

func (x *SemanticSearchResponse) GetResults() []*SemanticSearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SemanticSearchResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SemanticSearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    string                 `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityId      int64                  `protobuf:"varint,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Similarity    float32                `protobuf:"fixed32,3,opt,name=similarity,proto3" json:"similarity,omitempty"` // 0.0 - 1.0
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`               // The indexed text snippet
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemanticSearchResult) Reset() {
	*x = SemanticSearchResult{}
	mi := &file_api_proto_plugin_plugin_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticSearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticSearchResult) ProtoMessage() {}

func (x *SemanticSearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticSearchResult.ProtoReflect.Descriptor instead.
func (*SemanticSearchResult) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_ai_proto_rawDescGZIP(), []int{2}
}

func (x *SemanticSearchResult) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *SemanticSearchResult) GetEntityId() int64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *SemanticSearchResult) GetSimilarity() float32 {
	if x != nil {
		return x.Similarity
	}
	return 0
}

func (x *SemanticSearchResult) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type FindSimilarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    string                 `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityId      int64                  `protobuf:"varint,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindSimilarRequest) Reset() {
	*x = FindSimilarRequest{}
	mi := &file_api_proto_plugin_plugin_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindSimilarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSimilarRequest) ProtoMessage() {}

func (x *FindSimilarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSimilarRequest.ProtoReflect.Descriptor instead.
func (*FindSimilarRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_ai_proto_rawDescGZIP(), []int{3}
}

func (x *FindSimilarRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *FindSimilarRequest) GetEntityId() int64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *FindSimilarRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type AISearchStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether indexing is currently running
	IsIndexing bool `protobuf:"varint,1,opt,name=is_indexing,json=isIndexing,proto3" json:"is_indexing,omitempty"`
	// Current indexing progress (if indexing)
	Progress *IndexingProgress `protobuf:"bytes,2,opt,name=progress,proto3" json:"progress,omitempty"`
	// Stats per entity type
	Stats []*EntityTypeStats `protobuf:"bytes,3,rep,name=stats,proto3" json:"stats,omitempty"`
	// Total indexed items
	TotalIndexed  int64 `protobuf:"varint,4,opt,name=total_indexed,json=totalIndexed,proto3" json:"total_indexed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AISearchStatus) Reset() {
	*x = AISearchStatus{}
	mi := &file_api_proto_plugin_plugin_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AISearchStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AISearchStatus) ProtoMessage() {}

func (x *AISearchStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AISearchStatus.ProtoReflect.Descriptor instead.
func (*AISearchStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_ai_proto_rawDescGZIP(), []int{4}
}

func (x *AISearchStatus) GetIsIndexing() bool {
	if x != nil {
		return x.IsIndexing
	}
	return false
}

func (x *AISearchStatus) GetProgress() *IndexingProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

func (x *AISearchStatus) GetStats() []*EntityTypeStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *AISearchStatus) GetTotalIndexed() int64 {
	if x != nil {
		return x.TotalIndexed
	}
	return 0
}

type IndexingProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    string                 `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Processed     int64                  `protobuf:"varint,3,opt,name=processed,proto3" json:"processed,omitempty"`
	Failed        int64                  `protobuf:"varint,4,opt,name=failed,proto3" json:"failed,omitempty"`
	LastError     string                 `protobuf:"bytes,5,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	StartedAt     int64                  `protobuf:"varint,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`       // Unix timestamp
	LastUpdated   int64                  `protobuf:"varint,7,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexingProgress) Reset() {
	*x = IndexingProgress{}
	mi := &file_api_proto_plugin_plugin_ai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexingProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexingProgress) ProtoMessage() {}

func (x *IndexingProgress) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_ai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexingProgress.ProtoReflect.Descriptor instead.
func (*IndexingProgress) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_ai_proto_rawDescGZIP(), []int{5}
}

func (x *IndexingProgress) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *IndexingProgress) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *IndexingProgress) GetProcessed() int64 {
	if x != nil {
		return x.Processed
	}
	return 0
}

func (x *IndexingProgress) GetFailed() int64 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *IndexingProgress) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *IndexingProgress) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *IndexingProgress) GetLastUpdated() int64 {
	if x != nil {
		return x.LastUpdated
	}
	return 0
}

type EntityTypeStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    string                 `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	Indexed       int64                  `protobuf:"varint,2,opt,name=indexed,proto3" json:"indexed,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"` // Total items of this type in library
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityTypeStats) Reset() {
	*x = EntityTypeStats{}
	mi := &file_api_proto_plugin_plugin_ai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityTypeStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityTypeStats) ProtoMessage() {}

func (x *EntityTypeStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_ai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityTypeStats.ProtoReflect.Descriptor instead.
func (*EntityTypeStats) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_ai_proto_rawDescGZIP(), []int{6}
}

func (x *EntityTypeStats) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *EntityTypeStats) GetIndexed() int64 {
	if x != nil {
		return x.Indexed
	}
	return 0
}

func (x *EntityTypeStats) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type IndexLibraryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LibraryId     int64                  `protobuf:"varint,1,opt,name=library_id,json=libraryId,proto3" json:"library_id,omitempty"`
	LibraryType   string                 `protobuf:"bytes,2,opt,name=library_type,json=libraryType,proto3" json:"library_type,omitempty"` // "movie", "tv", "music"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexLibraryRequest) Reset() {
	*x = IndexLibraryRequest{}
	mi := &file_api_proto_plugin_plugin_ai_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexLibraryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexLibraryRequest) ProtoMessage() {}

func (x *IndexLibraryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_ai_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexLibraryRequest.ProtoReflect.Descriptor instead.
func (*IndexLibraryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_ai_proto_rawDescGZIP(), []int{7}
}

func (x *IndexLibraryRequest) GetLibraryId() int64 {
	if x != nil {
		return x.LibraryId
	}
	return 0
}

func (x *IndexLibraryRequest) GetLibraryType() string {
	if x != nil {
		return x.LibraryType
	}
	return ""
}

type IndexLibraryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Started       bool                   `protobuf:"varint,1,opt,name=started,proto3" json:"started,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Error message if not started
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexLibraryResponse) Reset() {
	*x = IndexLibraryResponse{}
	mi := &file_api_proto_plugin_plugin_ai_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexLibraryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexLibraryResponse) ProtoMessage() {}

func (x *IndexLibraryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_ai_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexLibraryResponse.ProtoReflect.Descriptor instead.
func (*IndexLibraryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_ai_proto_rawDescGZIP(), []int{8}
}

func (x *IndexLibraryResponse) GetStarted() bool {
	if x != nil {
		return x.Started
	}
	return false
}

func (x *IndexLibraryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_plugin_plugin_ai_proto protoreflect.FileDescriptor

const file_api_proto_plugin_plugin_ai_proto_rawDesc = "" +
	"\n" +
	" api/proto/plugin/plugin_ai.proto\x12\x10viewra.plugin.v1\x1a\x1dapi/proto/plugin/common.proto\"\x7f\n" +
	"\x15SemanticSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12!\n" +
	"\fentity_types\x18\x02 \x03(\tR\ventityTypes\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\"p\n" +
	"\x16SemanticSearchResponse\x12@\n" +
	"\aresults\x18\x01 \x03(\v2&.viewra.plugin.v1.SemanticSearchResultR\aresults\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x88\x01\n" +
	"\x14SemanticSearchResult\x12\x1f\n" +
	"\ventity_type\x18\x01 \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\x03R\bentityId\x12\x1e\n" +
	"\n" +
	"similarity\x18\x03 \x01(\x02R\n" +
	"similarity\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\"h\n" +
	"\x12FindSimilarRequest\x12\x1f\n" +
	"\ventity_type\x18\x01 \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\x03R\bentityId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xcf\x01\n" +
	"\x0eAISearchStatus\x12\x1f\n" +
	"\vis_indexing\x18\x01 \x01(\bR\n" +
	"isIndexing\x12>\n" +
	"\bprogress\x18\x02 \x01(\v2\".viewra.plugin.v1.IndexingProgressR\bprogress\x127\n" +
	"\x05stats\x18\x03 \x03(\v2!.viewra.plugin.v1.EntityTypeStatsR\x05stats\x12#\n" +
	"\rtotal_indexed\x18\x04 \x01(\x03R\ftotalIndexed\"\xe0\x01\n" +
	"\x10IndexingProgress\x12\x1f\n" +
	"\ventity_type\x18\x01 \x01(\tR\n" +
	"entityType\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x1c\n" +
	"\tprocessed\x18\x03 \x01(\x03R\tprocessed\x12\x16\n" +
	"\x06failed\x18\x04 \x01(\x03R\x06failed\x12\x1d\n" +
	"\n" +
	"last_error\x18\x05 \x01(\tR\tlastError\x12\x1d\n" +
	"\n" +
	"started_at\x18\x06 \x01(\x03R\tstartedAt\x12!\n" +
	"\flast_updated\x18\a \x01(\x03R\vlastUpdated\"b\n" +
	"\x0fEntityTypeStats\x12\x1f\n" +
	"\ventity_type\x18\x01 \x01(\tR\n" +
	"entityType\x12\x18\n" +
	"\aindexed\x18\x02 \x01(\x03R\aindexed\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\"W\n" +
	"\x13IndexLibraryRequest\x12\x1d\n" +
	"\n" +
	"library_id\x18\x01 \x01(\x03R\tlibraryId\x12!\n" +
	"\flibrary_type\x18\x02 \x01(\tR\vlibraryType\"J\n" +
	"\x14IndexLibraryResponse\x12\x18\n" +
	"\astarted\x18\x01 \x01(\bR\astarted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xb1\x03\n" +
	"\bAISearch\x12[\n" +
	"\x06Search\x12'.viewra.plugin.v1.SemanticSearchRequest\x1a(.viewra.plugin.v1.SemanticSearchResponse\x12]\n" +
	"\vFindSimilar\x12$.viewra.plugin.v1.FindSimilarRequest\x1a(.viewra.plugin.v1.SemanticSearchResponse\x12F\n" +
	"\tGetStatus\x12\x17.viewra.plugin.v1.Empty\x1a .viewra.plugin.v1.AISearchStatus\x12]\n" +
	"\fIndexLibrary\x12%.viewra.plugin.v1.IndexLibraryRequest\x1a&.viewra.plugin.v1.IndexLibraryResponse\x12B\n" +
	"\x0eCancelIndexing\x12\x17.viewra.plugin.v1.Empty\x1a\x17.viewra.plugin.v1.EmptyB8Z6github.com/mantonx/viewra/api/proto/plugin/v1;pluginv1b\x06proto3"

var (
	file_api_proto_plugin_plugin_ai_proto_rawDescOnce sync.Once
	file_api_proto_plugin_plugin_ai_proto_rawDescData []byte
)

func file_api_proto_plugin_plugin_ai_proto_rawDescGZIP() []byte {
	file_api_proto_plugin_plugin_ai_proto_rawDescOnce.Do(func() {
		file_api_proto_plugin_plugin_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_plugin_plugin_ai_proto_rawDesc), len(file_api_proto_plugin_plugin_ai_proto_rawDesc)))
	})
	return file_api_proto_plugin_plugin_ai_proto_rawDescData
}

var file_api_proto_plugin_plugin_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_proto_plugin_plugin_ai_proto_goTypes = []any{
	(*SemanticSearchRequest)(nil),  // 0: viewra.plugin.v1.SemanticSearchRequest
	(*SemanticSearchResponse)(nil), // 1: viewra.plugin.v1.SemanticSearchResponse
	(*SemanticSearchResult)(nil),   // 2: viewra.plugin.v1.SemanticSearchResult
	(*FindSimilarRequest)(nil),     // 3: viewra.plugin.v1.FindSimilarRequest
	(*AISearchStatus)(nil),         // 4: viewra.plugin.v1.AISearchStatus
	(*IndexingProgress)(nil),       // 5: viewra.plugin.v1.IndexingProgress
	(*EntityTypeStats)(nil),        // 6: viewra.plugin.v1.EntityTypeStats
	(*IndexLibraryRequest)(nil),    // 7: viewra.plugin.v1.IndexLibraryRequest
	(*IndexLibraryResponse)(nil),   // 8: viewra.plugin.v1.IndexLibraryResponse
	(*Empty)(nil),                  // 9: viewra.plugin.v1.Empty
}
var file_api_proto_plugin_plugin_ai_proto_depIdxs = []int32{
	2, // 0: viewra.plugin.v1.SemanticSearchResponse.results:type_name -> viewra.plugin.v1.SemanticSearchResult
	5, // 1: viewra.plugin.v1.AISearchStatus.progress:type_name -> viewra.plugin.v1.IndexingProgress
	6, // 2: viewra.plugin.v1.AISearchStatus.stats:type_name -> viewra.plugin.v1.EntityTypeStats
	0, // 3: viewra.plugin.v1.AISearch.Search:input_type -> viewra.plugin.v1.SemanticSearchRequest
	3, // 4: viewra.plugin.v1.AISearch.FindSimilar:input_type -> viewra.plugin.v1.FindSimilarRequest
	9, // 5: viewra.plugin.v1.AISearch.GetStatus:input_type -> viewra.plugin.v1.Empty
	7, // 6: viewra.plugin.v1.AISearch.IndexLibrary:input_type -> viewra.plugin.v1.IndexLibraryRequest
	9, // 7: viewra.plugin.v1.AISearch.CancelIndexing:input_type -> viewra.plugin.v1.Empty
	1, // 8: viewra.plugin.v1.AISearch.Search:output_type -> viewra.plugin.v1.SemanticSearchResponse
	1, // 9: viewra.plugin.v1.AISearch.FindSimilar:output_type -> viewra.plugin.v1.SemanticSearchResponse
	4, // 10: viewra.plugin.v1.AISearch.GetStatus:output_type -> viewra.plugin.v1.AISearchStatus
	8, // 11: viewra.plugin.v1.AISearch.IndexLibrary:output_type -> viewra.plugin.v1.IndexLibraryResponse
	9, // 12: viewra.plugin.v1.AISearch.CancelIndexing:output_type -> viewra.plugin.v1.Empty
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_plugin_plugin_ai_proto_init() }
func file_api_proto_plugin_plugin_ai_proto_init() {
	if File_api_proto_plugin_plugin_ai_proto != nil {
		return
	}
	file_api_proto_plugin_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_plugin_plugin_ai_proto_rawDesc), len(file_api_proto_plugin_plugin_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_plugin_plugin_ai_proto_goTypes,
		DependencyIndexes: file_api_proto_plugin_plugin_ai_proto_depIdxs,
		MessageInfos:      file_api_proto_plugin_plugin_ai_proto_msgTypes,
	}.Build()
	File_api_proto_plugin_plugin_ai_proto = out.File
	file_api_proto_plugin_plugin_ai_proto_goTypes = nil
	file_api_proto_plugin_plugin_ai_proto_depIdxs = nil
}
