// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: api/proto/plugin/provider.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginProvider_GetCapabilities_FullMethodName        = "/viewra.plugin.v1.PluginProvider/GetCapabilities"
	PluginProvider_ListModels_FullMethodName             = "/viewra.plugin.v1.PluginProvider/ListModels"
	PluginProvider_GenerateEmbedding_FullMethodName      = "/viewra.plugin.v1.PluginProvider/GenerateEmbedding"
	PluginProvider_GenerateEmbeddingBatch_FullMethodName = "/viewra.plugin.v1.PluginProvider/GenerateEmbeddingBatch"
	PluginProvider_Chat_FullMethodName                   = "/viewra.plugin.v1.PluginProvider/Chat"
	PluginProvider_ChatStream_FullMethodName             = "/viewra.plugin.v1.PluginProvider/ChatStream"
	PluginProvider_HealthCheck_FullMethodName            = "/viewra.plugin.v1.PluginProvider/HealthCheck"
)

// PluginProviderClient is the client API for PluginProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PluginProvider is implemented by AI provider plugins (ollama, openai, etc.).
// The host calls these methods when a consumer plugin requests AI services.
// Provider plugins register themselves with the host on startup.
type PluginProviderClient interface {
	// GetCapabilities returns what this provider supports.
	// Called by the host during provider registration.
	GetCapabilities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProviderCapabilities, error)
	// ListModels returns available models for this provider.
	// For cloud providers, this may fetch from their APIs.
	// For Ollama, this returns locally installed models.
	ListModels(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProviderModelList, error)
	// GenerateEmbedding generates an embedding for a single text.
	GenerateEmbedding(ctx context.Context, in *ProviderEmbeddingRequest, opts ...grpc.CallOption) (*EmbeddingResponse, error)
	// GenerateEmbeddingBatch generates embeddings for multiple texts.
	GenerateEmbeddingBatch(ctx context.Context, in *ProviderEmbeddingBatchRequest, opts ...grpc.CallOption) (*EmbeddingBatchResponse, error)
	// Chat sends a chat completion request.
	Chat(ctx context.Context, in *ProviderChatRequest, opts ...grpc.CallOption) (*ChatResponse, error)
	// ChatStream sends a streaming chat completion request.
	ChatStream(ctx context.Context, in *ProviderChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatStreamChunk], error)
	// HealthCheck verifies the provider is working.
	// Checks API key validity, service reachability, etc.
	HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProviderHealthStatus, error)
}

type pluginProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginProviderClient(cc grpc.ClientConnInterface) PluginProviderClient {
	return &pluginProviderClient{cc}
}

func (c *pluginProviderClient) GetCapabilities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProviderCapabilities, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProviderCapabilities)
	err := c.cc.Invoke(ctx, PluginProvider_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginProviderClient) ListModels(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProviderModelList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProviderModelList)
	err := c.cc.Invoke(ctx, PluginProvider_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginProviderClient) GenerateEmbedding(ctx context.Context, in *ProviderEmbeddingRequest, opts ...grpc.CallOption) (*EmbeddingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbeddingResponse)
	err := c.cc.Invoke(ctx, PluginProvider_GenerateEmbedding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginProviderClient) GenerateEmbeddingBatch(ctx context.Context, in *ProviderEmbeddingBatchRequest, opts ...grpc.CallOption) (*EmbeddingBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbeddingBatchResponse)
	err := c.cc.Invoke(ctx, PluginProvider_GenerateEmbeddingBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginProviderClient) Chat(ctx context.Context, in *ProviderChatRequest, opts ...grpc.CallOption) (*ChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatResponse)
	err := c.cc.Invoke(ctx, PluginProvider_Chat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginProviderClient) ChatStream(ctx context.Context, in *ProviderChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatStreamChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PluginProvider_ServiceDesc.Streams[0], PluginProvider_ChatStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProviderChatRequest, ChatStreamChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PluginProvider_ChatStreamClient = grpc.ServerStreamingClient[ChatStreamChunk]

func (c *pluginProviderClient) HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProviderHealthStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProviderHealthStatus)
	err := c.cc.Invoke(ctx, PluginProvider_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginProviderServer is the server API for PluginProvider service.
// All implementations must embed UnimplementedPluginProviderServer
// for forward compatibility.
//
// PluginProvider is implemented by AI provider plugins (ollama, openai, etc.).
// The host calls these methods when a consumer plugin requests AI services.
// Provider plugins register themselves with the host on startup.
type PluginProviderServer interface {
	// GetCapabilities returns what this provider supports.
	// Called by the host during provider registration.
	GetCapabilities(context.Context, *Empty) (*ProviderCapabilities, error)
	// ListModels returns available models for this provider.
	// For cloud providers, this may fetch from their APIs.
	// For Ollama, this returns locally installed models.
	ListModels(context.Context, *Empty) (*ProviderModelList, error)
	// GenerateEmbedding generates an embedding for a single text.
	GenerateEmbedding(context.Context, *ProviderEmbeddingRequest) (*EmbeddingResponse, error)
	// GenerateEmbeddingBatch generates embeddings for multiple texts.
	GenerateEmbeddingBatch(context.Context, *ProviderEmbeddingBatchRequest) (*EmbeddingBatchResponse, error)
	// Chat sends a chat completion request.
	Chat(context.Context, *ProviderChatRequest) (*ChatResponse, error)
	// ChatStream sends a streaming chat completion request.
	ChatStream(*ProviderChatRequest, grpc.ServerStreamingServer[ChatStreamChunk]) error
	// HealthCheck verifies the provider is working.
	// Checks API key validity, service reachability, etc.
	HealthCheck(context.Context, *Empty) (*ProviderHealthStatus, error)
	mustEmbedUnimplementedPluginProviderServer()
}

// UnimplementedPluginProviderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginProviderServer struct{}

func (UnimplementedPluginProviderServer) GetCapabilities(context.Context, *Empty) (*ProviderCapabilities, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedPluginProviderServer) ListModels(context.Context, *Empty) (*ProviderModelList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedPluginProviderServer) GenerateEmbedding(context.Context, *ProviderEmbeddingRequest) (*EmbeddingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateEmbedding not implemented")
}
func (UnimplementedPluginProviderServer) GenerateEmbeddingBatch(context.Context, *ProviderEmbeddingBatchRequest) (*EmbeddingBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateEmbeddingBatch not implemented")
}
func (UnimplementedPluginProviderServer) Chat(context.Context, *ProviderChatRequest) (*ChatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedPluginProviderServer) ChatStream(*ProviderChatRequest, grpc.ServerStreamingServer[ChatStreamChunk]) error {
	return status.Errorf(codes.Unimplemented, "method ChatStream not implemented")
}
func (UnimplementedPluginProviderServer) HealthCheck(context.Context, *Empty) (*ProviderHealthStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedPluginProviderServer) mustEmbedUnimplementedPluginProviderServer() {}
func (UnimplementedPluginProviderServer) testEmbeddedByValue()                        {}

// UnsafePluginProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginProviderServer will
// result in compilation errors.
type UnsafePluginProviderServer interface {
	mustEmbedUnimplementedPluginProviderServer()
}

func RegisterPluginProviderServer(s grpc.ServiceRegistrar, srv PluginProviderServer) {
	// If the following call pancis, it indicates UnimplementedPluginProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginProvider_ServiceDesc, srv)
}

func _PluginProvider_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginProviderServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginProvider_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginProviderServer).GetCapabilities(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginProvider_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginProviderServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginProvider_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginProviderServer).ListModels(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginProvider_GenerateEmbedding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProviderEmbeddingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginProviderServer).GenerateEmbedding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginProvider_GenerateEmbedding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginProviderServer).GenerateEmbedding(ctx, req.(*ProviderEmbeddingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginProvider_GenerateEmbeddingBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProviderEmbeddingBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginProviderServer).GenerateEmbeddingBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginProvider_GenerateEmbeddingBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginProviderServer).GenerateEmbeddingBatch(ctx, req.(*ProviderEmbeddingBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginProvider_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProviderChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginProviderServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginProvider_Chat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginProviderServer).Chat(ctx, req.(*ProviderChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginProvider_ChatStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProviderChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PluginProviderServer).ChatStream(m, &grpc.GenericServerStream[ProviderChatRequest, ChatStreamChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PluginProvider_ChatStreamServer = grpc.ServerStreamingServer[ChatStreamChunk]

func _PluginProvider_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginProviderServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginProvider_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginProviderServer).HealthCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginProvider_ServiceDesc is the grpc.ServiceDesc for PluginProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "viewra.plugin.v1.PluginProvider",
	HandlerType: (*PluginProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCapabilities",
			Handler:    _PluginProvider_GetCapabilities_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _PluginProvider_ListModels_Handler,
		},
		{
			MethodName: "GenerateEmbedding",
			Handler:    _PluginProvider_GenerateEmbedding_Handler,
		},
		{
			MethodName: "GenerateEmbeddingBatch",
			Handler:    _PluginProvider_GenerateEmbeddingBatch_Handler,
		},
		{
			MethodName: "Chat",
			Handler:    _PluginProvider_Chat_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _PluginProvider_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChatStream",
			Handler:       _PluginProvider_ChatStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/plugin/provider.proto",
}
