// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: api/proto/plugin/search_provider.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SearchProviderService_Search_FullMethodName          = "/viewra.plugin.v1.SearchProviderService/Search"
	SearchProviderService_GetSuggestions_FullMethodName  = "/viewra.plugin.v1.SearchProviderService/GetSuggestions"
	SearchProviderService_GetProviderInfo_FullMethodName = "/viewra.plugin.v1.SearchProviderService/GetProviderInfo"
)

// SearchProviderServiceClient is the client API for SearchProviderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SearchProviderService is implemented by plugins that provide search functionality.
// Multiple providers can be registered; the highest priority enabled one is the default.
type SearchProviderServiceClient interface {
	// Search performs a search with the given query.
	Search(ctx context.Context, in *SearchProviderRequest, opts ...grpc.CallOption) (*SearchProviderResponse, error)
	// GetSuggestions returns contextual suggestions for the search hero.
	GetSuggestions(ctx context.Context, in *SuggestionRequest, opts ...grpc.CallOption) (*SuggestionResponse, error)
	// GetProviderInfo returns metadata about this search provider.
	GetProviderInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SearchProviderInfo, error)
}

type searchProviderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchProviderServiceClient(cc grpc.ClientConnInterface) SearchProviderServiceClient {
	return &searchProviderServiceClient{cc}
}

func (c *searchProviderServiceClient) Search(ctx context.Context, in *SearchProviderRequest, opts ...grpc.CallOption) (*SearchProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchProviderResponse)
	err := c.cc.Invoke(ctx, SearchProviderService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchProviderServiceClient) GetSuggestions(ctx context.Context, in *SuggestionRequest, opts ...grpc.CallOption) (*SuggestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuggestionResponse)
	err := c.cc.Invoke(ctx, SearchProviderService_GetSuggestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchProviderServiceClient) GetProviderInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SearchProviderInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchProviderInfo)
	err := c.cc.Invoke(ctx, SearchProviderService_GetProviderInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchProviderServiceServer is the server API for SearchProviderService service.
// All implementations must embed UnimplementedSearchProviderServiceServer
// for forward compatibility.
//
// SearchProviderService is implemented by plugins that provide search functionality.
// Multiple providers can be registered; the highest priority enabled one is the default.
type SearchProviderServiceServer interface {
	// Search performs a search with the given query.
	Search(context.Context, *SearchProviderRequest) (*SearchProviderResponse, error)
	// GetSuggestions returns contextual suggestions for the search hero.
	GetSuggestions(context.Context, *SuggestionRequest) (*SuggestionResponse, error)
	// GetProviderInfo returns metadata about this search provider.
	GetProviderInfo(context.Context, *Empty) (*SearchProviderInfo, error)
	mustEmbedUnimplementedSearchProviderServiceServer()
}

// UnimplementedSearchProviderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSearchProviderServiceServer struct{}

func (UnimplementedSearchProviderServiceServer) Search(context.Context, *SearchProviderRequest) (*SearchProviderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedSearchProviderServiceServer) GetSuggestions(context.Context, *SuggestionRequest) (*SuggestionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSuggestions not implemented")
}
func (UnimplementedSearchProviderServiceServer) GetProviderInfo(context.Context, *Empty) (*SearchProviderInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProviderInfo not implemented")
}
func (UnimplementedSearchProviderServiceServer) mustEmbedUnimplementedSearchProviderServiceServer() {}
func (UnimplementedSearchProviderServiceServer) testEmbeddedByValue()                               {}

// UnsafeSearchProviderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchProviderServiceServer will
// result in compilation errors.
type UnsafeSearchProviderServiceServer interface {
	mustEmbedUnimplementedSearchProviderServiceServer()
}

func RegisterSearchProviderServiceServer(s grpc.ServiceRegistrar, srv SearchProviderServiceServer) {
	// If the following call pancis, it indicates UnimplementedSearchProviderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SearchProviderService_ServiceDesc, srv)
}

func _SearchProviderService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchProviderServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchProviderService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchProviderServiceServer).Search(ctx, req.(*SearchProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchProviderService_GetSuggestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuggestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchProviderServiceServer).GetSuggestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchProviderService_GetSuggestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchProviderServiceServer).GetSuggestions(ctx, req.(*SuggestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchProviderService_GetProviderInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchProviderServiceServer).GetProviderInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchProviderService_GetProviderInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchProviderServiceServer).GetProviderInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// SearchProviderService_ServiceDesc is the grpc.ServiceDesc for SearchProviderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SearchProviderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "viewra.plugin.v1.SearchProviderService",
	HandlerType: (*SearchProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _SearchProviderService_Search_Handler,
		},
		{
			MethodName: "GetSuggestions",
			Handler:    _SearchProviderService_GetSuggestions_Handler,
		},
		{
			MethodName: "GetProviderInfo",
			Handler:    _SearchProviderService_GetProviderInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/plugin/search_provider.proto",
}
