// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: api/proto/plugin/trending.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrendingProviderService_GetTrending_FullMethodName     = "/viewra.plugin.v1.TrendingProviderService/GetTrending"
	TrendingProviderService_GetProviderInfo_FullMethodName = "/viewra.plugin.v1.TrendingProviderService/GetProviderInfo"
)

// TrendingProviderServiceClient is the client API for TrendingProviderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TrendingProviderService is implemented by plugins that provide trending data.
// Trending data is matched against the user's local library to show relevant items.
type TrendingProviderServiceClient interface {
	// GetTrending returns currently trending items from this provider.
	GetTrending(ctx context.Context, in *TrendingRequest, opts ...grpc.CallOption) (*TrendingResponse, error)
	// GetProviderInfo returns metadata about this trending source.
	GetProviderInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TrendingProviderInfo, error)
}

type trendingProviderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrendingProviderServiceClient(cc grpc.ClientConnInterface) TrendingProviderServiceClient {
	return &trendingProviderServiceClient{cc}
}

func (c *trendingProviderServiceClient) GetTrending(ctx context.Context, in *TrendingRequest, opts ...grpc.CallOption) (*TrendingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrendingResponse)
	err := c.cc.Invoke(ctx, TrendingProviderService_GetTrending_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trendingProviderServiceClient) GetProviderInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TrendingProviderInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrendingProviderInfo)
	err := c.cc.Invoke(ctx, TrendingProviderService_GetProviderInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrendingProviderServiceServer is the server API for TrendingProviderService service.
// All implementations must embed UnimplementedTrendingProviderServiceServer
// for forward compatibility.
//
// TrendingProviderService is implemented by plugins that provide trending data.
// Trending data is matched against the user's local library to show relevant items.
type TrendingProviderServiceServer interface {
	// GetTrending returns currently trending items from this provider.
	GetTrending(context.Context, *TrendingRequest) (*TrendingResponse, error)
	// GetProviderInfo returns metadata about this trending source.
	GetProviderInfo(context.Context, *Empty) (*TrendingProviderInfo, error)
	mustEmbedUnimplementedTrendingProviderServiceServer()
}

// UnimplementedTrendingProviderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrendingProviderServiceServer struct{}

func (UnimplementedTrendingProviderServiceServer) GetTrending(context.Context, *TrendingRequest) (*TrendingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrending not implemented")
}
func (UnimplementedTrendingProviderServiceServer) GetProviderInfo(context.Context, *Empty) (*TrendingProviderInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProviderInfo not implemented")
}
func (UnimplementedTrendingProviderServiceServer) mustEmbedUnimplementedTrendingProviderServiceServer() {
}
func (UnimplementedTrendingProviderServiceServer) testEmbeddedByValue() {}

// UnsafeTrendingProviderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrendingProviderServiceServer will
// result in compilation errors.
type UnsafeTrendingProviderServiceServer interface {
	mustEmbedUnimplementedTrendingProviderServiceServer()
}

func RegisterTrendingProviderServiceServer(s grpc.ServiceRegistrar, srv TrendingProviderServiceServer) {
	// If the following call pancis, it indicates UnimplementedTrendingProviderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrendingProviderService_ServiceDesc, srv)
}

func _TrendingProviderService_GetTrending_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrendingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrendingProviderServiceServer).GetTrending(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrendingProviderService_GetTrending_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrendingProviderServiceServer).GetTrending(ctx, req.(*TrendingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrendingProviderService_GetProviderInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrendingProviderServiceServer).GetProviderInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrendingProviderService_GetProviderInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrendingProviderServiceServer).GetProviderInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// TrendingProviderService_ServiceDesc is the grpc.ServiceDesc for TrendingProviderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrendingProviderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "viewra.plugin.v1.TrendingProviderService",
	HandlerType: (*TrendingProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTrending",
			Handler:    _TrendingProviderService_GetTrending_Handler,
		},
		{
			MethodName: "GetProviderInfo",
			Handler:    _TrendingProviderService_GetProviderInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/plugin/trending.proto",
}
