// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc_sqlite

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	AddMediaStudio(ctx context.Context, arg AddMediaStudioParams) error
	// Boosts priority for pending/processing jobs and returns the number of affected rows.
	// Used for interactive priority boost when user views an item.
	BoostPriority(ctx context.Context, arg BoostPriorityParams) (int64, error)
	ClaimEnrichmentJobs(ctx context.Context, arg ClaimEnrichmentJobsParams) ([]EnrichmentQueue, error)
	CleanExpiredSchedulerLocks(ctx context.Context) (int64, error)
	ClearScanStateError(ctx context.Context, arg ClearScanStateErrorParams) error
	ClearScanStateWarning(ctx context.Context, arg ClearScanStateWarningParams) error
	ClearStudiosForEntity(ctx context.Context, arg ClearStudiosForEntityParams) error
	CompleteEnrichmentJob(ctx context.Context, id int64) error
	CompleteScanJob(ctx context.Context, arg CompleteScanJobParams) error
	CompleteTranscodeAnalytics(ctx context.Context, arg CompleteTranscodeAnalyticsParams) error
	// ============================================================================
	// Pagination Support Queries
	// ============================================================================
	CountAlbumsByLibrary(ctx context.Context, libraryID int64) (int64, error)
	CountAlbumsInLibrary(ctx context.Context, libraryID int64) (int64, error)
	CountArtistsInLibrary(ctx context.Context, libraryID int64) (int64, error)
	CountCreditsForEntity(ctx context.Context, arg CountCreditsForEntityParams) (int64, error)
	CountEnrichmentStatusByStage(ctx context.Context, stage string) (CountEnrichmentStatusByStageRow, error)
	CountFailedScanCheckpoints(ctx context.Context, scanJobID int64) (int64, error)
	CountImagesByEntity(ctx context.Context, arg CountImagesByEntityParams) (int64, error)
	CountImagesByMediaID(ctx context.Context, mediaID sql.NullInt64) (int64, error)
	CountLibraries(ctx context.Context) (int64, error)
	CountLibrariesByType(ctx context.Context, type_ string) (int64, error)
	// Count total failed enrichment jobs for a library.
	CountLibraryEnrichmentFailures(ctx context.Context, libraryID sql.NullInt64) (int64, error)
	CountLibraryErrors(ctx context.Context, libraryID int64) (int64, error)
	CountLibraryIssues(ctx context.Context, libraryID int64) (CountLibraryIssuesRow, error)
	CountLibraryScanState(ctx context.Context, libraryID int64) (int64, error)
	CountLibraryWarnings(ctx context.Context, libraryID int64) (int64, error)
	CountMediaByType(ctx context.Context, arg CountMediaByTypeParams) (int64, error)
	CountMediaInLibrary(ctx context.Context, libraryID int64) (int64, error)
	CountMoviesByLibrary(ctx context.Context, libraryID int64) (int64, error)
	CountMusicTracksByLibrary(ctx context.Context, libraryID int64) (int64, error)
	// Count images for entities that no longer exist (for reporting before cleanup).
	CountOrphanedEntityImages(ctx context.Context) (int64, error)
	CountPlaybackSessionsByMediaID(ctx context.Context, mediaID int64) (int64, error)
	CountPluginAPIKeys(ctx context.Context, pluginID string) (int64, error)
	CountPluginUserMetadata(ctx context.Context, arg CountPluginUserMetadataParams) (int64, error)
	CountScanJobsByLibrary(ctx context.Context, libraryID int64) (int64, error)
	CountSchedulerExecutionsByTask(ctx context.Context, taskID string) (int64, error)
	CountSearchArtistsByName(ctx context.Context, arg CountSearchArtistsByNameParams) (int64, error)
	CountSearchMoviesByTitle(ctx context.Context, arg CountSearchMoviesByTitleParams) (int64, error)
	CountSearchTVShowsByTitle(ctx context.Context, arg CountSearchTVShowsByTitleParams) (int64, error)
	CountSessionsByUserID(ctx context.Context, userID int64) (int64, error)
	// ============================================================================
	// Pagination Support Queries
	// ============================================================================
	CountTVShowsByLibrary(ctx context.Context, libraryID int64) (int64, error)
	CountTranscodeJobsByStatus(ctx context.Context, status string) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAlbum(ctx context.Context, arg CreateAlbumParams) (MusicAlbum, error)
	CreateArtist(ctx context.Context, arg CreateArtistParams) (MusicArtist, error)
	CreateCredit(ctx context.Context, arg CreateCreditParams) (Credit, error)
	CreateImage(ctx context.Context, arg CreateImageParams) (MediaImage, error)
	// Library queries for SQLite
	CreateLibrary(ctx context.Context, arg CreateLibraryParams) (Library, error)
	CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error)
	CreateMovie(ctx context.Context, arg CreateMovieParams) error
	CreateMusicTrack(ctx context.Context, arg CreateMusicTrackParams) error
	CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error)
	CreatePipelineStage(ctx context.Context, arg CreatePipelineStageParams) (EnrichmentPipeline, error)
	CreatePlugin(ctx context.Context, arg CreatePluginParams) error
	CreatePluginAPIKey(ctx context.Context, arg CreatePluginAPIKeyParams) error
	CreateQualitySwitchEvent(ctx context.Context, arg CreateQualitySwitchEventParams) (QualitySwitchEvent, error)
	CreateScanCheckpoint(ctx context.Context, arg CreateScanCheckpointParams) (ScanCheckpoint, error)
	CreateScanCheckpointBatch(ctx context.Context, arg CreateScanCheckpointBatchParams) error
	CreateScanJob(ctx context.Context, arg CreateScanJobParams) (ScanJob, error)
	// Scheduler Executions Queries
	CreateSchedulerExecution(ctx context.Context, arg CreateSchedulerExecutionParams) error
	// Session queries for SQLite
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateStudio(ctx context.Context, arg CreateStudioParams) (Studio, error)
	// ============================================================================
	// TV Episodes
	// ============================================================================
	CreateTVEpisode(ctx context.Context, arg CreateTVEpisodeParams) error
	// ============================================================================
	// TV Seasons
	// ============================================================================
	CreateTVSeason(ctx context.Context, arg CreateTVSeasonParams) (TvSeason, error)
	// ============================================================================
	// TV Shows
	// ============================================================================
	CreateTVShow(ctx context.Context, arg CreateTVShowParams) (TvShow, error)
	CreateTranscodeAnalytics(ctx context.Context, arg CreateTranscodeAnalyticsParams) error
	CreateTranscodeJob(ctx context.Context, arg CreateTranscodeJobParams) (TranscodeJob, error)
	// User queries for SQLite
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWatchProgress(ctx context.Context, arg CreateWatchProgressParams) (WatchProgress, error)
	DeleteAlbum(ctx context.Context, id int64) error
	DeleteAllUserSettings(ctx context.Context, userID string) error
	DeleteArtist(ctx context.Context, id int64) error
	DeleteAudioTracksByMediaID(ctx context.Context, mediaID int64) error
	DeleteCredit(ctx context.Context, id int64) error
	DeleteCreditsForEntity(ctx context.Context, arg DeleteCreditsForEntityParams) error
	DeleteCreditsForEntityByType(ctx context.Context, arg DeleteCreditsForEntityByTypeParams) error
	DeleteEnrichmentJobsByMedia(ctx context.Context, arg DeleteEnrichmentJobsByMediaParams) error
	DeleteEnrichmentStatusByMedia(ctx context.Context, arg DeleteEnrichmentStatusByMediaParams) error
	DeleteExpiredPluginAPIKeys(ctx context.Context) error
	DeleteExpiredSessions(ctx context.Context, expiresAt string) (int64, error)
	DeleteExternalID(ctx context.Context, arg DeleteExternalIDParams) error
	// Deletes by media_type and entity_id
	DeleteExternalIDsByMedia(ctx context.Context, arg DeleteExternalIDsByMediaParams) error
	// Legacy: deletes by media table ID
	DeleteExternalIDsByMediaID(ctx context.Context, mediaID sql.NullInt64) error
	DeleteExternalSubtitlesByMediaID(ctx context.Context, mediaID int64) error
	DeleteImage(ctx context.Context, id int64) error
	DeleteImagesByEntity(ctx context.Context, arg DeleteImagesByEntityParams) error
	DeleteImagesByHash(ctx context.Context, fileHash sql.NullString) error
	DeleteImagesByMediaID(ctx context.Context, mediaID sql.NullInt64) error
	DeleteKeywordsByEntity(ctx context.Context, arg DeleteKeywordsByEntityParams) error
	DeleteLibrary(ctx context.Context, id int64) error
	DeleteMedia(ctx context.Context, id int64) error
	DeleteMetadataSource(ctx context.Context, arg DeleteMetadataSourceParams) error
	DeleteMetadataSourcesByMedia(ctx context.Context, mediaID int64) error
	DeleteMetadataSourcesByPlugin(ctx context.Context, pluginID string) error
	DeleteMovie(ctx context.Context, mediaID int64) error
	DeleteMusicTrack(ctx context.Context, mediaID int64) error
	DeleteOldPlaybackSessions(ctx context.Context, startTime int64) error
	DeleteOldQualitySwitchEvents(ctx context.Context, timestamp int64) error
	DeleteOldScanJobs(ctx context.Context, arg DeleteOldScanJobsParams) error
	DeleteOldSchedulerExecutions(ctx context.Context, createdAt time.Time) (int64, error)
	// Delete images for entities that no longer exist (tv_show, tv_season, music_album, music_artist).
	// This handles the polymorphic entity_id references that don't have foreign key constraints.
	DeleteOrphanedEntityImages(ctx context.Context) (sql.Result, error)
	DeletePerson(ctx context.Context, id int64) error
	DeletePipelineStage(ctx context.Context, id int64) error
	DeletePipelineStagesByMediaType(ctx context.Context, mediaType string) error
	DeletePlaybackPreferences(ctx context.Context, arg DeletePlaybackPreferencesParams) error
	DeletePlaybackPreferencesByMediaID(ctx context.Context, mediaID int64) error
	DeletePlaybackPreferencesByUserID(ctx context.Context, userID int64) error
	DeletePlugin(ctx context.Context, id string) error
	DeletePluginAPIKey(ctx context.Context, id string) error
	DeletePluginAPIKeysByPlugin(ctx context.Context, pluginID string) error
	DeletePluginUserMetadata(ctx context.Context, arg DeletePluginUserMetadataParams) error
	DeletePluginUserMetadataByPlugin(ctx context.Context, pluginID string) error
	DeletePluginUserMetadataByUser(ctx context.Context, userID int64) error
	DeleteScanCheckpointsByJobID(ctx context.Context, scanJobID int64) error
	DeleteScanJob(ctx context.Context, id int64) error
	DeleteScanStateByLibrary(ctx context.Context, libraryID int64) error
	DeleteScanStateByPath(ctx context.Context, arg DeleteScanStateByPathParams) error
	DeleteScheduledTask(ctx context.Context, id string) error
	DeleteScheduledTasksBySourceID(ctx context.Context, sourceID sql.NullString) error
	DeleteSession(ctx context.Context, id int64) error
	DeleteSessionsByUserID(ctx context.Context, userID int64) error
	DeleteStudio(ctx context.Context, id int64) error
	DeleteSubtitleTracksByMediaID(ctx context.Context, mediaID int64) error
	DeleteSystemSetting(ctx context.Context, key string) error
	DeleteTVEpisode(ctx context.Context, mediaID int64) error
	DeleteTVSeason(ctx context.Context, id int64) error
	DeleteTVShow(ctx context.Context, id int64) error
	DeleteTranscodeJob(ctx context.Context, id int64) error
	DeleteTranscodeJobsByMediaID(ctx context.Context, mediaID int64) error
	DeleteUser(ctx context.Context, id int64) error
	DeleteUserSetting(ctx context.Context, arg DeleteUserSettingParams) error
	DeleteWatchProgress(ctx context.Context, id int64) error
	DeleteWatchProgressByMediaID(ctx context.Context, mediaID int64) error
	DisablePipelineStage(ctx context.Context, id int64) error
	DisablePlugin(ctx context.Context, id string) error
	DisableScheduledTask(ctx context.Context, id string) error
	EnablePipelineStage(ctx context.Context, id int64) error
	EnablePlugin(ctx context.Context, id string) error
	EnableScheduledTask(ctx context.Context, id string) error
	// Enqueue a job for enrichment processing. On conflict:
	// - If status is completed/skipped/failed: reset to pending for re-processing
	// - If status is pending/processing: keep existing state (idempotent)
	// Always returns the row (new or existing) to avoid "no rows" errors.
	EnqueueEnrichmentJob(ctx context.Context, arg EnqueueEnrichmentJobParams) (EnrichmentQueue, error)
	ExistsAnyUser(ctx context.Context) (int64, error)
	FailEnrichmentJob(ctx context.Context, arg FailEnrichmentJobParams) error
	FailTranscodeAnalytics(ctx context.Context, arg FailTranscodeAnalyticsParams) error
	FindAlbumByTitle(ctx context.Context, arg FindAlbumByTitleParams) (MusicAlbum, error)
	FindArtistByName(ctx context.Context, arg FindArtistByNameParams) (MusicArtist, error)
	GetAlbumByID(ctx context.Context, id int64) (MusicAlbum, error)
	GetAlbumByMusicBrainzID(ctx context.Context, musicbrainzAlbumID sql.NullString) (MusicAlbum, error)
	GetAllFileHashes(ctx context.Context) ([]sql.NullString, error)
	GetAllPipelineStages(ctx context.Context, mediaType string) ([]EnrichmentPipeline, error)
	GetAllSystemSettings(ctx context.Context) ([]SystemSetting, error)
	GetAllUserSettings(ctx context.Context, userID string) ([]UserSetting, error)
	GetArtistByID(ctx context.Context, id int64) (MusicArtist, error)
	GetArtistByMusicBrainzID(ctx context.Context, musicbrainzArtistID sql.NullString) (MusicArtist, error)
	// ============================================================================
	// Aggregation Queries for API (optimized)
	// ============================================================================
	GetArtistsWithCountsByLibrary(ctx context.Context, libraryID int64) ([]GetArtistsWithCountsByLibraryRow, error)
	GetArtistsWithCountsByLibraryPaginated(ctx context.Context, arg GetArtistsWithCountsByLibraryPaginatedParams) ([]GetArtistsWithCountsByLibraryPaginatedRow, error)
	GetArtistsWithCountsByLibraryPaginatedDesc(ctx context.Context, arg GetArtistsWithCountsByLibraryPaginatedDescParams) ([]GetArtistsWithCountsByLibraryPaginatedDescRow, error)
	GetAudioTracksByMediaID(ctx context.Context, mediaID int64) ([]MediaAudioTrack, error)
	GetBatchWatchProgressByMediaIDs(ctx context.Context, arg GetBatchWatchProgressByMediaIDsParams) ([]WatchProgress, error)
	GetCastForEntity(ctx context.Context, arg GetCastForEntityParams) ([]GetCastForEntityRow, error)
	GetCorrelatedAnalytics(ctx context.Context, arg GetCorrelatedAnalyticsParams) ([]GetCorrelatedAnalyticsRow, error)
	GetCorrelatedAnalyticsAll(ctx context.Context, arg GetCorrelatedAnalyticsAllParams) ([]GetCorrelatedAnalyticsAllRow, error)
	GetCreatorsForEntity(ctx context.Context, arg GetCreatorsForEntityParams) ([]GetCreatorsForEntityRow, error)
	GetCreditsForEntity(ctx context.Context, arg GetCreditsForEntityParams) ([]GetCreditsForEntityRow, error)
	GetCreditsForEntityByType(ctx context.Context, arg GetCreditsForEntityByTypeParams) ([]GetCreditsForEntityByTypeRow, error)
	GetCreditsForPerson(ctx context.Context, personID int64) ([]GetCreditsForPersonRow, error)
	// Get the currently processing enrichment item with its title for a library.
	// Joins with media/tv_shows/tv_seasons/music tables to get the title.
	// Returns the first processing item (by locked_at) for the library.
	GetCurrentEnrichmentItem(ctx context.Context, libraryID sql.NullInt64) (GetCurrentEnrichmentItemRow, error)
	GetDirectorsForEntity(ctx context.Context, arg GetDirectorsForEntityParams) ([]GetDirectorsForEntityRow, error)
	GetEmbeddedSubtitlesByMediaID(ctx context.Context, mediaID int64) ([]MediaSubtitleTrack, error)
	GetEnabledPipelineStages(ctx context.Context, mediaType string) ([]EnrichmentPipeline, error)
	GetEnrichmentJob(ctx context.Context, id int64) (EnrichmentQueue, error)
	GetEnrichmentJobByMediaAndStage(ctx context.Context, arg GetEnrichmentJobByMediaAndStageParams) (EnrichmentQueue, error)
	GetEnrichmentQueueStats(ctx context.Context, stage string) (GetEnrichmentQueueStatsRow, error)
	GetEnrichmentQueueStatsByMedia(ctx context.Context, mediaID int64) ([]GetEnrichmentQueueStatsByMediaRow, error)
	GetEnrichmentStatus(ctx context.Context, arg GetEnrichmentStatusParams) (EnrichmentStatus, error)
	GetEnrichmentStatusByMedia(ctx context.Context, arg GetEnrichmentStatusByMediaParams) ([]EnrichmentStatus, error)
	GetEnrichmentStatusByStage(ctx context.Context, arg GetEnrichmentStatusByStageParams) ([]EnrichmentStatus, error)
	// Returns full entity info for external ID lookup
	GetEntityByExternalID(ctx context.Context, arg GetEntityByExternalIDParams) (GetEntityByExternalIDRow, error)
	// Returns episode details with the parent show's title for plugin indexing
	GetEpisodeWithShowTitle(ctx context.Context, mediaID int64) (GetEpisodeWithShowTitleRow, error)
	GetExternalID(ctx context.Context, arg GetExternalIDParams) (MediaExternalID, error)
	// Gets external IDs by media_type and entity_id (polymorphic)
	GetExternalIDsByMedia(ctx context.Context, arg GetExternalIDsByMediaParams) ([]MediaExternalID, error)
	// Legacy query: gets external IDs by media table ID (for backward compatibility)
	GetExternalIDsByMediaID(ctx context.Context, mediaID sql.NullInt64) ([]MediaExternalID, error)
	// Batch fetch: gets external IDs for multiple media IDs
	// Note: sqlc doesn't support array params in SQLite, so this is implemented
	// in the repository using a dynamic query or multiple calls
	GetExternalIDsByMediaIDBatch(ctx context.Context, mediaIds []sql.NullInt64) ([]MediaExternalID, error)
	GetExternalSubtitlesByMediaID(ctx context.Context, mediaID int64) ([]MediaSubtitleTrack, error)
	GetFilePathCache(ctx context.Context, libraryID int64) ([]GetFilePathCacheRow, error)
	GetFirstPipelineStage(ctx context.Context, mediaType string) (EnrichmentPipeline, error)
	GetImageByExternalURL(ctx context.Context, arg GetImageByExternalURLParams) (MediaImage, error)
	GetImageByFilePath(ctx context.Context, filePath sql.NullString) (MediaImage, error)
	GetImageByID(ctx context.Context, id int64) (MediaImage, error)
	GetImageByTypeAndEntity(ctx context.Context, arg GetImageByTypeAndEntityParams) (MediaImage, error)
	GetImageByTypeAndMediaID(ctx context.Context, arg GetImageByTypeAndMediaIDParams) (MediaImage, error)
	GetImagesByHash(ctx context.Context, fileHash sql.NullString) ([]MediaImage, error)
	GetInterruptedSchedulerExecutions(ctx context.Context) ([]SchedulerExecution, error)
	GetKeywordsByEntity(ctx context.Context, arg GetKeywordsByEntityParams) ([]GetKeywordsByEntityRow, error)
	GetLatestScanJobByLibrary(ctx context.Context, libraryID int64) (ScanJob, error)
	GetLatestSchedulerExecution(ctx context.Context, taskID string) (SchedulerExecution, error)
	GetLibraryByID(ctx context.Context, id int64) (Library, error)
	GetLibraryByPath(ctx context.Context, path string) (Library, error)
	// Get failed enrichment jobs for a library with titles for display.
	// Joins with media/tv_shows/tv_seasons/music tables to get the title.
	GetLibraryEnrichmentFailures(ctx context.Context, arg GetLibraryEnrichmentFailuresParams) ([]GetLibraryEnrichmentFailuresRow, error)
	// Get overall enrichment progress for a library.
	// Returns: items that completed all stages / total unique items that entered enrichment.
	// "Fully enriched" means an item has completed the last stage in the pipeline.
	GetLibraryEnrichmentOverallProgress(ctx context.Context, arg GetLibraryEnrichmentOverallProgressParams) (GetLibraryEnrichmentOverallProgressRow, error)
	GetLibraryEnrichmentProgress(ctx context.Context, arg GetLibraryEnrichmentProgressParams) ([]GetLibraryEnrichmentProgressRow, error)
	GetLibraryErrors(ctx context.Context, libraryID int64) ([]ScanState, error)
	GetLibraryIssues(ctx context.Context, libraryID int64) ([]ScanState, error)
	GetLibraryScanState(ctx context.Context, libraryID int64) ([]ScanState, error)
	GetLibraryWarnings(ctx context.Context, libraryID int64) ([]ScanState, error)
	GetLocationKeywordsByEntity(ctx context.Context, arg GetLocationKeywordsByEntityParams) ([]GetLocationKeywordsByEntityRow, error)
	// Returns entity_id for the given provider/external_id combination
	GetMediaByExternalID(ctx context.Context, arg GetMediaByExternalIDParams) (int64, error)
	GetMediaByFilePath(ctx context.Context, arg GetMediaByFilePathParams) (Medium, error)
	GetMediaByID(ctx context.Context, id int64) (Medium, error)
	GetMetadataSource(ctx context.Context, arg GetMetadataSourceParams) (MediaMetadataSource, error)
	GetMetadataSourcesByField(ctx context.Context, arg GetMetadataSourcesByFieldParams) ([]MediaMetadataSource, error)
	GetMetadataSourcesByMedia(ctx context.Context, mediaID int64) ([]MediaMetadataSource, error)
	GetMovieByMediaID(ctx context.Context, mediaID int64) (GetMovieByMediaIDRow, error)
	GetMusicTrackByMediaID(ctx context.Context, mediaID int64) (GetMusicTrackByMediaIDRow, error)
	GetNextPipelinePosition(ctx context.Context, mediaType string) (int64, error)
	GetNextPipelineStage(ctx context.Context, arg GetNextPipelineStageParams) (EnrichmentPipeline, error)
	// Find enrichment statuses where a stage completed but the next stage was never enqueued.
	// This happens when the server crashes between marking a stage complete and enqueuing the next.
	// Returns the media items that need their next stage enqueued.
	GetOrphanedPipelineStates(ctx context.Context) ([]GetOrphanedPipelineStatesRow, error)
	GetOverallPlaybackSummary(ctx context.Context) (GetOverallPlaybackSummaryRow, error)
	GetOverallTranscodeSummary(ctx context.Context) (GetOverallTranscodeSummaryRow, error)
	GetPendingScanCheckpoints(ctx context.Context, arg GetPendingScanCheckpointsParams) ([]ScanCheckpoint, error)
	// Looks up a person by external ID (e.g., TMDb person ID)
	GetPersonByExternalID(ctx context.Context, arg GetPersonByExternalIDParams) (int64, error)
	GetPersonByID(ctx context.Context, id int64) (Person, error)
	GetPersonByIMDbID(ctx context.Context, imdbID sql.NullString) (Person, error)
	GetPersonByName(ctx context.Context, name string) (Person, error)
	GetPersonByTMDbID(ctx context.Context, tmdbID sql.NullInt64) (Person, error)
	// Gets all external IDs for a person
	GetPersonExternalIDs(ctx context.Context, entityID int64) ([]GetPersonExternalIDsRow, error)
	GetPipelineStage(ctx context.Context, id int64) (EnrichmentPipeline, error)
	GetPipelineStageByName(ctx context.Context, arg GetPipelineStageByNameParams) (EnrichmentPipeline, error)
	GetPipelineStageByPlugin(ctx context.Context, arg GetPipelineStageByPluginParams) (EnrichmentPipeline, error)
	GetPlaybackPreferences(ctx context.Context, arg GetPlaybackPreferencesParams) (PlaybackPreference, error)
	GetPlaybackSessionByID(ctx context.Context, sessionID string) (PlaybackSession, error)
	GetPlaybackSummaryByMediaID(ctx context.Context, mediaID int64) (GetPlaybackSummaryByMediaIDRow, error)
	GetPlugin(ctx context.Context, id string) (GetPluginRow, error)
	GetPluginAPIKey(ctx context.Context, id string) (PluginApiKey, error)
	GetPluginAPIKeyByHash(ctx context.Context, keyHash string) (PluginApiKey, error)
	GetPluginSettings(ctx context.Context, id string) (sql.NullString, error)
	GetPluginUserMetadata(ctx context.Context, arg GetPluginUserMetadataParams) (GetPluginUserMetadataRow, error)
	GetQualitySwitchStats(ctx context.Context, mediaID int64) (GetQualitySwitchStatsRow, error)
	GetRetryableEnrichmentJobs(ctx context.Context, arg GetRetryableEnrichmentJobsParams) ([]EnrichmentQueue, error)
	GetRunningSchedulerExecutions(ctx context.Context) ([]SchedulerExecution, error)
	GetScanCheckpointByID(ctx context.Context, id int64) (ScanCheckpoint, error)
	GetScanCheckpointByPath(ctx context.Context, arg GetScanCheckpointByPathParams) (ScanCheckpoint, error)
	GetScanCheckpointErrorsByCategory(ctx context.Context, scanJobID int64) ([]GetScanCheckpointErrorsByCategoryRow, error)
	GetScanCheckpointProgress(ctx context.Context, scanJobID int64) (GetScanCheckpointProgressRow, error)
	GetScanCheckpointStats(ctx context.Context, scanJobID int64) (GetScanCheckpointStatsRow, error)
	GetScanJob(ctx context.Context, id int64) (ScanJob, error)
	GetScanJobStats(ctx context.Context, libraryID int64) (GetScanJobStatsRow, error)
	GetScanStateByPath(ctx context.Context, arg GetScanStateByPathParams) (ScanState, error)
	GetScanStateModifiedSince(ctx context.Context, arg GetScanStateModifiedSinceParams) ([]ScanState, error)
	// Scheduled Tasks Queries
	GetScheduledTask(ctx context.Context, id string) (ScheduledTask, error)
	GetSchedulerExecution(ctx context.Context, id string) (SchedulerExecution, error)
	GetSchedulerExecutionStats(ctx context.Context, taskID string) (GetSchedulerExecutionStatsRow, error)
	GetSchedulerLock(ctx context.Context, lockKey string) (SchedulerLock, error)
	GetSessionByID(ctx context.Context, id int64) (Session, error)
	GetSessionByPublicID(ctx context.Context, publicID string) (Session, error)
	GetSessionByTokenHash(ctx context.Context, refreshTokenHash string) (Session, error)
	GetSessionsByUserID(ctx context.Context, userID int64) ([]Session, error)
	// Looks up a studio by external ID (e.g., TMDb company ID)
	GetStudioByExternalID(ctx context.Context, arg GetStudioByExternalIDParams) (int64, error)
	GetStudioByID(ctx context.Context, id int64) (Studio, error)
	GetStudioByName(ctx context.Context, name string) (Studio, error)
	GetStudioByTMDbID(ctx context.Context, tmdbID sql.NullInt64) (Studio, error)
	// Gets all external IDs for a studio
	GetStudioExternalIDs(ctx context.Context, entityID int64) ([]GetStudioExternalIDsRow, error)
	GetStudiosForEntity(ctx context.Context, arg GetStudiosForEntityParams) ([]Studio, error)
	GetSubtitleTracksByMediaID(ctx context.Context, mediaID int64) ([]MediaSubtitleTrack, error)
	// Settings queries for SQLite
	GetSystemSetting(ctx context.Context, key string) (SystemSetting, error)
	GetSystemSettingsByCategory(ctx context.Context, category string) ([]SystemSetting, error)
	GetTVEpisodeByMediaID(ctx context.Context, mediaID int64) (GetTVEpisodeByMediaIDRow, error)
	GetTVEpisodeByShowSeasonEpisode(ctx context.Context, arg GetTVEpisodeByShowSeasonEpisodeParams) (GetTVEpisodeByShowSeasonEpisodeRow, error)
	GetTVSeasonByID(ctx context.Context, id int64) (TvSeason, error)
	GetTVSeasonByShowAndNumber(ctx context.Context, arg GetTVSeasonByShowAndNumberParams) (TvSeason, error)
	// Find a TV show by its directory path. Used to prevent duplicate shows
	// when different episodes parse to different titles but share the same directory.
	GetTVShowByDirectory(ctx context.Context, arg GetTVShowByDirectoryParams) (TvShow, error)
	GetTVShowByID(ctx context.Context, id int64) (TvShow, error)
	GetTVShowByTitle(ctx context.Context, arg GetTVShowByTitleParams) (TvShow, error)
	// ============================================================================
	// Aggregation Queries for API
	// ============================================================================
	GetTVShowsWithCountsByLibrary(ctx context.Context, libraryID int64) ([]GetTVShowsWithCountsByLibraryRow, error)
	GetTVShowsWithCountsByLibraryPaginated(ctx context.Context, arg GetTVShowsWithCountsByLibraryPaginatedParams) ([]GetTVShowsWithCountsByLibraryPaginatedRow, error)
	GetTVShowsWithCountsByLibraryPaginatedDesc(ctx context.Context, arg GetTVShowsWithCountsByLibraryPaginatedDescParams) ([]GetTVShowsWithCountsByLibraryPaginatedDescRow, error)
	GetThemeKeywordsByEntity(ctx context.Context, arg GetThemeKeywordsByEntityParams) ([]GetThemeKeywordsByEntityRow, error)
	GetTotalTranscodeSize(ctx context.Context) (interface{}, error)
	GetTranscodeAnalyticsBySessionID(ctx context.Context, sessionID string) (TranscodeAnalytic, error)
	GetTranscodeJobByID(ctx context.Context, id int64) (TranscodeJob, error)
	GetTranscodeJobByMediaIDAndQuality(ctx context.Context, arg GetTranscodeJobByMediaIDAndQualityParams) (TranscodeJob, error)
	GetTranscodeSummaryByMediaID(ctx context.Context, mediaID int64) (GetTranscodeSummaryByMediaIDRow, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByPublicID(ctx context.Context, publicID string) (User, error)
	GetUserByUsername(ctx context.Context, lower string) (User, error)
	// Location Preferences (stored in users table)
	GetUserLocation(ctx context.Context, id int64) (GetUserLocationRow, error)
	GetUserSetting(ctx context.Context, arg GetUserSettingParams) (UserSetting, error)
	GetWatchProgressByID(ctx context.Context, id int64) (WatchProgress, error)
	GetWatchProgressByMediaID(ctx context.Context, mediaID int64) (WatchProgress, error)
	GetWatchProgressByMediaIDAndUserID(ctx context.Context, arg GetWatchProgressByMediaIDAndUserIDParams) (WatchProgress, error)
	GetWritersForEntity(ctx context.Context, arg GetWritersForEntityParams) ([]GetWritersForEntityRow, error)
	IncrementPluginRestartCount(ctx context.Context, id string) error
	IncrementSeasonEpisodeCount(ctx context.Context, id int64) error
	// Audio and subtitle track queries for multi-language support
	InsertAudioTrack(ctx context.Context, arg InsertAudioTrackParams) (InsertAudioTrackRow, error)
	InsertKeyword(ctx context.Context, arg InsertKeywordParams) error
	InsertSubtitleTrack(ctx context.Context, arg InsertSubtitleTrackParams) (InsertSubtitleTrackRow, error)
	LibraryExistsByID(ctx context.Context, id int64) (int64, error)
	LibraryExistsByPath(ctx context.Context, path string) (int64, error)
	ListAlbumsByArtist(ctx context.Context, arg ListAlbumsByArtistParams) ([]MusicAlbum, error)
	ListAlbumsByLibrary(ctx context.Context, libraryID int64) ([]MusicAlbum, error)
	ListAlbumsByLibraryGrouped(ctx context.Context, libraryID int64) ([]ListAlbumsByLibraryGroupedRow, error)
	ListAlbumsByLibraryPaginated(ctx context.Context, arg ListAlbumsByLibraryPaginatedParams) ([]ListAlbumsByLibraryPaginatedRow, error)
	ListAlbumsByLibraryPaginatedDesc(ctx context.Context, arg ListAlbumsByLibraryPaginatedDescParams) ([]ListAlbumsByLibraryPaginatedDescRow, error)
	ListAllMedia(ctx context.Context) ([]Medium, error)
	ListAllTranscodeJobs(ctx context.Context) ([]TranscodeJob, error)
	ListArtistIDsByLibraryPaginated(ctx context.Context, arg ListArtistIDsByLibraryPaginatedParams) ([]int64, error)
	ListArtistIDsByLibraryPaginatedDesc(ctx context.Context, arg ListArtistIDsByLibraryPaginatedDescParams) ([]int64, error)
	ListArtistsByLibrary(ctx context.Context, libraryID int64) ([]MusicArtist, error)
	ListEnabledPlugins(ctx context.Context) ([]ListEnabledPluginsRow, error)
	ListEnabledScheduledTasks(ctx context.Context) ([]ScheduledTask, error)
	ListFailedScanCheckpoints(ctx context.Context, arg ListFailedScanCheckpointsParams) ([]ScanCheckpoint, error)
	ListImagesByEntity(ctx context.Context, arg ListImagesByEntityParams) ([]MediaImage, error)
	ListImagesByMediaID(ctx context.Context, mediaID sql.NullInt64) ([]MediaImage, error)
	ListImagesBySource(ctx context.Context, sourceType string) ([]MediaImage, error)
	ListInProgressByUserID(ctx context.Context, arg ListInProgressByUserIDParams) ([]WatchProgress, error)
	ListLibraries(ctx context.Context) ([]Library, error)
	ListLibrariesByType(ctx context.Context, type_ string) ([]Library, error)
	ListMediaByLibrary(ctx context.Context, libraryID int64) ([]Medium, error)
	ListMediaByType(ctx context.Context, arg ListMediaByTypeParams) ([]Medium, error)
	ListMonitoredLibraries(ctx context.Context) ([]Library, error)
	ListMovieIDsByLibraryPaginated(ctx context.Context, arg ListMovieIDsByLibraryPaginatedParams) ([]int64, error)
	ListMovieIDsByLibraryPaginatedDesc(ctx context.Context, arg ListMovieIDsByLibraryPaginatedDescParams) ([]int64, error)
	ListMoviesByGenre(ctx context.Context, arg ListMoviesByGenreParams) ([]ListMoviesByGenreRow, error)
	ListMoviesByLibrary(ctx context.Context, libraryID int64) ([]ListMoviesByLibraryRow, error)
	ListMoviesByLibraryPaginated(ctx context.Context, arg ListMoviesByLibraryPaginatedParams) ([]ListMoviesByLibraryPaginatedRow, error)
	ListMoviesByLibraryPaginatedDesc(ctx context.Context, arg ListMoviesByLibraryPaginatedDescParams) ([]ListMoviesByLibraryPaginatedDescRow, error)
	ListMoviesByYear(ctx context.Context, arg ListMoviesByYearParams) ([]ListMoviesByYearRow, error)
	ListMusicTracksByAlbum(ctx context.Context, arg ListMusicTracksByAlbumParams) ([]ListMusicTracksByAlbumRow, error)
	ListMusicTracksByAlbumArtist(ctx context.Context, arg ListMusicTracksByAlbumArtistParams) ([]ListMusicTracksByAlbumArtistRow, error)
	ListMusicTracksByAlbumID(ctx context.Context, albumID sql.NullInt64) ([]ListMusicTracksByAlbumIDRow, error)
	ListMusicTracksByArtist(ctx context.Context, arg ListMusicTracksByArtistParams) ([]ListMusicTracksByArtistRow, error)
	ListMusicTracksByLibrary(ctx context.Context, libraryID int64) ([]ListMusicTracksByLibraryRow, error)
	ListMusicTracksByLibraryPaginated(ctx context.Context, arg ListMusicTracksByLibraryPaginatedParams) ([]ListMusicTracksByLibraryPaginatedRow, error)
	ListMusicTracksByLibraryPaginatedDesc(ctx context.Context, arg ListMusicTracksByLibraryPaginatedDescParams) ([]ListMusicTracksByLibraryPaginatedDescRow, error)
	// This query returns all images for validation in application code
	// The application will check if files actually exist
	ListOrphanImages(ctx context.Context) ([]MediaImage, error)
	ListPeople(ctx context.Context, arg ListPeopleParams) ([]Person, error)
	ListPlaybackSessionsByMediaID(ctx context.Context, arg ListPlaybackSessionsByMediaIDParams) ([]PlaybackSession, error)
	ListPluginAPIKeys(ctx context.Context, pluginID string) ([]PluginApiKey, error)
	ListPluginUserMetadataKeys(ctx context.Context, arg ListPluginUserMetadataKeysParams) ([]string, error)
	ListPlugins(ctx context.Context) ([]ListPluginsRow, error)
	ListPluginsByCategory(ctx context.Context, dollar_1 sql.NullString) ([]ListPluginsByCategoryRow, error)
	ListProcessingTranscodeJobs(ctx context.Context) ([]TranscodeJob, error)
	ListQualitySwitchEventsBySessionID(ctx context.Context, sessionID string) ([]QualitySwitchEvent, error)
	ListQueuedTranscodeJobs(ctx context.Context, limit int64) ([]TranscodeJob, error)
	ListRunningScanJobs(ctx context.Context) ([]ScanJob, error)
	ListScanJobsByLibrary(ctx context.Context, arg ListScanJobsByLibraryParams) ([]ScanJob, error)
	ListScheduledTasks(ctx context.Context) ([]ScheduledTask, error)
	ListScheduledTasksBySource(ctx context.Context, source string) ([]ScheduledTask, error)
	ListScheduledTasksBySourceID(ctx context.Context, sourceID sql.NullString) ([]ScheduledTask, error)
	ListSchedulerExecutions(ctx context.Context, arg ListSchedulerExecutionsParams) ([]SchedulerExecution, error)
	ListSchedulerExecutionsByTask(ctx context.Context, arg ListSchedulerExecutionsByTaskParams) ([]SchedulerExecution, error)
	ListStudios(ctx context.Context) ([]Studio, error)
	ListTVEpisodesByLibrary(ctx context.Context, libraryID int64) ([]ListTVEpisodesByLibraryRow, error)
	ListTVEpisodesBySeason(ctx context.Context, seasonID int64) ([]ListTVEpisodesBySeasonRow, error)
	ListTVEpisodesByShow(ctx context.Context, showID int64) ([]ListTVEpisodesByShowRow, error)
	ListTVSeasonsByShow(ctx context.Context, showID int64) ([]TvSeason, error)
	ListTVShowIDsByLibraryPaginated(ctx context.Context, arg ListTVShowIDsByLibraryPaginatedParams) ([]int64, error)
	ListTVShowIDsByLibraryPaginatedDesc(ctx context.Context, arg ListTVShowIDsByLibraryPaginatedDescParams) ([]int64, error)
	ListTVShowsByLibrary(ctx context.Context, libraryID int64) ([]TvShow, error)
	ListTVShowsByLibraryPaginated(ctx context.Context, arg ListTVShowsByLibraryPaginatedParams) ([]TvShow, error)
	ListTVShowsByLibraryPaginatedDesc(ctx context.Context, arg ListTVShowsByLibraryPaginatedDescParams) ([]TvShow, error)
	ListTranscodeAnalyticsByMediaID(ctx context.Context, arg ListTranscodeAnalyticsByMediaIDParams) ([]TranscodeAnalytic, error)
	ListTranscodeJobsByLRU(ctx context.Context, limit int64) ([]TranscodeJob, error)
	ListTranscodeJobsByMediaID(ctx context.Context, mediaID int64) ([]TranscodeJob, error)
	ListTranscodeJobsByStatus(ctx context.Context, status string) ([]TranscodeJob, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListWatchProgressByUserID(ctx context.Context, arg ListWatchProgressByUserIDParams) ([]WatchProgress, error)
	ListWatchedByUserID(ctx context.Context, arg ListWatchedByUserIDParams) ([]WatchProgress, error)
	MarkEnrichmentComplete(ctx context.Context, arg MarkEnrichmentCompleteParams) error
	MarkEnrichmentFailed(ctx context.Context, arg MarkEnrichmentFailedParams) error
	MarkEnrichmentSkipped(ctx context.Context, arg MarkEnrichmentSkippedParams) error
	MarkRunningAsInterrupted(ctx context.Context, resumable sql.NullInt64) (int64, error)
	MediaExistsInLibrary(ctx context.Context, arg MediaExistsInLibraryParams) (int64, error)
	PluginExists(ctx context.Context, id string) (int64, error)
	PluginKVCount(ctx context.Context, pluginID string) (int64, error)
	PluginKVDelete(ctx context.Context, arg PluginKVDeleteParams) error
	PluginKVDeleteByPlugin(ctx context.Context, pluginID string) error
	PluginKVDeleteExpired(ctx context.Context) error
	PluginKVGet(ctx context.Context, arg PluginKVGetParams) (PluginKVGetRow, error)
	PluginKVList(ctx context.Context, arg PluginKVListParams) ([]string, error)
	PluginKVSet(ctx context.Context, arg PluginKVSetParams) error
	PluginKVTotalSize(ctx context.Context, pluginID string) (interface{}, error)
	RefreshSchedulerLock(ctx context.Context, arg RefreshSchedulerLockParams) error
	ReleaseSchedulerLock(ctx context.Context, lockKey string) error
	ReleaseStuckEnrichmentJobs(ctx context.Context, dollar_1 sql.NullString) error
	RemoveMediaStudio(ctx context.Context, arg RemoveMediaStudioParams) error
	// Re-queue a job for retry without incrementing the attempt count.
	// Used for transient infrastructure errors (plugin restarts, connection issues).
	RequeueEnrichmentJob(ctx context.Context, arg RequeueEnrichmentJobParams) error
	ResetEnrichmentJobForRetry(ctx context.Context, id int64) error
	ResetFailedScanCheckpoints(ctx context.Context, scanJobID int64) error
	ResetPluginRestartCount(ctx context.Context, id string) error
	// Reset all 'processing' status records to 'pending'.
	// Called at startup to recover from crashed workers.
	ResetStuckEnrichmentStatus(ctx context.Context) (int64, error)
	// Reset a single failed job to pending for retry.
	RetryEnrichmentJob(ctx context.Context, id int64) error
	// Reset all failed jobs for a library to pending for retry.
	RetryEnrichmentJobsByLibrary(ctx context.Context, libraryID sql.NullInt64) (int64, error)
	ScheduledTaskExists(ctx context.Context, id string) (int64, error)
	SchedulerLockExists(ctx context.Context, lockKey string) (int64, error)
	SearchArtistsByName(ctx context.Context, arg SearchArtistsByNameParams) ([]MusicArtist, error)
	SearchArtistsWithCountsByNamePaginated(ctx context.Context, arg SearchArtistsWithCountsByNamePaginatedParams) ([]SearchArtistsWithCountsByNamePaginatedRow, error)
	SearchByKeyword(ctx context.Context, keyword string) ([]SearchByKeywordRow, error)
	SearchByLocationKeyword(ctx context.Context, keyword string) ([]SearchByLocationKeywordRow, error)
	SearchMoviesByTitle(ctx context.Context, arg SearchMoviesByTitleParams) ([]SearchMoviesByTitleRow, error)
	SearchMoviesByTitlePaginated(ctx context.Context, arg SearchMoviesByTitlePaginatedParams) ([]SearchMoviesByTitlePaginatedRow, error)
	// Searches movies across all libraries (for plugin use)
	SearchMoviesGlobal(ctx context.Context, arg SearchMoviesGlobalParams) ([]SearchMoviesGlobalRow, error)
	SearchMusicTracks(ctx context.Context, arg SearchMusicTracksParams) ([]SearchMusicTracksRow, error)
	SearchPeopleByName(ctx context.Context, arg SearchPeopleByNameParams) ([]Person, error)
	SearchTVEpisodesByTitle(ctx context.Context, arg SearchTVEpisodesByTitleParams) ([]SearchTVEpisodesByTitleRow, error)
	SearchTVShowsByTitle(ctx context.Context, arg SearchTVShowsByTitleParams) ([]TvShow, error)
	SearchTVShowsByTitlePaginated(ctx context.Context, arg SearchTVShowsByTitlePaginatedParams) ([]TvShow, error)
	// Searches TV shows across all libraries (for plugin use)
	SearchTVShowsGlobal(ctx context.Context, arg SearchTVShowsGlobalParams) ([]SearchTVShowsGlobalRow, error)
	SearchTVShowsWithCountsByTitlePaginated(ctx context.Context, arg SearchTVShowsWithCountsByTitlePaginatedParams) ([]SearchTVShowsWithCountsByTitlePaginatedRow, error)
	SetPluginUserMetadata(ctx context.Context, arg SetPluginUserMetadataParams) error
	SetScanStateError(ctx context.Context, arg SetScanStateErrorParams) error
	SetScanStateWarning(ctx context.Context, arg SetScanStateWarningParams) error
	SkipEnrichmentJob(ctx context.Context, id int64) error
	// Scheduler Locks Queries
	TryAcquireSchedulerLock(ctx context.Context, arg TryAcquireSchedulerLockParams) error
	UpdateAlbum(ctx context.Context, arg UpdateAlbumParams) error
	UpdateArtist(ctx context.Context, arg UpdateArtistParams) error
	UpdateImage(ctx context.Context, arg UpdateImageParams) error
	UpdateLibrary(ctx context.Context, arg UpdateLibraryParams) (Library, error)
	UpdateLibraryMonitoring(ctx context.Context, arg UpdateLibraryMonitoringParams) (Library, error)
	UpdateMedia(ctx context.Context, arg UpdateMediaParams) (Medium, error)
	UpdateMovie(ctx context.Context, arg UpdateMovieParams) error
	UpdateMusicTrack(ctx context.Context, arg UpdateMusicTrackParams) error
	UpdatePerson(ctx context.Context, arg UpdatePersonParams) error
	UpdatePipelineStage(ctx context.Context, arg UpdatePipelineStageParams) error
	UpdatePipelineStagePosition(ctx context.Context, arg UpdatePipelineStagePositionParams) error
	UpdatePlugin(ctx context.Context, arg UpdatePluginParams) error
	UpdatePluginHealth(ctx context.Context, arg UpdatePluginHealthParams) error
	UpdatePluginSettings(ctx context.Context, arg UpdatePluginSettingsParams) error
	UpdatePluginSettingsSchema(ctx context.Context, arg UpdatePluginSettingsSchemaParams) error
	// Updates priority for all pending/processing jobs for a media item.
	// Used to boost priority after enrichment discovers actual release date.
	// Only upgrades priority (higher values), never downgrades - preserves "added recently" boost.
	UpdatePriorityByMedia(ctx context.Context, arg UpdatePriorityByMediaParams) error
	UpdateScanCheckpointRetryCount(ctx context.Context, arg UpdateScanCheckpointRetryCountParams) error
	UpdateScanCheckpointStatus(ctx context.Context, arg UpdateScanCheckpointStatusParams) error
	UpdateScanJobProgress(ctx context.Context, arg UpdateScanJobProgressParams) error
	UpdateScanJobStatus(ctx context.Context, arg UpdateScanJobStatusParams) error
	UpdateScheduledTask(ctx context.Context, arg UpdateScheduledTaskParams) error
	UpdateSchedulerExecution(ctx context.Context, arg UpdateSchedulerExecutionParams) error
	UpdateSessionLastUsed(ctx context.Context, arg UpdateSessionLastUsedParams) error
	UpdateStudio(ctx context.Context, arg UpdateStudioParams) error
	UpdateTVEpisode(ctx context.Context, arg UpdateTVEpisodeParams) error
	UpdateTVSeason(ctx context.Context, arg UpdateTVSeasonParams) error
	UpdateTVShow(ctx context.Context, arg UpdateTVShowParams) error
	UpdateTranscodeFirstFrame(ctx context.Context, arg UpdateTranscodeFirstFrameParams) error
	UpdateTranscodeFirstSegment(ctx context.Context, arg UpdateTranscodeFirstSegmentParams) error
	UpdateTranscodeJob(ctx context.Context, arg UpdateTranscodeJobParams) error
	UpdateTranscodeJobAccess(ctx context.Context, arg UpdateTranscodeJobAccessParams) error
	UpdateTranscodeJobAccessByMediaAndQuality(ctx context.Context, arg UpdateTranscodeJobAccessByMediaAndQualityParams) error
	UpdateTranscodeManifestReady(ctx context.Context, arg UpdateTranscodeManifestReadyParams) error
	UpdateTranscodeSegmentCount(ctx context.Context, arg UpdateTranscodeSegmentCountParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserLocation(ctx context.Context, arg UpdateUserLocationParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateWatchProgress(ctx context.Context, arg UpdateWatchProgressParams) (WatchProgress, error)
	UpsertEnrichmentStatus(ctx context.Context, arg UpsertEnrichmentStatusParams) error
	// Upserts an external ID for any entity type (movies, tv_shows, tv_seasons, etc.)
	// Uses media_type + entity_id for polymorphic lookup
	UpsertExternalID(ctx context.Context, arg UpsertExternalIDParams) error
	UpsertMetadataSource(ctx context.Context, arg UpsertMetadataSourceParams) error
	UpsertPlaybackPreferences(ctx context.Context, arg UpsertPlaybackPreferencesParams) (PlaybackPreference, error)
	UpsertPlaybackSession(ctx context.Context, arg UpsertPlaybackSessionParams) (PlaybackSession, error)
	UpsertPlugin(ctx context.Context, arg UpsertPluginParams) error
	UpsertScanState(ctx context.Context, arg UpsertScanStateParams) error
	UpsertScheduledTask(ctx context.Context, arg UpsertScheduledTaskParams) error
	UpsertSystemSetting(ctx context.Context, arg UpsertSystemSettingParams) error
	// Atomically creates a TV show or returns existing one if title already exists.
	// Uses ON CONFLICT to handle race conditions during concurrent episode scans.
	// On conflict, updates directory if it was previously empty.
	UpsertTVShow(ctx context.Context, arg UpsertTVShowParams) (TvShow, error)
	UpsertUserSetting(ctx context.Context, arg UpsertUserSettingParams) error
	UpsertWatchProgress(ctx context.Context, arg UpsertWatchProgressParams) (WatchProgress, error)
}

var _ Querier = (*Queries)(nil)
