// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scan_job.sql

package sqlc_sqlite

import (
	"context"
	"database/sql"
)

const completeScanJob = `-- name: CompleteScanJob :exec
UPDATE scan_jobs
SET
    status = ?,
    progress = ?,
    files_found = ?,
    files_processed = ?,
    bytes_processed = ?,
    error_count = ?,
    completed_at = ?,
    error_message = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type CompleteScanJobParams struct {
	Status         string          `json:"status"`
	Progress       sql.NullFloat64 `json:"progress"`
	FilesFound     sql.NullInt64   `json:"files_found"`
	FilesProcessed sql.NullInt64   `json:"files_processed"`
	BytesProcessed sql.NullInt64   `json:"bytes_processed"`
	ErrorCount     sql.NullInt64   `json:"error_count"`
	CompletedAt    sql.NullTime    `json:"completed_at"`
	ErrorMessage   sql.NullString  `json:"error_message"`
	ID             int64           `json:"id"`
}

func (q *Queries) CompleteScanJob(ctx context.Context, arg CompleteScanJobParams) error {
	_, err := q.db.ExecContext(ctx, completeScanJob,
		arg.Status,
		arg.Progress,
		arg.FilesFound,
		arg.FilesProcessed,
		arg.BytesProcessed,
		arg.ErrorCount,
		arg.CompletedAt,
		arg.ErrorMessage,
		arg.ID,
	)
	return err
}

const countScanJobsByLibrary = `-- name: CountScanJobsByLibrary :one
SELECT COUNT(*) FROM scan_jobs
WHERE library_id = ?
`

func (q *Queries) CountScanJobsByLibrary(ctx context.Context, libraryID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countScanJobsByLibrary, libraryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createScanJob = `-- name: CreateScanJob :one
INSERT INTO scan_jobs (
    library_id,
    status,
    progress,
    files_found,
    files_processed,
    bytes_processed,
    error_count,
    started_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, library_id, status, progress, files_found, files_processed, bytes_processed, error_count, started_at, completed_at, error_message, created_at, updated_at
`

type CreateScanJobParams struct {
	LibraryID      int64           `json:"library_id"`
	Status         string          `json:"status"`
	Progress       sql.NullFloat64 `json:"progress"`
	FilesFound     sql.NullInt64   `json:"files_found"`
	FilesProcessed sql.NullInt64   `json:"files_processed"`
	BytesProcessed sql.NullInt64   `json:"bytes_processed"`
	ErrorCount     sql.NullInt64   `json:"error_count"`
	StartedAt      sql.NullTime    `json:"started_at"`
}

func (q *Queries) CreateScanJob(ctx context.Context, arg CreateScanJobParams) (ScanJob, error) {
	row := q.db.QueryRowContext(ctx, createScanJob,
		arg.LibraryID,
		arg.Status,
		arg.Progress,
		arg.FilesFound,
		arg.FilesProcessed,
		arg.BytesProcessed,
		arg.ErrorCount,
		arg.StartedAt,
	)
	var i ScanJob
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Status,
		&i.Progress,
		&i.FilesFound,
		&i.FilesProcessed,
		&i.BytesProcessed,
		&i.ErrorCount,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOldScanJobs = `-- name: DeleteOldScanJobs :exec
DELETE FROM scan_jobs
WHERE library_id = ?
  AND status IN ('completed', 'failed')
  AND created_at < datetime('now', ?)
`

type DeleteOldScanJobsParams struct {
	LibraryID int64       `json:"library_id"`
	Datetime  interface{} `json:"datetime"`
}

func (q *Queries) DeleteOldScanJobs(ctx context.Context, arg DeleteOldScanJobsParams) error {
	_, err := q.db.ExecContext(ctx, deleteOldScanJobs, arg.LibraryID, arg.Datetime)
	return err
}

const deleteScanJob = `-- name: DeleteScanJob :exec
DELETE FROM scan_jobs
WHERE id = ?
`

func (q *Queries) DeleteScanJob(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteScanJob, id)
	return err
}

const getLatestScanJobByLibrary = `-- name: GetLatestScanJobByLibrary :one
SELECT id, library_id, status, progress, files_found, files_processed, bytes_processed, error_count, started_at, completed_at, error_message, created_at, updated_at FROM scan_jobs
WHERE library_id = ?
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestScanJobByLibrary(ctx context.Context, libraryID int64) (ScanJob, error) {
	row := q.db.QueryRowContext(ctx, getLatestScanJobByLibrary, libraryID)
	var i ScanJob
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Status,
		&i.Progress,
		&i.FilesFound,
		&i.FilesProcessed,
		&i.BytesProcessed,
		&i.ErrorCount,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScanJob = `-- name: GetScanJob :one
SELECT id, library_id, status, progress, files_found, files_processed, bytes_processed, error_count, started_at, completed_at, error_message, created_at, updated_at FROM scan_jobs
WHERE id = ?
`

func (q *Queries) GetScanJob(ctx context.Context, id int64) (ScanJob, error) {
	row := q.db.QueryRowContext(ctx, getScanJob, id)
	var i ScanJob
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Status,
		&i.Progress,
		&i.FilesFound,
		&i.FilesProcessed,
		&i.BytesProcessed,
		&i.ErrorCount,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScanJobStats = `-- name: GetScanJobStats :one
SELECT
    COUNT(*) as total_jobs,
    SUM(CASE WHEN status = 'running' THEN 1 ELSE 0 END) as running_jobs,
    SUM(CASE WHEN status = 'completed' THEN 1 ELSE 0 END) as completed_jobs,
    SUM(CASE WHEN status = 'failed' THEN 1 ELSE 0 END) as failed_jobs,
    SUM(files_processed) as total_files_processed,
    SUM(bytes_processed) as total_bytes_processed
FROM scan_jobs
WHERE library_id = ?
`

type GetScanJobStatsRow struct {
	TotalJobs           int64           `json:"total_jobs"`
	RunningJobs         sql.NullFloat64 `json:"running_jobs"`
	CompletedJobs       sql.NullFloat64 `json:"completed_jobs"`
	FailedJobs          sql.NullFloat64 `json:"failed_jobs"`
	TotalFilesProcessed sql.NullFloat64 `json:"total_files_processed"`
	TotalBytesProcessed sql.NullFloat64 `json:"total_bytes_processed"`
}

func (q *Queries) GetScanJobStats(ctx context.Context, libraryID int64) (GetScanJobStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getScanJobStats, libraryID)
	var i GetScanJobStatsRow
	err := row.Scan(
		&i.TotalJobs,
		&i.RunningJobs,
		&i.CompletedJobs,
		&i.FailedJobs,
		&i.TotalFilesProcessed,
		&i.TotalBytesProcessed,
	)
	return i, err
}

const listRunningScanJobs = `-- name: ListRunningScanJobs :many
SELECT id, library_id, status, progress, files_found, files_processed, bytes_processed, error_count, started_at, completed_at, error_message, created_at, updated_at FROM scan_jobs
WHERE status = 'running'
ORDER BY started_at ASC
`

func (q *Queries) ListRunningScanJobs(ctx context.Context) ([]ScanJob, error) {
	rows, err := q.db.QueryContext(ctx, listRunningScanJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanJob{}
	for rows.Next() {
		var i ScanJob
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Status,
			&i.Progress,
			&i.FilesFound,
			&i.FilesProcessed,
			&i.BytesProcessed,
			&i.ErrorCount,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScanJobsByLibrary = `-- name: ListScanJobsByLibrary :many
SELECT id, library_id, status, progress, files_found, files_processed, bytes_processed, error_count, started_at, completed_at, error_message, created_at, updated_at FROM scan_jobs
WHERE library_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListScanJobsByLibraryParams struct {
	LibraryID int64 `json:"library_id"`
	Limit     int64 `json:"limit"`
}

func (q *Queries) ListScanJobsByLibrary(ctx context.Context, arg ListScanJobsByLibraryParams) ([]ScanJob, error) {
	rows, err := q.db.QueryContext(ctx, listScanJobsByLibrary, arg.LibraryID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanJob{}
	for rows.Next() {
		var i ScanJob
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Status,
			&i.Progress,
			&i.FilesFound,
			&i.FilesProcessed,
			&i.BytesProcessed,
			&i.ErrorCount,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScanJobProgress = `-- name: UpdateScanJobProgress :exec
UPDATE scan_jobs
SET
    progress = ?,
    files_found = ?,
    files_processed = ?,
    bytes_processed = ?,
    error_count = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateScanJobProgressParams struct {
	Progress       sql.NullFloat64 `json:"progress"`
	FilesFound     sql.NullInt64   `json:"files_found"`
	FilesProcessed sql.NullInt64   `json:"files_processed"`
	BytesProcessed sql.NullInt64   `json:"bytes_processed"`
	ErrorCount     sql.NullInt64   `json:"error_count"`
	ID             int64           `json:"id"`
}

func (q *Queries) UpdateScanJobProgress(ctx context.Context, arg UpdateScanJobProgressParams) error {
	_, err := q.db.ExecContext(ctx, updateScanJobProgress,
		arg.Progress,
		arg.FilesFound,
		arg.FilesProcessed,
		arg.BytesProcessed,
		arg.ErrorCount,
		arg.ID,
	)
	return err
}

const updateScanJobStatus = `-- name: UpdateScanJobStatus :exec
UPDATE scan_jobs
SET
    status = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateScanJobStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateScanJobStatus(ctx context.Context, arg UpdateScanJobStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateScanJobStatus, arg.Status, arg.ID)
	return err
}
