// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package sqlc_sqlite

import (
	"context"
	"database/sql"
)

const deleteAllUserSettings = `-- name: DeleteAllUserSettings :exec
DELETE FROM user_settings
WHERE user_id = ?
`

func (q *Queries) DeleteAllUserSettings(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteAllUserSettings, userID)
	return err
}

const deleteSystemSetting = `-- name: DeleteSystemSetting :exec
DELETE FROM system_settings
WHERE key = ?
`

func (q *Queries) DeleteSystemSetting(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteSystemSetting, key)
	return err
}

const deleteUserSetting = `-- name: DeleteUserSetting :exec
DELETE FROM user_settings
WHERE user_id = ? AND key = ?
`

type DeleteUserSettingParams struct {
	UserID string `json:"user_id"`
	Key    string `json:"key"`
}

func (q *Queries) DeleteUserSetting(ctx context.Context, arg DeleteUserSettingParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserSetting, arg.UserID, arg.Key)
	return err
}

const getAllSystemSettings = `-- name: GetAllSystemSettings :many
SELECT "key", value, value_type, category, description, updated_at, updated_by FROM system_settings
ORDER BY category, key
`

func (q *Queries) GetAllSystemSettings(ctx context.Context) ([]SystemSetting, error) {
	rows, err := q.db.QueryContext(ctx, getAllSystemSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemSetting{}
	for rows.Next() {
		var i SystemSetting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.ValueType,
			&i.Category,
			&i.Description,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUserSettings = `-- name: GetAllUserSettings :many
SELECT user_id, "key", value, updated_at FROM user_settings
WHERE user_id = ?
ORDER BY key
`

func (q *Queries) GetAllUserSettings(ctx context.Context, userID string) ([]UserSetting, error) {
	rows, err := q.db.QueryContext(ctx, getAllUserSettings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserSetting{}
	for rows.Next() {
		var i UserSetting
		if err := rows.Scan(
			&i.UserID,
			&i.Key,
			&i.Value,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSystemSetting = `-- name: GetSystemSetting :one

SELECT "key", value, value_type, category, description, updated_at, updated_by FROM system_settings
WHERE key = ?
LIMIT 1
`

// Settings queries for SQLite
func (q *Queries) GetSystemSetting(ctx context.Context, key string) (SystemSetting, error) {
	row := q.db.QueryRowContext(ctx, getSystemSetting, key)
	var i SystemSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.ValueType,
		&i.Category,
		&i.Description,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getSystemSettingsByCategory = `-- name: GetSystemSettingsByCategory :many
SELECT "key", value, value_type, category, description, updated_at, updated_by FROM system_settings
WHERE category = ?
ORDER BY key
`

func (q *Queries) GetSystemSettingsByCategory(ctx context.Context, category string) ([]SystemSetting, error) {
	rows, err := q.db.QueryContext(ctx, getSystemSettingsByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemSetting{}
	for rows.Next() {
		var i SystemSetting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.ValueType,
			&i.Category,
			&i.Description,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserSetting = `-- name: GetUserSetting :one
SELECT user_id, "key", value, updated_at FROM user_settings
WHERE user_id = ? AND key = ?
LIMIT 1
`

type GetUserSettingParams struct {
	UserID string `json:"user_id"`
	Key    string `json:"key"`
}

func (q *Queries) GetUserSetting(ctx context.Context, arg GetUserSettingParams) (UserSetting, error) {
	row := q.db.QueryRowContext(ctx, getUserSetting, arg.UserID, arg.Key)
	var i UserSetting
	err := row.Scan(
		&i.UserID,
		&i.Key,
		&i.Value,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSystemSetting = `-- name: UpsertSystemSetting :exec
INSERT INTO system_settings (key, value, value_type, category, description, updated_at, updated_by)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(key) DO UPDATE SET
    value = excluded.value,
    updated_at = excluded.updated_at,
    updated_by = excluded.updated_by
`

type UpsertSystemSettingParams struct {
	Key         string         `json:"key"`
	Value       string         `json:"value"`
	ValueType   string         `json:"value_type"`
	Category    string         `json:"category"`
	Description sql.NullString `json:"description"`
	UpdatedAt   string         `json:"updated_at"`
	UpdatedBy   sql.NullString `json:"updated_by"`
}

func (q *Queries) UpsertSystemSetting(ctx context.Context, arg UpsertSystemSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSystemSetting,
		arg.Key,
		arg.Value,
		arg.ValueType,
		arg.Category,
		arg.Description,
		arg.UpdatedAt,
		arg.UpdatedBy,
	)
	return err
}

const upsertUserSetting = `-- name: UpsertUserSetting :exec
INSERT INTO user_settings (user_id, key, value, updated_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(user_id, key) DO UPDATE SET
    value = excluded.value,
    updated_at = excluded.updated_at
`

type UpsertUserSettingParams struct {
	UserID    string `json:"user_id"`
	Key       string `json:"key"`
	Value     string `json:"value"`
	UpdatedAt string `json:"updated_at"`
}

func (q *Queries) UpsertUserSetting(ctx context.Context, arg UpsertUserSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserSetting,
		arg.UserID,
		arg.Key,
		arg.Value,
		arg.UpdatedAt,
	)
	return err
}
