// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transcode_jobs.sql

package sqlc_sqlite

import (
	"context"
	"database/sql"
)

const countTranscodeJobsByStatus = `-- name: CountTranscodeJobsByStatus :one
SELECT COUNT(*) FROM transcode_jobs
WHERE status = ?
`

func (q *Queries) CountTranscodeJobsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTranscodeJobsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTranscodeJob = `-- name: CreateTranscodeJob :one
INSERT INTO transcode_jobs (
    media_id,
    quality,
    type,
    status,
    progress,
    created_at
) VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, media_id, quality, type, status, progress, error, started_at, completed_at, created_at, file_path, file_size_bytes, last_accessed_at, access_count, start_position, codec, client_device_type, client_network_type, recommended_quality, streaming_strategy
`

type CreateTranscodeJobParams struct {
	MediaID   int64         `json:"media_id"`
	Quality   string        `json:"quality"`
	Type      string        `json:"type"`
	Status    string        `json:"status"`
	Progress  sql.NullInt64 `json:"progress"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

func (q *Queries) CreateTranscodeJob(ctx context.Context, arg CreateTranscodeJobParams) (TranscodeJob, error) {
	row := q.db.QueryRowContext(ctx, createTranscodeJob,
		arg.MediaID,
		arg.Quality,
		arg.Type,
		arg.Status,
		arg.Progress,
		arg.CreatedAt,
	)
	var i TranscodeJob
	err := row.Scan(
		&i.ID,
		&i.MediaID,
		&i.Quality,
		&i.Type,
		&i.Status,
		&i.Progress,
		&i.Error,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.FilePath,
		&i.FileSizeBytes,
		&i.LastAccessedAt,
		&i.AccessCount,
		&i.StartPosition,
		&i.Codec,
		&i.ClientDeviceType,
		&i.ClientNetworkType,
		&i.RecommendedQuality,
		&i.StreamingStrategy,
	)
	return i, err
}

const deleteTranscodeJob = `-- name: DeleteTranscodeJob :exec
DELETE FROM transcode_jobs
WHERE id = ?
`

func (q *Queries) DeleteTranscodeJob(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTranscodeJob, id)
	return err
}

const deleteTranscodeJobsByMediaID = `-- name: DeleteTranscodeJobsByMediaID :exec
DELETE FROM transcode_jobs
WHERE media_id = ?
`

func (q *Queries) DeleteTranscodeJobsByMediaID(ctx context.Context, mediaID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTranscodeJobsByMediaID, mediaID)
	return err
}

const getTotalTranscodeSize = `-- name: GetTotalTranscodeSize :one
SELECT COALESCE(SUM(file_size_bytes), 0) as total_size
FROM transcode_jobs
WHERE status = 'completed'
`

func (q *Queries) GetTotalTranscodeSize(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getTotalTranscodeSize)
	var total_size interface{}
	err := row.Scan(&total_size)
	return total_size, err
}

const getTranscodeJobByID = `-- name: GetTranscodeJobByID :one
SELECT id, media_id, quality, type, status, progress, error, started_at, completed_at, created_at, file_path, file_size_bytes, last_accessed_at, access_count, start_position, codec, client_device_type, client_network_type, recommended_quality, streaming_strategy FROM transcode_jobs
WHERE id = ?
`

func (q *Queries) GetTranscodeJobByID(ctx context.Context, id int64) (TranscodeJob, error) {
	row := q.db.QueryRowContext(ctx, getTranscodeJobByID, id)
	var i TranscodeJob
	err := row.Scan(
		&i.ID,
		&i.MediaID,
		&i.Quality,
		&i.Type,
		&i.Status,
		&i.Progress,
		&i.Error,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.FilePath,
		&i.FileSizeBytes,
		&i.LastAccessedAt,
		&i.AccessCount,
		&i.StartPosition,
		&i.Codec,
		&i.ClientDeviceType,
		&i.ClientNetworkType,
		&i.RecommendedQuality,
		&i.StreamingStrategy,
	)
	return i, err
}

const getTranscodeJobByMediaIDAndQuality = `-- name: GetTranscodeJobByMediaIDAndQuality :one
SELECT id, media_id, quality, type, status, progress, error, started_at, completed_at, created_at, file_path, file_size_bytes, last_accessed_at, access_count, start_position, codec, client_device_type, client_network_type, recommended_quality, streaming_strategy FROM transcode_jobs
WHERE media_id = ? AND quality = ?
`

type GetTranscodeJobByMediaIDAndQualityParams struct {
	MediaID int64  `json:"media_id"`
	Quality string `json:"quality"`
}

func (q *Queries) GetTranscodeJobByMediaIDAndQuality(ctx context.Context, arg GetTranscodeJobByMediaIDAndQualityParams) (TranscodeJob, error) {
	row := q.db.QueryRowContext(ctx, getTranscodeJobByMediaIDAndQuality, arg.MediaID, arg.Quality)
	var i TranscodeJob
	err := row.Scan(
		&i.ID,
		&i.MediaID,
		&i.Quality,
		&i.Type,
		&i.Status,
		&i.Progress,
		&i.Error,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.FilePath,
		&i.FileSizeBytes,
		&i.LastAccessedAt,
		&i.AccessCount,
		&i.StartPosition,
		&i.Codec,
		&i.ClientDeviceType,
		&i.ClientNetworkType,
		&i.RecommendedQuality,
		&i.StreamingStrategy,
	)
	return i, err
}

const listAllTranscodeJobs = `-- name: ListAllTranscodeJobs :many
SELECT id, media_id, quality, type, status, progress, error, started_at, completed_at, created_at, file_path, file_size_bytes, last_accessed_at, access_count, start_position, codec, client_device_type, client_network_type, recommended_quality, streaming_strategy FROM transcode_jobs
ORDER BY created_at DESC
`

func (q *Queries) ListAllTranscodeJobs(ctx context.Context) ([]TranscodeJob, error) {
	rows, err := q.db.QueryContext(ctx, listAllTranscodeJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TranscodeJob{}
	for rows.Next() {
		var i TranscodeJob
		if err := rows.Scan(
			&i.ID,
			&i.MediaID,
			&i.Quality,
			&i.Type,
			&i.Status,
			&i.Progress,
			&i.Error,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.FilePath,
			&i.FileSizeBytes,
			&i.LastAccessedAt,
			&i.AccessCount,
			&i.StartPosition,
			&i.Codec,
			&i.ClientDeviceType,
			&i.ClientNetworkType,
			&i.RecommendedQuality,
			&i.StreamingStrategy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProcessingTranscodeJobs = `-- name: ListProcessingTranscodeJobs :many
SELECT id, media_id, quality, type, status, progress, error, started_at, completed_at, created_at, file_path, file_size_bytes, last_accessed_at, access_count, start_position, codec, client_device_type, client_network_type, recommended_quality, streaming_strategy FROM transcode_jobs
WHERE status = 'processing'
ORDER BY started_at ASC
`

func (q *Queries) ListProcessingTranscodeJobs(ctx context.Context) ([]TranscodeJob, error) {
	rows, err := q.db.QueryContext(ctx, listProcessingTranscodeJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TranscodeJob{}
	for rows.Next() {
		var i TranscodeJob
		if err := rows.Scan(
			&i.ID,
			&i.MediaID,
			&i.Quality,
			&i.Type,
			&i.Status,
			&i.Progress,
			&i.Error,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.FilePath,
			&i.FileSizeBytes,
			&i.LastAccessedAt,
			&i.AccessCount,
			&i.StartPosition,
			&i.Codec,
			&i.ClientDeviceType,
			&i.ClientNetworkType,
			&i.RecommendedQuality,
			&i.StreamingStrategy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueuedTranscodeJobs = `-- name: ListQueuedTranscodeJobs :many
SELECT id, media_id, quality, type, status, progress, error, started_at, completed_at, created_at, file_path, file_size_bytes, last_accessed_at, access_count, start_position, codec, client_device_type, client_network_type, recommended_quality, streaming_strategy FROM transcode_jobs
WHERE status = 'queued'
ORDER BY created_at ASC
LIMIT ?
`

func (q *Queries) ListQueuedTranscodeJobs(ctx context.Context, limit int64) ([]TranscodeJob, error) {
	rows, err := q.db.QueryContext(ctx, listQueuedTranscodeJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TranscodeJob{}
	for rows.Next() {
		var i TranscodeJob
		if err := rows.Scan(
			&i.ID,
			&i.MediaID,
			&i.Quality,
			&i.Type,
			&i.Status,
			&i.Progress,
			&i.Error,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.FilePath,
			&i.FileSizeBytes,
			&i.LastAccessedAt,
			&i.AccessCount,
			&i.StartPosition,
			&i.Codec,
			&i.ClientDeviceType,
			&i.ClientNetworkType,
			&i.RecommendedQuality,
			&i.StreamingStrategy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranscodeJobsByLRU = `-- name: ListTranscodeJobsByLRU :many
SELECT id, media_id, quality, type, status, progress, error, started_at, completed_at, created_at, file_path, file_size_bytes, last_accessed_at, access_count, start_position, codec, client_device_type, client_network_type, recommended_quality, streaming_strategy FROM transcode_jobs
WHERE status = 'completed'
  AND last_accessed_at IS NOT NULL
ORDER BY last_accessed_at ASC
LIMIT ?
`

func (q *Queries) ListTranscodeJobsByLRU(ctx context.Context, limit int64) ([]TranscodeJob, error) {
	rows, err := q.db.QueryContext(ctx, listTranscodeJobsByLRU, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TranscodeJob{}
	for rows.Next() {
		var i TranscodeJob
		if err := rows.Scan(
			&i.ID,
			&i.MediaID,
			&i.Quality,
			&i.Type,
			&i.Status,
			&i.Progress,
			&i.Error,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.FilePath,
			&i.FileSizeBytes,
			&i.LastAccessedAt,
			&i.AccessCount,
			&i.StartPosition,
			&i.Codec,
			&i.ClientDeviceType,
			&i.ClientNetworkType,
			&i.RecommendedQuality,
			&i.StreamingStrategy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranscodeJobsByMediaID = `-- name: ListTranscodeJobsByMediaID :many
SELECT id, media_id, quality, type, status, progress, error, started_at, completed_at, created_at, file_path, file_size_bytes, last_accessed_at, access_count, start_position, codec, client_device_type, client_network_type, recommended_quality, streaming_strategy FROM transcode_jobs
WHERE media_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListTranscodeJobsByMediaID(ctx context.Context, mediaID int64) ([]TranscodeJob, error) {
	rows, err := q.db.QueryContext(ctx, listTranscodeJobsByMediaID, mediaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TranscodeJob{}
	for rows.Next() {
		var i TranscodeJob
		if err := rows.Scan(
			&i.ID,
			&i.MediaID,
			&i.Quality,
			&i.Type,
			&i.Status,
			&i.Progress,
			&i.Error,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.FilePath,
			&i.FileSizeBytes,
			&i.LastAccessedAt,
			&i.AccessCount,
			&i.StartPosition,
			&i.Codec,
			&i.ClientDeviceType,
			&i.ClientNetworkType,
			&i.RecommendedQuality,
			&i.StreamingStrategy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranscodeJobsByStatus = `-- name: ListTranscodeJobsByStatus :many
SELECT id, media_id, quality, type, status, progress, error, started_at, completed_at, created_at, file_path, file_size_bytes, last_accessed_at, access_count, start_position, codec, client_device_type, client_network_type, recommended_quality, streaming_strategy FROM transcode_jobs
WHERE status = ?
ORDER BY created_at ASC
`

func (q *Queries) ListTranscodeJobsByStatus(ctx context.Context, status string) ([]TranscodeJob, error) {
	rows, err := q.db.QueryContext(ctx, listTranscodeJobsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TranscodeJob{}
	for rows.Next() {
		var i TranscodeJob
		if err := rows.Scan(
			&i.ID,
			&i.MediaID,
			&i.Quality,
			&i.Type,
			&i.Status,
			&i.Progress,
			&i.Error,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.FilePath,
			&i.FileSizeBytes,
			&i.LastAccessedAt,
			&i.AccessCount,
			&i.StartPosition,
			&i.Codec,
			&i.ClientDeviceType,
			&i.ClientNetworkType,
			&i.RecommendedQuality,
			&i.StreamingStrategy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTranscodeJob = `-- name: UpdateTranscodeJob :exec
UPDATE transcode_jobs
SET status = ?,
    progress = ?,
    error = ?,
    started_at = ?,
    completed_at = ?,
    file_path = ?,
    file_size_bytes = ?,
    start_position = ?
WHERE id = ?
`

type UpdateTranscodeJobParams struct {
	Status        string          `json:"status"`
	Progress      sql.NullInt64   `json:"progress"`
	Error         sql.NullString  `json:"error"`
	StartedAt     sql.NullTime    `json:"started_at"`
	CompletedAt   sql.NullTime    `json:"completed_at"`
	FilePath      sql.NullString  `json:"file_path"`
	FileSizeBytes sql.NullInt64   `json:"file_size_bytes"`
	StartPosition sql.NullFloat64 `json:"start_position"`
	ID            int64           `json:"id"`
}

func (q *Queries) UpdateTranscodeJob(ctx context.Context, arg UpdateTranscodeJobParams) error {
	_, err := q.db.ExecContext(ctx, updateTranscodeJob,
		arg.Status,
		arg.Progress,
		arg.Error,
		arg.StartedAt,
		arg.CompletedAt,
		arg.FilePath,
		arg.FileSizeBytes,
		arg.StartPosition,
		arg.ID,
	)
	return err
}

const updateTranscodeJobAccess = `-- name: UpdateTranscodeJobAccess :exec
UPDATE transcode_jobs
SET last_accessed_at = ?,
    access_count = access_count + 1
WHERE id = ?
`

type UpdateTranscodeJobAccessParams struct {
	LastAccessedAt sql.NullTime `json:"last_accessed_at"`
	ID             int64        `json:"id"`
}

func (q *Queries) UpdateTranscodeJobAccess(ctx context.Context, arg UpdateTranscodeJobAccessParams) error {
	_, err := q.db.ExecContext(ctx, updateTranscodeJobAccess, arg.LastAccessedAt, arg.ID)
	return err
}

const updateTranscodeJobAccessByMediaAndQuality = `-- name: UpdateTranscodeJobAccessByMediaAndQuality :exec
UPDATE transcode_jobs
SET last_accessed_at = ?,
    access_count = access_count + 1
WHERE media_id = ? AND quality = ?
`

type UpdateTranscodeJobAccessByMediaAndQualityParams struct {
	LastAccessedAt sql.NullTime `json:"last_accessed_at"`
	MediaID        int64        `json:"media_id"`
	Quality        string       `json:"quality"`
}

func (q *Queries) UpdateTranscodeJobAccessByMediaAndQuality(ctx context.Context, arg UpdateTranscodeJobAccessByMediaAndQualityParams) error {
	_, err := q.db.ExecContext(ctx, updateTranscodeJobAccessByMediaAndQuality, arg.LastAccessedAt, arg.MediaID, arg.Quality)
	return err
}
