// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tv_shows.sql

package sqlc_sqlite

import (
	"context"
	"database/sql"
	"strings"
)

const countSearchTVShowsByTitle = `-- name: CountSearchTVShowsByTitle :one
SELECT COUNT(*)
FROM tv_shows
WHERE library_id = ?
  AND (title LIKE ? OR original_title LIKE ?)
`

type CountSearchTVShowsByTitleParams struct {
	LibraryID     int64          `json:"library_id"`
	Title         string         `json:"title"`
	OriginalTitle sql.NullString `json:"original_title"`
}

func (q *Queries) CountSearchTVShowsByTitle(ctx context.Context, arg CountSearchTVShowsByTitleParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSearchTVShowsByTitle, arg.LibraryID, arg.Title, arg.OriginalTitle)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTVShowsByLibrary = `-- name: CountTVShowsByLibrary :one

SELECT COUNT(*)
FROM tv_shows
WHERE library_id = ?
`

// ============================================================================
// Pagination Support Queries
// ============================================================================
func (q *Queries) CountTVShowsByLibrary(ctx context.Context, libraryID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTVShowsByLibrary, libraryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTVEpisode = `-- name: CreateTVEpisode :exec

INSERT INTO tv_episodes (
    media_id, show_id, season_id, season_number, episode_number,
    absolute_number, dvd_season, dvd_episode, episode_title, original_title,
    air_date, plot, content_rating, maturity_rating, imdb_id, tmdb_id, tvdb_id,
    rating, rating_votes, runtime_minutes
) VALUES (
    ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?
)
`

type CreateTVEpisodeParams struct {
	MediaID        int64           `json:"media_id"`
	ShowID         int64           `json:"show_id"`
	SeasonID       int64           `json:"season_id"`
	SeasonNumber   int64           `json:"season_number"`
	EpisodeNumber  int64           `json:"episode_number"`
	AbsoluteNumber sql.NullInt64   `json:"absolute_number"`
	DvdSeason      sql.NullInt64   `json:"dvd_season"`
	DvdEpisode     sql.NullInt64   `json:"dvd_episode"`
	EpisodeTitle   sql.NullString  `json:"episode_title"`
	OriginalTitle  sql.NullString  `json:"original_title"`
	AirDate        sql.NullTime    `json:"air_date"`
	Plot           sql.NullString  `json:"plot"`
	ContentRating  sql.NullString  `json:"content_rating"`
	MaturityRating sql.NullInt64   `json:"maturity_rating"`
	ImdbID         sql.NullString  `json:"imdb_id"`
	TmdbID         sql.NullInt64   `json:"tmdb_id"`
	TvdbID         sql.NullInt64   `json:"tvdb_id"`
	Rating         sql.NullFloat64 `json:"rating"`
	RatingVotes    sql.NullInt64   `json:"rating_votes"`
	RuntimeMinutes sql.NullInt64   `json:"runtime_minutes"`
}

// ============================================================================
// TV Episodes
// ============================================================================
func (q *Queries) CreateTVEpisode(ctx context.Context, arg CreateTVEpisodeParams) error {
	_, err := q.db.ExecContext(ctx, createTVEpisode,
		arg.MediaID,
		arg.ShowID,
		arg.SeasonID,
		arg.SeasonNumber,
		arg.EpisodeNumber,
		arg.AbsoluteNumber,
		arg.DvdSeason,
		arg.DvdEpisode,
		arg.EpisodeTitle,
		arg.OriginalTitle,
		arg.AirDate,
		arg.Plot,
		arg.ContentRating,
		arg.MaturityRating,
		arg.ImdbID,
		arg.TmdbID,
		arg.TvdbID,
		arg.Rating,
		arg.RatingVotes,
		arg.RuntimeMinutes,
	)
	return err
}

const createTVSeason = `-- name: CreateTVSeason :one

INSERT INTO tv_seasons (
    show_id, season_number, name, overview, air_date, poster_path, episode_count
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
) RETURNING id, show_id, season_number, name, overview, air_date, poster_path, episode_count, created_at, updated_at
`

type CreateTVSeasonParams struct {
	ShowID       int64          `json:"show_id"`
	SeasonNumber int64          `json:"season_number"`
	Name         sql.NullString `json:"name"`
	Overview     sql.NullString `json:"overview"`
	AirDate      sql.NullTime   `json:"air_date"`
	PosterPath   sql.NullString `json:"poster_path"`
	EpisodeCount sql.NullInt64  `json:"episode_count"`
}

// ============================================================================
// TV Seasons
// ============================================================================
func (q *Queries) CreateTVSeason(ctx context.Context, arg CreateTVSeasonParams) (TvSeason, error) {
	row := q.db.QueryRowContext(ctx, createTVSeason,
		arg.ShowID,
		arg.SeasonNumber,
		arg.Name,
		arg.Overview,
		arg.AirDate,
		arg.PosterPath,
		arg.EpisodeCount,
	)
	var i TvSeason
	err := row.Scan(
		&i.ID,
		&i.ShowID,
		&i.SeasonNumber,
		&i.Name,
		&i.Overview,
		&i.AirDate,
		&i.PosterPath,
		&i.EpisodeCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTVShow = `-- name: CreateTVShow :one

INSERT INTO tv_shows (
    library_id, title, original_title, sort_title, year, first_air_date,
    last_air_date, genre, plot, status, content_rating, maturity_rating,
    network, original_language, country_of_origin, imdb_id, tmdb_id, tvdb_id,
    directory, rating, rating_votes, tagline
) VALUES (
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?
) RETURNING id, library_id, title, original_title, sort_title, year, first_air_date, last_air_date, genre, plot, status, content_rating, maturity_rating, network, original_language, country_of_origin, imdb_id, tmdb_id, tvdb_id, created_at, updated_at, directory, rating, rating_votes, tagline
`

type CreateTVShowParams struct {
	LibraryID        int64           `json:"library_id"`
	Title            string          `json:"title"`
	OriginalTitle    sql.NullString  `json:"original_title"`
	SortTitle        sql.NullString  `json:"sort_title"`
	Year             sql.NullInt64   `json:"year"`
	FirstAirDate     sql.NullTime    `json:"first_air_date"`
	LastAirDate      sql.NullTime    `json:"last_air_date"`
	Genre            sql.NullString  `json:"genre"`
	Plot             sql.NullString  `json:"plot"`
	Status           sql.NullString  `json:"status"`
	ContentRating    sql.NullString  `json:"content_rating"`
	MaturityRating   sql.NullInt64   `json:"maturity_rating"`
	Network          sql.NullString  `json:"network"`
	OriginalLanguage sql.NullString  `json:"original_language"`
	CountryOfOrigin  sql.NullString  `json:"country_of_origin"`
	ImdbID           sql.NullString  `json:"imdb_id"`
	TmdbID           sql.NullInt64   `json:"tmdb_id"`
	TvdbID           sql.NullInt64   `json:"tvdb_id"`
	Directory        sql.NullString  `json:"directory"`
	Rating           sql.NullFloat64 `json:"rating"`
	RatingVotes      sql.NullInt64   `json:"rating_votes"`
	Tagline          sql.NullString  `json:"tagline"`
}

// ============================================================================
// TV Shows
// ============================================================================
func (q *Queries) CreateTVShow(ctx context.Context, arg CreateTVShowParams) (TvShow, error) {
	row := q.db.QueryRowContext(ctx, createTVShow,
		arg.LibraryID,
		arg.Title,
		arg.OriginalTitle,
		arg.SortTitle,
		arg.Year,
		arg.FirstAirDate,
		arg.LastAirDate,
		arg.Genre,
		arg.Plot,
		arg.Status,
		arg.ContentRating,
		arg.MaturityRating,
		arg.Network,
		arg.OriginalLanguage,
		arg.CountryOfOrigin,
		arg.ImdbID,
		arg.TmdbID,
		arg.TvdbID,
		arg.Directory,
		arg.Rating,
		arg.RatingVotes,
		arg.Tagline,
	)
	var i TvShow
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Title,
		&i.OriginalTitle,
		&i.SortTitle,
		&i.Year,
		&i.FirstAirDate,
		&i.LastAirDate,
		&i.Genre,
		&i.Plot,
		&i.Status,
		&i.ContentRating,
		&i.MaturityRating,
		&i.Network,
		&i.OriginalLanguage,
		&i.CountryOfOrigin,
		&i.ImdbID,
		&i.TmdbID,
		&i.TvdbID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Directory,
		&i.Rating,
		&i.RatingVotes,
		&i.Tagline,
	)
	return i, err
}

const deleteTVEpisode = `-- name: DeleteTVEpisode :exec
DELETE FROM tv_episodes
WHERE media_id = ?
`

func (q *Queries) DeleteTVEpisode(ctx context.Context, mediaID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTVEpisode, mediaID)
	return err
}

const deleteTVSeason = `-- name: DeleteTVSeason :exec
DELETE FROM tv_seasons
WHERE id = ?
`

func (q *Queries) DeleteTVSeason(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTVSeason, id)
	return err
}

const deleteTVShow = `-- name: DeleteTVShow :exec
DELETE FROM tv_shows
WHERE id = ?
`

func (q *Queries) DeleteTVShow(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTVShow, id)
	return err
}

const getEpisodeWithShowTitle = `-- name: GetEpisodeWithShowTitle :one
SELECT
    e.media_id,
    med.library_id,
    med.title,
    e.season_number,
    e.episode_number,
    e.episode_title,
    e.plot,
    s.title as show_title,
    s.genre as show_genre
FROM tv_episodes e
JOIN media med ON e.media_id = med.id
JOIN tv_shows s ON e.show_id = s.id
WHERE e.media_id = ?
`

type GetEpisodeWithShowTitleRow struct {
	MediaID       int64          `json:"media_id"`
	LibraryID     int64          `json:"library_id"`
	Title         string         `json:"title"`
	SeasonNumber  int64          `json:"season_number"`
	EpisodeNumber int64          `json:"episode_number"`
	EpisodeTitle  sql.NullString `json:"episode_title"`
	Plot          sql.NullString `json:"plot"`
	ShowTitle     string         `json:"show_title"`
	ShowGenre     sql.NullString `json:"show_genre"`
}

// Returns episode details with the parent show's title for plugin indexing
func (q *Queries) GetEpisodeWithShowTitle(ctx context.Context, mediaID int64) (GetEpisodeWithShowTitleRow, error) {
	row := q.db.QueryRowContext(ctx, getEpisodeWithShowTitle, mediaID)
	var i GetEpisodeWithShowTitleRow
	err := row.Scan(
		&i.MediaID,
		&i.LibraryID,
		&i.Title,
		&i.SeasonNumber,
		&i.EpisodeNumber,
		&i.EpisodeTitle,
		&i.Plot,
		&i.ShowTitle,
		&i.ShowGenre,
	)
	return i, err
}

const getTVEpisodeByMediaID = `-- name: GetTVEpisodeByMediaID :one
SELECT
    e.media_id, e.show_id, e.season_id, e.season_number, e.episode_number, e.absolute_number, e.dvd_season, e.dvd_episode, e.episode_title, e.original_title, e.air_date, e.plot, e.content_rating, e.maturity_rating, e.imdb_id, e.tmdb_id, e.tvdb_id, e.rating, e.rating_votes, e.runtime_minutes,
    med.id as media_id,
    med.library_id,
    med.title,
    med.file_path,
    med.file_size,
    med.file_hash,
    med.container_format,
    med.duration,
    med.width,
    med.height,
    med.aspect_ratio,
    med.codec,
    med.audio_codec,
    med.codec_profile,
    med.bit_rate,
    med.frame_rate,
    med.scan_type,
    med.hdr_format,
    med.color_space,
    med.color_primaries,
    med.thumbnail_path,
    med.type,
    med.source_type,
    med.resolution_label,
    med.quality_score,
    med.is_3d,
    med.stereo_mode,
    med.has_dash,
    med.dash_manifest_path,
    med.transcoding_status,
    med.is_extra,
    med.date_added,
    med.date_modified,
    med.created_at,
    med.updated_at
FROM tv_episodes e
JOIN media med ON e.media_id = med.id
WHERE e.media_id = ?
`

type GetTVEpisodeByMediaIDRow struct {
	MediaID           int64           `json:"media_id"`
	ShowID            int64           `json:"show_id"`
	SeasonID          int64           `json:"season_id"`
	SeasonNumber      int64           `json:"season_number"`
	EpisodeNumber     int64           `json:"episode_number"`
	AbsoluteNumber    sql.NullInt64   `json:"absolute_number"`
	DvdSeason         sql.NullInt64   `json:"dvd_season"`
	DvdEpisode        sql.NullInt64   `json:"dvd_episode"`
	EpisodeTitle      sql.NullString  `json:"episode_title"`
	OriginalTitle     sql.NullString  `json:"original_title"`
	AirDate           sql.NullTime    `json:"air_date"`
	Plot              sql.NullString  `json:"plot"`
	ContentRating     sql.NullString  `json:"content_rating"`
	MaturityRating    sql.NullInt64   `json:"maturity_rating"`
	ImdbID            sql.NullString  `json:"imdb_id"`
	TmdbID            sql.NullInt64   `json:"tmdb_id"`
	TvdbID            sql.NullInt64   `json:"tvdb_id"`
	Rating            sql.NullFloat64 `json:"rating"`
	RatingVotes       sql.NullInt64   `json:"rating_votes"`
	RuntimeMinutes    sql.NullInt64   `json:"runtime_minutes"`
	MediaID_2         int64           `json:"media_id_2"`
	LibraryID         int64           `json:"library_id"`
	Title             string          `json:"title"`
	FilePath          string          `json:"file_path"`
	FileSize          sql.NullInt64   `json:"file_size"`
	FileHash          sql.NullString  `json:"file_hash"`
	ContainerFormat   sql.NullString  `json:"container_format"`
	Duration          sql.NullFloat64 `json:"duration"`
	Width             sql.NullInt64   `json:"width"`
	Height            sql.NullInt64   `json:"height"`
	AspectRatio       sql.NullString  `json:"aspect_ratio"`
	Codec             sql.NullString  `json:"codec"`
	AudioCodec        sql.NullString  `json:"audio_codec"`
	CodecProfile      sql.NullString  `json:"codec_profile"`
	BitRate           sql.NullInt64   `json:"bit_rate"`
	FrameRate         sql.NullFloat64 `json:"frame_rate"`
	ScanType          sql.NullString  `json:"scan_type"`
	HdrFormat         sql.NullString  `json:"hdr_format"`
	ColorSpace        sql.NullString  `json:"color_space"`
	ColorPrimaries    sql.NullString  `json:"color_primaries"`
	ThumbnailPath     sql.NullString  `json:"thumbnail_path"`
	Type              string          `json:"type"`
	SourceType        sql.NullString  `json:"source_type"`
	ResolutionLabel   sql.NullString  `json:"resolution_label"`
	QualityScore      sql.NullInt64   `json:"quality_score"`
	Is3d              sql.NullInt64   `json:"is_3d"`
	StereoMode        sql.NullString  `json:"stereo_mode"`
	HasDash           sql.NullInt64   `json:"has_dash"`
	DashManifestPath  sql.NullString  `json:"dash_manifest_path"`
	TranscodingStatus sql.NullString  `json:"transcoding_status"`
	IsExtra           int64           `json:"is_extra"`
	DateAdded         sql.NullTime    `json:"date_added"`
	DateModified      sql.NullTime    `json:"date_modified"`
	CreatedAt         sql.NullTime    `json:"created_at"`
	UpdatedAt         sql.NullTime    `json:"updated_at"`
}

func (q *Queries) GetTVEpisodeByMediaID(ctx context.Context, mediaID int64) (GetTVEpisodeByMediaIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTVEpisodeByMediaID, mediaID)
	var i GetTVEpisodeByMediaIDRow
	err := row.Scan(
		&i.MediaID,
		&i.ShowID,
		&i.SeasonID,
		&i.SeasonNumber,
		&i.EpisodeNumber,
		&i.AbsoluteNumber,
		&i.DvdSeason,
		&i.DvdEpisode,
		&i.EpisodeTitle,
		&i.OriginalTitle,
		&i.AirDate,
		&i.Plot,
		&i.ContentRating,
		&i.MaturityRating,
		&i.ImdbID,
		&i.TmdbID,
		&i.TvdbID,
		&i.Rating,
		&i.RatingVotes,
		&i.RuntimeMinutes,
		&i.MediaID_2,
		&i.LibraryID,
		&i.Title,
		&i.FilePath,
		&i.FileSize,
		&i.FileHash,
		&i.ContainerFormat,
		&i.Duration,
		&i.Width,
		&i.Height,
		&i.AspectRatio,
		&i.Codec,
		&i.AudioCodec,
		&i.CodecProfile,
		&i.BitRate,
		&i.FrameRate,
		&i.ScanType,
		&i.HdrFormat,
		&i.ColorSpace,
		&i.ColorPrimaries,
		&i.ThumbnailPath,
		&i.Type,
		&i.SourceType,
		&i.ResolutionLabel,
		&i.QualityScore,
		&i.Is3d,
		&i.StereoMode,
		&i.HasDash,
		&i.DashManifestPath,
		&i.TranscodingStatus,
		&i.IsExtra,
		&i.DateAdded,
		&i.DateModified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTVEpisodeByShowSeasonEpisode = `-- name: GetTVEpisodeByShowSeasonEpisode :one
SELECT
    e.media_id, e.show_id, e.season_id, e.season_number, e.episode_number, e.absolute_number, e.dvd_season, e.dvd_episode, e.episode_title, e.original_title, e.air_date, e.plot, e.content_rating, e.maturity_rating, e.imdb_id, e.tmdb_id, e.tvdb_id, e.rating, e.rating_votes, e.runtime_minutes,
    med.id as media_id,
    med.library_id,
    med.title,
    med.file_path,
    med.file_size,
    med.file_hash,
    med.container_format,
    med.duration,
    med.width,
    med.height,
    med.aspect_ratio,
    med.codec,
    med.audio_codec,
    med.codec_profile,
    med.bit_rate,
    med.frame_rate,
    med.scan_type,
    med.hdr_format,
    med.color_space,
    med.color_primaries,
    med.thumbnail_path,
    med.type,
    med.source_type,
    med.resolution_label,
    med.quality_score,
    med.is_3d,
    med.stereo_mode,
    med.has_dash,
    med.dash_manifest_path,
    med.transcoding_status,
    med.is_extra,
    med.date_added,
    med.date_modified,
    med.created_at,
    med.updated_at
FROM tv_episodes e
JOIN media med ON e.media_id = med.id
WHERE e.show_id = ? AND e.season_number = ? AND e.episode_number = ?
LIMIT 1
`

type GetTVEpisodeByShowSeasonEpisodeParams struct {
	ShowID        int64 `json:"show_id"`
	SeasonNumber  int64 `json:"season_number"`
	EpisodeNumber int64 `json:"episode_number"`
}

type GetTVEpisodeByShowSeasonEpisodeRow struct {
	MediaID           int64           `json:"media_id"`
	ShowID            int64           `json:"show_id"`
	SeasonID          int64           `json:"season_id"`
	SeasonNumber      int64           `json:"season_number"`
	EpisodeNumber     int64           `json:"episode_number"`
	AbsoluteNumber    sql.NullInt64   `json:"absolute_number"`
	DvdSeason         sql.NullInt64   `json:"dvd_season"`
	DvdEpisode        sql.NullInt64   `json:"dvd_episode"`
	EpisodeTitle      sql.NullString  `json:"episode_title"`
	OriginalTitle     sql.NullString  `json:"original_title"`
	AirDate           sql.NullTime    `json:"air_date"`
	Plot              sql.NullString  `json:"plot"`
	ContentRating     sql.NullString  `json:"content_rating"`
	MaturityRating    sql.NullInt64   `json:"maturity_rating"`
	ImdbID            sql.NullString  `json:"imdb_id"`
	TmdbID            sql.NullInt64   `json:"tmdb_id"`
	TvdbID            sql.NullInt64   `json:"tvdb_id"`
	Rating            sql.NullFloat64 `json:"rating"`
	RatingVotes       sql.NullInt64   `json:"rating_votes"`
	RuntimeMinutes    sql.NullInt64   `json:"runtime_minutes"`
	MediaID_2         int64           `json:"media_id_2"`
	LibraryID         int64           `json:"library_id"`
	Title             string          `json:"title"`
	FilePath          string          `json:"file_path"`
	FileSize          sql.NullInt64   `json:"file_size"`
	FileHash          sql.NullString  `json:"file_hash"`
	ContainerFormat   sql.NullString  `json:"container_format"`
	Duration          sql.NullFloat64 `json:"duration"`
	Width             sql.NullInt64   `json:"width"`
	Height            sql.NullInt64   `json:"height"`
	AspectRatio       sql.NullString  `json:"aspect_ratio"`
	Codec             sql.NullString  `json:"codec"`
	AudioCodec        sql.NullString  `json:"audio_codec"`
	CodecProfile      sql.NullString  `json:"codec_profile"`
	BitRate           sql.NullInt64   `json:"bit_rate"`
	FrameRate         sql.NullFloat64 `json:"frame_rate"`
	ScanType          sql.NullString  `json:"scan_type"`
	HdrFormat         sql.NullString  `json:"hdr_format"`
	ColorSpace        sql.NullString  `json:"color_space"`
	ColorPrimaries    sql.NullString  `json:"color_primaries"`
	ThumbnailPath     sql.NullString  `json:"thumbnail_path"`
	Type              string          `json:"type"`
	SourceType        sql.NullString  `json:"source_type"`
	ResolutionLabel   sql.NullString  `json:"resolution_label"`
	QualityScore      sql.NullInt64   `json:"quality_score"`
	Is3d              sql.NullInt64   `json:"is_3d"`
	StereoMode        sql.NullString  `json:"stereo_mode"`
	HasDash           sql.NullInt64   `json:"has_dash"`
	DashManifestPath  sql.NullString  `json:"dash_manifest_path"`
	TranscodingStatus sql.NullString  `json:"transcoding_status"`
	IsExtra           int64           `json:"is_extra"`
	DateAdded         sql.NullTime    `json:"date_added"`
	DateModified      sql.NullTime    `json:"date_modified"`
	CreatedAt         sql.NullTime    `json:"created_at"`
	UpdatedAt         sql.NullTime    `json:"updated_at"`
}

func (q *Queries) GetTVEpisodeByShowSeasonEpisode(ctx context.Context, arg GetTVEpisodeByShowSeasonEpisodeParams) (GetTVEpisodeByShowSeasonEpisodeRow, error) {
	row := q.db.QueryRowContext(ctx, getTVEpisodeByShowSeasonEpisode, arg.ShowID, arg.SeasonNumber, arg.EpisodeNumber)
	var i GetTVEpisodeByShowSeasonEpisodeRow
	err := row.Scan(
		&i.MediaID,
		&i.ShowID,
		&i.SeasonID,
		&i.SeasonNumber,
		&i.EpisodeNumber,
		&i.AbsoluteNumber,
		&i.DvdSeason,
		&i.DvdEpisode,
		&i.EpisodeTitle,
		&i.OriginalTitle,
		&i.AirDate,
		&i.Plot,
		&i.ContentRating,
		&i.MaturityRating,
		&i.ImdbID,
		&i.TmdbID,
		&i.TvdbID,
		&i.Rating,
		&i.RatingVotes,
		&i.RuntimeMinutes,
		&i.MediaID_2,
		&i.LibraryID,
		&i.Title,
		&i.FilePath,
		&i.FileSize,
		&i.FileHash,
		&i.ContainerFormat,
		&i.Duration,
		&i.Width,
		&i.Height,
		&i.AspectRatio,
		&i.Codec,
		&i.AudioCodec,
		&i.CodecProfile,
		&i.BitRate,
		&i.FrameRate,
		&i.ScanType,
		&i.HdrFormat,
		&i.ColorSpace,
		&i.ColorPrimaries,
		&i.ThumbnailPath,
		&i.Type,
		&i.SourceType,
		&i.ResolutionLabel,
		&i.QualityScore,
		&i.Is3d,
		&i.StereoMode,
		&i.HasDash,
		&i.DashManifestPath,
		&i.TranscodingStatus,
		&i.IsExtra,
		&i.DateAdded,
		&i.DateModified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTVSeasonByID = `-- name: GetTVSeasonByID :one
SELECT id, show_id, season_number, name, overview, air_date, poster_path, episode_count, created_at, updated_at FROM tv_seasons
WHERE id = ?
`

func (q *Queries) GetTVSeasonByID(ctx context.Context, id int64) (TvSeason, error) {
	row := q.db.QueryRowContext(ctx, getTVSeasonByID, id)
	var i TvSeason
	err := row.Scan(
		&i.ID,
		&i.ShowID,
		&i.SeasonNumber,
		&i.Name,
		&i.Overview,
		&i.AirDate,
		&i.PosterPath,
		&i.EpisodeCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTVSeasonByShowAndNumber = `-- name: GetTVSeasonByShowAndNumber :one
SELECT id, show_id, season_number, name, overview, air_date, poster_path, episode_count, created_at, updated_at FROM tv_seasons
WHERE show_id = ? AND season_number = ?
LIMIT 1
`

type GetTVSeasonByShowAndNumberParams struct {
	ShowID       int64 `json:"show_id"`
	SeasonNumber int64 `json:"season_number"`
}

func (q *Queries) GetTVSeasonByShowAndNumber(ctx context.Context, arg GetTVSeasonByShowAndNumberParams) (TvSeason, error) {
	row := q.db.QueryRowContext(ctx, getTVSeasonByShowAndNumber, arg.ShowID, arg.SeasonNumber)
	var i TvSeason
	err := row.Scan(
		&i.ID,
		&i.ShowID,
		&i.SeasonNumber,
		&i.Name,
		&i.Overview,
		&i.AirDate,
		&i.PosterPath,
		&i.EpisodeCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTVShowByDirectory = `-- name: GetTVShowByDirectory :one
SELECT id, library_id, title, original_title, sort_title, year, first_air_date, last_air_date, genre, plot, status, content_rating, maturity_rating, network, original_language, country_of_origin, imdb_id, tmdb_id, tvdb_id, created_at, updated_at, directory, rating, rating_votes, tagline FROM tv_shows
WHERE library_id = ? AND directory = ?
LIMIT 1
`

type GetTVShowByDirectoryParams struct {
	LibraryID int64          `json:"library_id"`
	Directory sql.NullString `json:"directory"`
}

// Find a TV show by its directory path. Used to prevent duplicate shows
// when different episodes parse to different titles but share the same directory.
func (q *Queries) GetTVShowByDirectory(ctx context.Context, arg GetTVShowByDirectoryParams) (TvShow, error) {
	row := q.db.QueryRowContext(ctx, getTVShowByDirectory, arg.LibraryID, arg.Directory)
	var i TvShow
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Title,
		&i.OriginalTitle,
		&i.SortTitle,
		&i.Year,
		&i.FirstAirDate,
		&i.LastAirDate,
		&i.Genre,
		&i.Plot,
		&i.Status,
		&i.ContentRating,
		&i.MaturityRating,
		&i.Network,
		&i.OriginalLanguage,
		&i.CountryOfOrigin,
		&i.ImdbID,
		&i.TmdbID,
		&i.TvdbID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Directory,
		&i.Rating,
		&i.RatingVotes,
		&i.Tagline,
	)
	return i, err
}

const getTVShowByID = `-- name: GetTVShowByID :one
SELECT id, library_id, title, original_title, sort_title, year, first_air_date, last_air_date, genre, plot, status, content_rating, maturity_rating, network, original_language, country_of_origin, imdb_id, tmdb_id, tvdb_id, created_at, updated_at, directory, rating, rating_votes, tagline FROM tv_shows
WHERE id = ?
`

func (q *Queries) GetTVShowByID(ctx context.Context, id int64) (TvShow, error) {
	row := q.db.QueryRowContext(ctx, getTVShowByID, id)
	var i TvShow
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Title,
		&i.OriginalTitle,
		&i.SortTitle,
		&i.Year,
		&i.FirstAirDate,
		&i.LastAirDate,
		&i.Genre,
		&i.Plot,
		&i.Status,
		&i.ContentRating,
		&i.MaturityRating,
		&i.Network,
		&i.OriginalLanguage,
		&i.CountryOfOrigin,
		&i.ImdbID,
		&i.TmdbID,
		&i.TvdbID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Directory,
		&i.Rating,
		&i.RatingVotes,
		&i.Tagline,
	)
	return i, err
}

const getTVShowByTitle = `-- name: GetTVShowByTitle :one
SELECT id, library_id, title, original_title, sort_title, year, first_air_date, last_air_date, genre, plot, status, content_rating, maturity_rating, network, original_language, country_of_origin, imdb_id, tmdb_id, tvdb_id, created_at, updated_at, directory, rating, rating_votes, tagline FROM tv_shows
WHERE library_id = ?1 AND LOWER(title) = LOWER(?2)
LIMIT 1
`

type GetTVShowByTitleParams struct {
	LibraryID int64  `json:"library_id"`
	Title     string `json:"title"`
}

func (q *Queries) GetTVShowByTitle(ctx context.Context, arg GetTVShowByTitleParams) (TvShow, error) {
	row := q.db.QueryRowContext(ctx, getTVShowByTitle, arg.LibraryID, arg.Title)
	var i TvShow
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Title,
		&i.OriginalTitle,
		&i.SortTitle,
		&i.Year,
		&i.FirstAirDate,
		&i.LastAirDate,
		&i.Genre,
		&i.Plot,
		&i.Status,
		&i.ContentRating,
		&i.MaturityRating,
		&i.Network,
		&i.OriginalLanguage,
		&i.CountryOfOrigin,
		&i.ImdbID,
		&i.TmdbID,
		&i.TvdbID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Directory,
		&i.Rating,
		&i.RatingVotes,
		&i.Tagline,
	)
	return i, err
}

const getTVShowsWithCountsByLibrary = `-- name: GetTVShowsWithCountsByLibrary :many

SELECT
    s.id,
    s.library_id,
    s.title,
    s.year,
    s.genre,
    s.plot,
    s.content_rating,
    s.imdb_id,
    s.tmdb_id,
    COUNT(DISTINCT e.season_number) as season_count,
    COUNT(*) as episode_count
FROM tv_shows s
LEFT JOIN tv_episodes e ON s.id = e.show_id
LEFT JOIN media med ON e.media_id = med.id
WHERE s.library_id = ?
  AND (med.is_extra = 0 OR med.is_extra IS NULL)
GROUP BY s.id, s.library_id, s.title, s.year, s.genre, s.plot, s.content_rating, s.imdb_id, s.tmdb_id
ORDER BY COALESCE(NULLIF(s.sort_title, ''), s.title) COLLATE NOCASE
`

type GetTVShowsWithCountsByLibraryRow struct {
	ID            int64          `json:"id"`
	LibraryID     int64          `json:"library_id"`
	Title         string         `json:"title"`
	Year          sql.NullInt64  `json:"year"`
	Genre         sql.NullString `json:"genre"`
	Plot          sql.NullString `json:"plot"`
	ContentRating sql.NullString `json:"content_rating"`
	ImdbID        sql.NullString `json:"imdb_id"`
	TmdbID        sql.NullInt64  `json:"tmdb_id"`
	SeasonCount   int64          `json:"season_count"`
	EpisodeCount  int64          `json:"episode_count"`
}

// ============================================================================
// Aggregation Queries for API
// ============================================================================
func (q *Queries) GetTVShowsWithCountsByLibrary(ctx context.Context, libraryID int64) ([]GetTVShowsWithCountsByLibraryRow, error) {
	rows, err := q.db.QueryContext(ctx, getTVShowsWithCountsByLibrary, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTVShowsWithCountsByLibraryRow{}
	for rows.Next() {
		var i GetTVShowsWithCountsByLibraryRow
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Title,
			&i.Year,
			&i.Genre,
			&i.Plot,
			&i.ContentRating,
			&i.ImdbID,
			&i.TmdbID,
			&i.SeasonCount,
			&i.EpisodeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTVShowsWithCountsByLibraryPaginated = `-- name: GetTVShowsWithCountsByLibraryPaginated :many
SELECT
    s.id,
    s.library_id,
    s.title,
    s.year,
    s.genre,
    s.plot,
    s.content_rating,
    s.imdb_id,
    s.tmdb_id,
    s.created_at,
    COUNT(DISTINCT e.season_number) as season_count,
    COUNT(*) as episode_count
FROM tv_shows s
LEFT JOIN tv_episodes e ON s.id = e.show_id
LEFT JOIN media med ON e.media_id = med.id
WHERE s.library_id = ?
  AND (med.is_extra = 0 OR med.is_extra IS NULL)
GROUP BY s.id, s.library_id, s.title, s.year, s.genre, s.plot, s.content_rating, s.imdb_id, s.tmdb_id, s.created_at
ORDER BY COALESCE(NULLIF(s.sort_title, ''), s.title) COLLATE NOCASE ASC
LIMIT ? OFFSET ?
`

type GetTVShowsWithCountsByLibraryPaginatedParams struct {
	LibraryID int64 `json:"library_id"`
	Limit     int64 `json:"limit"`
	Offset    int64 `json:"offset"`
}

type GetTVShowsWithCountsByLibraryPaginatedRow struct {
	ID            int64          `json:"id"`
	LibraryID     int64          `json:"library_id"`
	Title         string         `json:"title"`
	Year          sql.NullInt64  `json:"year"`
	Genre         sql.NullString `json:"genre"`
	Plot          sql.NullString `json:"plot"`
	ContentRating sql.NullString `json:"content_rating"`
	ImdbID        sql.NullString `json:"imdb_id"`
	TmdbID        sql.NullInt64  `json:"tmdb_id"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	SeasonCount   int64          `json:"season_count"`
	EpisodeCount  int64          `json:"episode_count"`
}

func (q *Queries) GetTVShowsWithCountsByLibraryPaginated(ctx context.Context, arg GetTVShowsWithCountsByLibraryPaginatedParams) ([]GetTVShowsWithCountsByLibraryPaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, getTVShowsWithCountsByLibraryPaginated, arg.LibraryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTVShowsWithCountsByLibraryPaginatedRow{}
	for rows.Next() {
		var i GetTVShowsWithCountsByLibraryPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Title,
			&i.Year,
			&i.Genre,
			&i.Plot,
			&i.ContentRating,
			&i.ImdbID,
			&i.TmdbID,
			&i.CreatedAt,
			&i.SeasonCount,
			&i.EpisodeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTVShowsWithCountsByLibraryPaginatedDesc = `-- name: GetTVShowsWithCountsByLibraryPaginatedDesc :many
SELECT
    s.id,
    s.library_id,
    s.title,
    s.year,
    s.genre,
    s.plot,
    s.content_rating,
    s.imdb_id,
    s.tmdb_id,
    s.created_at,
    COUNT(DISTINCT e.season_number) as season_count,
    COUNT(*) as episode_count
FROM tv_shows s
LEFT JOIN tv_episodes e ON s.id = e.show_id
LEFT JOIN media med ON e.media_id = med.id
WHERE s.library_id = ?
  AND (med.is_extra = 0 OR med.is_extra IS NULL)
GROUP BY s.id, s.library_id, s.title, s.year, s.genre, s.plot, s.content_rating, s.imdb_id, s.tmdb_id, s.created_at
ORDER BY COALESCE(NULLIF(s.sort_title, ''), s.title) COLLATE NOCASE DESC
LIMIT ? OFFSET ?
`

type GetTVShowsWithCountsByLibraryPaginatedDescParams struct {
	LibraryID int64 `json:"library_id"`
	Limit     int64 `json:"limit"`
	Offset    int64 `json:"offset"`
}

type GetTVShowsWithCountsByLibraryPaginatedDescRow struct {
	ID            int64          `json:"id"`
	LibraryID     int64          `json:"library_id"`
	Title         string         `json:"title"`
	Year          sql.NullInt64  `json:"year"`
	Genre         sql.NullString `json:"genre"`
	Plot          sql.NullString `json:"plot"`
	ContentRating sql.NullString `json:"content_rating"`
	ImdbID        sql.NullString `json:"imdb_id"`
	TmdbID        sql.NullInt64  `json:"tmdb_id"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	SeasonCount   int64          `json:"season_count"`
	EpisodeCount  int64          `json:"episode_count"`
}

func (q *Queries) GetTVShowsWithCountsByLibraryPaginatedDesc(ctx context.Context, arg GetTVShowsWithCountsByLibraryPaginatedDescParams) ([]GetTVShowsWithCountsByLibraryPaginatedDescRow, error) {
	rows, err := q.db.QueryContext(ctx, getTVShowsWithCountsByLibraryPaginatedDesc, arg.LibraryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTVShowsWithCountsByLibraryPaginatedDescRow{}
	for rows.Next() {
		var i GetTVShowsWithCountsByLibraryPaginatedDescRow
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Title,
			&i.Year,
			&i.Genre,
			&i.Plot,
			&i.ContentRating,
			&i.ImdbID,
			&i.TmdbID,
			&i.CreatedAt,
			&i.SeasonCount,
			&i.EpisodeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementSeasonEpisodeCount = `-- name: IncrementSeasonEpisodeCount :exec
UPDATE tv_seasons
SET episode_count = episode_count + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) IncrementSeasonEpisodeCount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, incrementSeasonEpisodeCount, id)
	return err
}

const listRecentlyAddedTVShows = `-- name: ListRecentlyAddedTVShows :many
SELECT
    s.id,
    s.library_id,
    s.title,
    s.original_title,
    s.sort_title,
    s.year,
    s.genre,
    s.plot,
    s.content_rating,
    s.imdb_id,
    s.tmdb_id,
    s.created_at,
    MAX(med.created_at) as latest_episode_added
FROM tv_shows s
JOIN tv_episodes e ON s.id = e.show_id
JOIN media med ON e.media_id = med.id
WHERE med.is_extra = 0
GROUP BY s.id
ORDER BY latest_episode_added DESC
LIMIT ?
`

type ListRecentlyAddedTVShowsRow struct {
	ID                 int64          `json:"id"`
	LibraryID          int64          `json:"library_id"`
	Title              string         `json:"title"`
	OriginalTitle      sql.NullString `json:"original_title"`
	SortTitle          sql.NullString `json:"sort_title"`
	Year               sql.NullInt64  `json:"year"`
	Genre              sql.NullString `json:"genre"`
	Plot               sql.NullString `json:"plot"`
	ContentRating      sql.NullString `json:"content_rating"`
	ImdbID             sql.NullString `json:"imdb_id"`
	TmdbID             sql.NullInt64  `json:"tmdb_id"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	LatestEpisodeAdded interface{}    `json:"latest_episode_added"`
}

// Returns recently added TV shows across all libraries, ordered by newest episode date
func (q *Queries) ListRecentlyAddedTVShows(ctx context.Context, limit int64) ([]ListRecentlyAddedTVShowsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentlyAddedTVShows, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentlyAddedTVShowsRow{}
	for rows.Next() {
		var i ListRecentlyAddedTVShowsRow
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Title,
			&i.OriginalTitle,
			&i.SortTitle,
			&i.Year,
			&i.Genre,
			&i.Plot,
			&i.ContentRating,
			&i.ImdbID,
			&i.TmdbID,
			&i.CreatedAt,
			&i.LatestEpisodeAdded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTVEpisodesByLibrary = `-- name: ListTVEpisodesByLibrary :many
SELECT
    e.media_id, e.show_id, e.season_id, e.season_number, e.episode_number, e.absolute_number, e.dvd_season, e.dvd_episode, e.episode_title, e.original_title, e.air_date, e.plot, e.content_rating, e.maturity_rating, e.imdb_id, e.tmdb_id, e.tvdb_id, e.rating, e.rating_votes, e.runtime_minutes,
    med.id as media_id,
    med.library_id,
    med.title,
    med.file_path,
    med.file_size,
    med.file_hash,
    med.container_format,
    med.duration,
    med.width,
    med.height,
    med.aspect_ratio,
    med.codec,
    med.audio_codec,
    med.codec_profile,
    med.bit_rate,
    med.frame_rate,
    med.scan_type,
    med.hdr_format,
    med.color_space,
    med.color_primaries,
    med.thumbnail_path,
    med.type,
    med.source_type,
    med.resolution_label,
    med.quality_score,
    med.is_3d,
    med.stereo_mode,
    med.has_dash,
    med.dash_manifest_path,
    med.transcoding_status,
    med.is_extra,
    med.date_added,
    med.date_modified,
    med.created_at,
    med.updated_at
FROM tv_episodes e
JOIN media med ON e.media_id = med.id
WHERE med.library_id = ?
  AND med.is_extra = 0
ORDER BY e.show_id, e.season_number, e.episode_number
`

type ListTVEpisodesByLibraryRow struct {
	MediaID           int64           `json:"media_id"`
	ShowID            int64           `json:"show_id"`
	SeasonID          int64           `json:"season_id"`
	SeasonNumber      int64           `json:"season_number"`
	EpisodeNumber     int64           `json:"episode_number"`
	AbsoluteNumber    sql.NullInt64   `json:"absolute_number"`
	DvdSeason         sql.NullInt64   `json:"dvd_season"`
	DvdEpisode        sql.NullInt64   `json:"dvd_episode"`
	EpisodeTitle      sql.NullString  `json:"episode_title"`
	OriginalTitle     sql.NullString  `json:"original_title"`
	AirDate           sql.NullTime    `json:"air_date"`
	Plot              sql.NullString  `json:"plot"`
	ContentRating     sql.NullString  `json:"content_rating"`
	MaturityRating    sql.NullInt64   `json:"maturity_rating"`
	ImdbID            sql.NullString  `json:"imdb_id"`
	TmdbID            sql.NullInt64   `json:"tmdb_id"`
	TvdbID            sql.NullInt64   `json:"tvdb_id"`
	Rating            sql.NullFloat64 `json:"rating"`
	RatingVotes       sql.NullInt64   `json:"rating_votes"`
	RuntimeMinutes    sql.NullInt64   `json:"runtime_minutes"`
	MediaID_2         int64           `json:"media_id_2"`
	LibraryID         int64           `json:"library_id"`
	Title             string          `json:"title"`
	FilePath          string          `json:"file_path"`
	FileSize          sql.NullInt64   `json:"file_size"`
	FileHash          sql.NullString  `json:"file_hash"`
	ContainerFormat   sql.NullString  `json:"container_format"`
	Duration          sql.NullFloat64 `json:"duration"`
	Width             sql.NullInt64   `json:"width"`
	Height            sql.NullInt64   `json:"height"`
	AspectRatio       sql.NullString  `json:"aspect_ratio"`
	Codec             sql.NullString  `json:"codec"`
	AudioCodec        sql.NullString  `json:"audio_codec"`
	CodecProfile      sql.NullString  `json:"codec_profile"`
	BitRate           sql.NullInt64   `json:"bit_rate"`
	FrameRate         sql.NullFloat64 `json:"frame_rate"`
	ScanType          sql.NullString  `json:"scan_type"`
	HdrFormat         sql.NullString  `json:"hdr_format"`
	ColorSpace        sql.NullString  `json:"color_space"`
	ColorPrimaries    sql.NullString  `json:"color_primaries"`
	ThumbnailPath     sql.NullString  `json:"thumbnail_path"`
	Type              string          `json:"type"`
	SourceType        sql.NullString  `json:"source_type"`
	ResolutionLabel   sql.NullString  `json:"resolution_label"`
	QualityScore      sql.NullInt64   `json:"quality_score"`
	Is3d              sql.NullInt64   `json:"is_3d"`
	StereoMode        sql.NullString  `json:"stereo_mode"`
	HasDash           sql.NullInt64   `json:"has_dash"`
	DashManifestPath  sql.NullString  `json:"dash_manifest_path"`
	TranscodingStatus sql.NullString  `json:"transcoding_status"`
	IsExtra           int64           `json:"is_extra"`
	DateAdded         sql.NullTime    `json:"date_added"`
	DateModified      sql.NullTime    `json:"date_modified"`
	CreatedAt         sql.NullTime    `json:"created_at"`
	UpdatedAt         sql.NullTime    `json:"updated_at"`
}

func (q *Queries) ListTVEpisodesByLibrary(ctx context.Context, libraryID int64) ([]ListTVEpisodesByLibraryRow, error) {
	rows, err := q.db.QueryContext(ctx, listTVEpisodesByLibrary, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTVEpisodesByLibraryRow{}
	for rows.Next() {
		var i ListTVEpisodesByLibraryRow
		if err := rows.Scan(
			&i.MediaID,
			&i.ShowID,
			&i.SeasonID,
			&i.SeasonNumber,
			&i.EpisodeNumber,
			&i.AbsoluteNumber,
			&i.DvdSeason,
			&i.DvdEpisode,
			&i.EpisodeTitle,
			&i.OriginalTitle,
			&i.AirDate,
			&i.Plot,
			&i.ContentRating,
			&i.MaturityRating,
			&i.ImdbID,
			&i.TmdbID,
			&i.TvdbID,
			&i.Rating,
			&i.RatingVotes,
			&i.RuntimeMinutes,
			&i.MediaID_2,
			&i.LibraryID,
			&i.Title,
			&i.FilePath,
			&i.FileSize,
			&i.FileHash,
			&i.ContainerFormat,
			&i.Duration,
			&i.Width,
			&i.Height,
			&i.AspectRatio,
			&i.Codec,
			&i.AudioCodec,
			&i.CodecProfile,
			&i.BitRate,
			&i.FrameRate,
			&i.ScanType,
			&i.HdrFormat,
			&i.ColorSpace,
			&i.ColorPrimaries,
			&i.ThumbnailPath,
			&i.Type,
			&i.SourceType,
			&i.ResolutionLabel,
			&i.QualityScore,
			&i.Is3d,
			&i.StereoMode,
			&i.HasDash,
			&i.DashManifestPath,
			&i.TranscodingStatus,
			&i.IsExtra,
			&i.DateAdded,
			&i.DateModified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTVEpisodesBySeason = `-- name: ListTVEpisodesBySeason :many
SELECT
    e.media_id, e.show_id, e.season_id, e.season_number, e.episode_number, e.absolute_number, e.dvd_season, e.dvd_episode, e.episode_title, e.original_title, e.air_date, e.plot, e.content_rating, e.maturity_rating, e.imdb_id, e.tmdb_id, e.tvdb_id, e.rating, e.rating_votes, e.runtime_minutes,
    med.id as media_id,
    med.library_id,
    med.title,
    med.file_path,
    med.file_size,
    med.file_hash,
    med.container_format,
    med.duration,
    med.width,
    med.height,
    med.aspect_ratio,
    med.codec,
    med.audio_codec,
    med.codec_profile,
    med.bit_rate,
    med.frame_rate,
    med.scan_type,
    med.hdr_format,
    med.color_space,
    med.color_primaries,
    med.thumbnail_path,
    med.type,
    med.source_type,
    med.resolution_label,
    med.quality_score,
    med.is_3d,
    med.stereo_mode,
    med.has_dash,
    med.dash_manifest_path,
    med.transcoding_status,
    med.is_extra,
    med.date_added,
    med.date_modified,
    med.created_at,
    med.updated_at
FROM tv_episodes e
JOIN media med ON e.media_id = med.id
WHERE e.season_id = ?
  AND med.is_extra = 0
ORDER BY e.episode_number
`

type ListTVEpisodesBySeasonRow struct {
	MediaID           int64           `json:"media_id"`
	ShowID            int64           `json:"show_id"`
	SeasonID          int64           `json:"season_id"`
	SeasonNumber      int64           `json:"season_number"`
	EpisodeNumber     int64           `json:"episode_number"`
	AbsoluteNumber    sql.NullInt64   `json:"absolute_number"`
	DvdSeason         sql.NullInt64   `json:"dvd_season"`
	DvdEpisode        sql.NullInt64   `json:"dvd_episode"`
	EpisodeTitle      sql.NullString  `json:"episode_title"`
	OriginalTitle     sql.NullString  `json:"original_title"`
	AirDate           sql.NullTime    `json:"air_date"`
	Plot              sql.NullString  `json:"plot"`
	ContentRating     sql.NullString  `json:"content_rating"`
	MaturityRating    sql.NullInt64   `json:"maturity_rating"`
	ImdbID            sql.NullString  `json:"imdb_id"`
	TmdbID            sql.NullInt64   `json:"tmdb_id"`
	TvdbID            sql.NullInt64   `json:"tvdb_id"`
	Rating            sql.NullFloat64 `json:"rating"`
	RatingVotes       sql.NullInt64   `json:"rating_votes"`
	RuntimeMinutes    sql.NullInt64   `json:"runtime_minutes"`
	MediaID_2         int64           `json:"media_id_2"`
	LibraryID         int64           `json:"library_id"`
	Title             string          `json:"title"`
	FilePath          string          `json:"file_path"`
	FileSize          sql.NullInt64   `json:"file_size"`
	FileHash          sql.NullString  `json:"file_hash"`
	ContainerFormat   sql.NullString  `json:"container_format"`
	Duration          sql.NullFloat64 `json:"duration"`
	Width             sql.NullInt64   `json:"width"`
	Height            sql.NullInt64   `json:"height"`
	AspectRatio       sql.NullString  `json:"aspect_ratio"`
	Codec             sql.NullString  `json:"codec"`
	AudioCodec        sql.NullString  `json:"audio_codec"`
	CodecProfile      sql.NullString  `json:"codec_profile"`
	BitRate           sql.NullInt64   `json:"bit_rate"`
	FrameRate         sql.NullFloat64 `json:"frame_rate"`
	ScanType          sql.NullString  `json:"scan_type"`
	HdrFormat         sql.NullString  `json:"hdr_format"`
	ColorSpace        sql.NullString  `json:"color_space"`
	ColorPrimaries    sql.NullString  `json:"color_primaries"`
	ThumbnailPath     sql.NullString  `json:"thumbnail_path"`
	Type              string          `json:"type"`
	SourceType        sql.NullString  `json:"source_type"`
	ResolutionLabel   sql.NullString  `json:"resolution_label"`
	QualityScore      sql.NullInt64   `json:"quality_score"`
	Is3d              sql.NullInt64   `json:"is_3d"`
	StereoMode        sql.NullString  `json:"stereo_mode"`
	HasDash           sql.NullInt64   `json:"has_dash"`
	DashManifestPath  sql.NullString  `json:"dash_manifest_path"`
	TranscodingStatus sql.NullString  `json:"transcoding_status"`
	IsExtra           int64           `json:"is_extra"`
	DateAdded         sql.NullTime    `json:"date_added"`
	DateModified      sql.NullTime    `json:"date_modified"`
	CreatedAt         sql.NullTime    `json:"created_at"`
	UpdatedAt         sql.NullTime    `json:"updated_at"`
}

func (q *Queries) ListTVEpisodesBySeason(ctx context.Context, seasonID int64) ([]ListTVEpisodesBySeasonRow, error) {
	rows, err := q.db.QueryContext(ctx, listTVEpisodesBySeason, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTVEpisodesBySeasonRow{}
	for rows.Next() {
		var i ListTVEpisodesBySeasonRow
		if err := rows.Scan(
			&i.MediaID,
			&i.ShowID,
			&i.SeasonID,
			&i.SeasonNumber,
			&i.EpisodeNumber,
			&i.AbsoluteNumber,
			&i.DvdSeason,
			&i.DvdEpisode,
			&i.EpisodeTitle,
			&i.OriginalTitle,
			&i.AirDate,
			&i.Plot,
			&i.ContentRating,
			&i.MaturityRating,
			&i.ImdbID,
			&i.TmdbID,
			&i.TvdbID,
			&i.Rating,
			&i.RatingVotes,
			&i.RuntimeMinutes,
			&i.MediaID_2,
			&i.LibraryID,
			&i.Title,
			&i.FilePath,
			&i.FileSize,
			&i.FileHash,
			&i.ContainerFormat,
			&i.Duration,
			&i.Width,
			&i.Height,
			&i.AspectRatio,
			&i.Codec,
			&i.AudioCodec,
			&i.CodecProfile,
			&i.BitRate,
			&i.FrameRate,
			&i.ScanType,
			&i.HdrFormat,
			&i.ColorSpace,
			&i.ColorPrimaries,
			&i.ThumbnailPath,
			&i.Type,
			&i.SourceType,
			&i.ResolutionLabel,
			&i.QualityScore,
			&i.Is3d,
			&i.StereoMode,
			&i.HasDash,
			&i.DashManifestPath,
			&i.TranscodingStatus,
			&i.IsExtra,
			&i.DateAdded,
			&i.DateModified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTVEpisodesByShow = `-- name: ListTVEpisodesByShow :many
SELECT
    e.media_id, e.show_id, e.season_id, e.season_number, e.episode_number, e.absolute_number, e.dvd_season, e.dvd_episode, e.episode_title, e.original_title, e.air_date, e.plot, e.content_rating, e.maturity_rating, e.imdb_id, e.tmdb_id, e.tvdb_id, e.rating, e.rating_votes, e.runtime_minutes,
    med.id as media_id,
    med.library_id,
    med.title,
    med.file_path,
    med.file_size,
    med.file_hash,
    med.container_format,
    med.duration,
    med.width,
    med.height,
    med.aspect_ratio,
    med.codec,
    med.audio_codec,
    med.codec_profile,
    med.bit_rate,
    med.frame_rate,
    med.scan_type,
    med.hdr_format,
    med.color_space,
    med.color_primaries,
    med.thumbnail_path,
    med.type,
    med.source_type,
    med.resolution_label,
    med.quality_score,
    med.is_3d,
    med.stereo_mode,
    med.has_dash,
    med.dash_manifest_path,
    med.transcoding_status,
    med.is_extra,
    med.date_added,
    med.date_modified,
    med.created_at,
    med.updated_at
FROM tv_episodes e
JOIN media med ON e.media_id = med.id
WHERE e.show_id = ?
  AND med.is_extra = 0
ORDER BY e.season_number, e.episode_number
`

type ListTVEpisodesByShowRow struct {
	MediaID           int64           `json:"media_id"`
	ShowID            int64           `json:"show_id"`
	SeasonID          int64           `json:"season_id"`
	SeasonNumber      int64           `json:"season_number"`
	EpisodeNumber     int64           `json:"episode_number"`
	AbsoluteNumber    sql.NullInt64   `json:"absolute_number"`
	DvdSeason         sql.NullInt64   `json:"dvd_season"`
	DvdEpisode        sql.NullInt64   `json:"dvd_episode"`
	EpisodeTitle      sql.NullString  `json:"episode_title"`
	OriginalTitle     sql.NullString  `json:"original_title"`
	AirDate           sql.NullTime    `json:"air_date"`
	Plot              sql.NullString  `json:"plot"`
	ContentRating     sql.NullString  `json:"content_rating"`
	MaturityRating    sql.NullInt64   `json:"maturity_rating"`
	ImdbID            sql.NullString  `json:"imdb_id"`
	TmdbID            sql.NullInt64   `json:"tmdb_id"`
	TvdbID            sql.NullInt64   `json:"tvdb_id"`
	Rating            sql.NullFloat64 `json:"rating"`
	RatingVotes       sql.NullInt64   `json:"rating_votes"`
	RuntimeMinutes    sql.NullInt64   `json:"runtime_minutes"`
	MediaID_2         int64           `json:"media_id_2"`
	LibraryID         int64           `json:"library_id"`
	Title             string          `json:"title"`
	FilePath          string          `json:"file_path"`
	FileSize          sql.NullInt64   `json:"file_size"`
	FileHash          sql.NullString  `json:"file_hash"`
	ContainerFormat   sql.NullString  `json:"container_format"`
	Duration          sql.NullFloat64 `json:"duration"`
	Width             sql.NullInt64   `json:"width"`
	Height            sql.NullInt64   `json:"height"`
	AspectRatio       sql.NullString  `json:"aspect_ratio"`
	Codec             sql.NullString  `json:"codec"`
	AudioCodec        sql.NullString  `json:"audio_codec"`
	CodecProfile      sql.NullString  `json:"codec_profile"`
	BitRate           sql.NullInt64   `json:"bit_rate"`
	FrameRate         sql.NullFloat64 `json:"frame_rate"`
	ScanType          sql.NullString  `json:"scan_type"`
	HdrFormat         sql.NullString  `json:"hdr_format"`
	ColorSpace        sql.NullString  `json:"color_space"`
	ColorPrimaries    sql.NullString  `json:"color_primaries"`
	ThumbnailPath     sql.NullString  `json:"thumbnail_path"`
	Type              string          `json:"type"`
	SourceType        sql.NullString  `json:"source_type"`
	ResolutionLabel   sql.NullString  `json:"resolution_label"`
	QualityScore      sql.NullInt64   `json:"quality_score"`
	Is3d              sql.NullInt64   `json:"is_3d"`
	StereoMode        sql.NullString  `json:"stereo_mode"`
	HasDash           sql.NullInt64   `json:"has_dash"`
	DashManifestPath  sql.NullString  `json:"dash_manifest_path"`
	TranscodingStatus sql.NullString  `json:"transcoding_status"`
	IsExtra           int64           `json:"is_extra"`
	DateAdded         sql.NullTime    `json:"date_added"`
	DateModified      sql.NullTime    `json:"date_modified"`
	CreatedAt         sql.NullTime    `json:"created_at"`
	UpdatedAt         sql.NullTime    `json:"updated_at"`
}

func (q *Queries) ListTVEpisodesByShow(ctx context.Context, showID int64) ([]ListTVEpisodesByShowRow, error) {
	rows, err := q.db.QueryContext(ctx, listTVEpisodesByShow, showID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTVEpisodesByShowRow{}
	for rows.Next() {
		var i ListTVEpisodesByShowRow
		if err := rows.Scan(
			&i.MediaID,
			&i.ShowID,
			&i.SeasonID,
			&i.SeasonNumber,
			&i.EpisodeNumber,
			&i.AbsoluteNumber,
			&i.DvdSeason,
			&i.DvdEpisode,
			&i.EpisodeTitle,
			&i.OriginalTitle,
			&i.AirDate,
			&i.Plot,
			&i.ContentRating,
			&i.MaturityRating,
			&i.ImdbID,
			&i.TmdbID,
			&i.TvdbID,
			&i.Rating,
			&i.RatingVotes,
			&i.RuntimeMinutes,
			&i.MediaID_2,
			&i.LibraryID,
			&i.Title,
			&i.FilePath,
			&i.FileSize,
			&i.FileHash,
			&i.ContainerFormat,
			&i.Duration,
			&i.Width,
			&i.Height,
			&i.AspectRatio,
			&i.Codec,
			&i.AudioCodec,
			&i.CodecProfile,
			&i.BitRate,
			&i.FrameRate,
			&i.ScanType,
			&i.HdrFormat,
			&i.ColorSpace,
			&i.ColorPrimaries,
			&i.ThumbnailPath,
			&i.Type,
			&i.SourceType,
			&i.ResolutionLabel,
			&i.QualityScore,
			&i.Is3d,
			&i.StereoMode,
			&i.HasDash,
			&i.DashManifestPath,
			&i.TranscodingStatus,
			&i.IsExtra,
			&i.DateAdded,
			&i.DateModified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTVSeasonsByShow = `-- name: ListTVSeasonsByShow :many
SELECT id, show_id, season_number, name, overview, air_date, poster_path, episode_count, created_at, updated_at FROM tv_seasons
WHERE show_id = ?
ORDER BY season_number
`

func (q *Queries) ListTVSeasonsByShow(ctx context.Context, showID int64) ([]TvSeason, error) {
	rows, err := q.db.QueryContext(ctx, listTVSeasonsByShow, showID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TvSeason{}
	for rows.Next() {
		var i TvSeason
		if err := rows.Scan(
			&i.ID,
			&i.ShowID,
			&i.SeasonNumber,
			&i.Name,
			&i.Overview,
			&i.AirDate,
			&i.PosterPath,
			&i.EpisodeCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTVShowIDsByLibraryPaginated = `-- name: ListTVShowIDsByLibraryPaginated :many
SELECT id
FROM tv_shows
WHERE library_id = ?
ORDER BY COALESCE(NULLIF(sort_title, ''), title) COLLATE NOCASE ASC
LIMIT ? OFFSET ?
`

type ListTVShowIDsByLibraryPaginatedParams struct {
	LibraryID int64 `json:"library_id"`
	Limit     int64 `json:"limit"`
	Offset    int64 `json:"offset"`
}

func (q *Queries) ListTVShowIDsByLibraryPaginated(ctx context.Context, arg ListTVShowIDsByLibraryPaginatedParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listTVShowIDsByLibraryPaginated, arg.LibraryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTVShowIDsByLibraryPaginatedDesc = `-- name: ListTVShowIDsByLibraryPaginatedDesc :many
SELECT id
FROM tv_shows
WHERE library_id = ?
ORDER BY COALESCE(NULLIF(sort_title, ''), title) COLLATE NOCASE DESC
LIMIT ? OFFSET ?
`

type ListTVShowIDsByLibraryPaginatedDescParams struct {
	LibraryID int64 `json:"library_id"`
	Limit     int64 `json:"limit"`
	Offset    int64 `json:"offset"`
}

func (q *Queries) ListTVShowIDsByLibraryPaginatedDesc(ctx context.Context, arg ListTVShowIDsByLibraryPaginatedDescParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listTVShowIDsByLibraryPaginatedDesc, arg.LibraryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTVShowsByGenre = `-- name: ListTVShowsByGenre :many
SELECT
    s.id, s.library_id, s.title, s.original_title, s.sort_title, s.year, s.first_air_date, s.last_air_date, s.genre, s.plot, s.status, s.content_rating, s.maturity_rating, s.network, s.original_language, s.country_of_origin, s.imdb_id, s.tmdb_id, s.tvdb_id, s.created_at, s.updated_at, s.directory, s.rating, s.rating_votes, s.tagline
FROM tv_shows s
WHERE (s.library_id = ?1 OR ?1 = 0)
  AND s.genre LIKE '%' || ?2 || '%'
  AND s.id NOT IN (/*SLICE:exclude_ids*/?)
ORDER BY COALESCE(NULLIF(s.sort_title, ''), s.title) COLLATE NOCASE
LIMIT ?4
`

type ListTVShowsByGenreParams struct {
	LibraryID  int64          `json:"library_id"`
	Genre      sql.NullString `json:"genre"`
	ExcludeIds []int64        `json:"exclude_ids"`
	Limit      int64          `json:"limit"`
}

// Lists TV shows matching a genre pattern with optional library filter and exclusion list.
// library_id: 0 means all libraries
// genre: genre pattern to match (will be wrapped in % for LIKE)
// exclude_ids: array of show IDs to exclude
// limit: maximum number of results
func (q *Queries) ListTVShowsByGenre(ctx context.Context, arg ListTVShowsByGenreParams) ([]TvShow, error) {
	query := listTVShowsByGenre
	var queryParams []interface{}
	queryParams = append(queryParams, arg.LibraryID)
	queryParams = append(queryParams, arg.Genre)
	if len(arg.ExcludeIds) > 0 {
		for _, v := range arg.ExcludeIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:exclude_ids*/?", strings.Repeat(",?", len(arg.ExcludeIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:exclude_ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Limit)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TvShow{}
	for rows.Next() {
		var i TvShow
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Title,
			&i.OriginalTitle,
			&i.SortTitle,
			&i.Year,
			&i.FirstAirDate,
			&i.LastAirDate,
			&i.Genre,
			&i.Plot,
			&i.Status,
			&i.ContentRating,
			&i.MaturityRating,
			&i.Network,
			&i.OriginalLanguage,
			&i.CountryOfOrigin,
			&i.ImdbID,
			&i.TmdbID,
			&i.TvdbID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Directory,
			&i.Rating,
			&i.RatingVotes,
			&i.Tagline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTVShowsByLibrary = `-- name: ListTVShowsByLibrary :many
SELECT id, library_id, title, original_title, sort_title, year, first_air_date, last_air_date, genre, plot, status, content_rating, maturity_rating, network, original_language, country_of_origin, imdb_id, tmdb_id, tvdb_id, created_at, updated_at, directory, rating, rating_votes, tagline FROM tv_shows
WHERE library_id = ?
ORDER BY COALESCE(NULLIF(sort_title, ''), title) COLLATE NOCASE
`

func (q *Queries) ListTVShowsByLibrary(ctx context.Context, libraryID int64) ([]TvShow, error) {
	rows, err := q.db.QueryContext(ctx, listTVShowsByLibrary, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TvShow{}
	for rows.Next() {
		var i TvShow
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Title,
			&i.OriginalTitle,
			&i.SortTitle,
			&i.Year,
			&i.FirstAirDate,
			&i.LastAirDate,
			&i.Genre,
			&i.Plot,
			&i.Status,
			&i.ContentRating,
			&i.MaturityRating,
			&i.Network,
			&i.OriginalLanguage,
			&i.CountryOfOrigin,
			&i.ImdbID,
			&i.TmdbID,
			&i.TvdbID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Directory,
			&i.Rating,
			&i.RatingVotes,
			&i.Tagline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTVShowsByLibraryPaginated = `-- name: ListTVShowsByLibraryPaginated :many
SELECT id, library_id, title, original_title, sort_title, year, first_air_date, last_air_date, genre, plot, status, content_rating, maturity_rating, network, original_language, country_of_origin, imdb_id, tmdb_id, tvdb_id, created_at, updated_at, directory, rating, rating_votes, tagline FROM tv_shows
WHERE library_id = ?
ORDER BY COALESCE(NULLIF(sort_title, ''), title) COLLATE NOCASE ASC
LIMIT ? OFFSET ?
`

type ListTVShowsByLibraryPaginatedParams struct {
	LibraryID int64 `json:"library_id"`
	Limit     int64 `json:"limit"`
	Offset    int64 `json:"offset"`
}

func (q *Queries) ListTVShowsByLibraryPaginated(ctx context.Context, arg ListTVShowsByLibraryPaginatedParams) ([]TvShow, error) {
	rows, err := q.db.QueryContext(ctx, listTVShowsByLibraryPaginated, arg.LibraryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TvShow{}
	for rows.Next() {
		var i TvShow
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Title,
			&i.OriginalTitle,
			&i.SortTitle,
			&i.Year,
			&i.FirstAirDate,
			&i.LastAirDate,
			&i.Genre,
			&i.Plot,
			&i.Status,
			&i.ContentRating,
			&i.MaturityRating,
			&i.Network,
			&i.OriginalLanguage,
			&i.CountryOfOrigin,
			&i.ImdbID,
			&i.TmdbID,
			&i.TvdbID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Directory,
			&i.Rating,
			&i.RatingVotes,
			&i.Tagline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTVShowsByLibraryPaginatedDesc = `-- name: ListTVShowsByLibraryPaginatedDesc :many
SELECT id, library_id, title, original_title, sort_title, year, first_air_date, last_air_date, genre, plot, status, content_rating, maturity_rating, network, original_language, country_of_origin, imdb_id, tmdb_id, tvdb_id, created_at, updated_at, directory, rating, rating_votes, tagline FROM tv_shows
WHERE library_id = ?
ORDER BY COALESCE(NULLIF(sort_title, ''), title) COLLATE NOCASE DESC
LIMIT ? OFFSET ?
`

type ListTVShowsByLibraryPaginatedDescParams struct {
	LibraryID int64 `json:"library_id"`
	Limit     int64 `json:"limit"`
	Offset    int64 `json:"offset"`
}

func (q *Queries) ListTVShowsByLibraryPaginatedDesc(ctx context.Context, arg ListTVShowsByLibraryPaginatedDescParams) ([]TvShow, error) {
	rows, err := q.db.QueryContext(ctx, listTVShowsByLibraryPaginatedDesc, arg.LibraryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TvShow{}
	for rows.Next() {
		var i TvShow
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Title,
			&i.OriginalTitle,
			&i.SortTitle,
			&i.Year,
			&i.FirstAirDate,
			&i.LastAirDate,
			&i.Genre,
			&i.Plot,
			&i.Status,
			&i.ContentRating,
			&i.MaturityRating,
			&i.Network,
			&i.OriginalLanguage,
			&i.CountryOfOrigin,
			&i.ImdbID,
			&i.TmdbID,
			&i.TvdbID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Directory,
			&i.Rating,
			&i.RatingVotes,
			&i.Tagline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTVEpisodesByTitle = `-- name: SearchTVEpisodesByTitle :many
SELECT
    e.media_id, e.show_id, e.season_id, e.season_number, e.episode_number, e.absolute_number, e.dvd_season, e.dvd_episode, e.episode_title, e.original_title, e.air_date, e.plot, e.content_rating, e.maturity_rating, e.imdb_id, e.tmdb_id, e.tvdb_id, e.rating, e.rating_votes, e.runtime_minutes,
    med.id as media_id,
    med.library_id,
    med.title,
    med.file_path,
    med.file_size,
    med.file_hash,
    med.container_format,
    med.duration,
    med.width,
    med.height,
    med.aspect_ratio,
    med.codec,
    med.audio_codec,
    med.codec_profile,
    med.bit_rate,
    med.frame_rate,
    med.scan_type,
    med.hdr_format,
    med.color_space,
    med.color_primaries,
    med.thumbnail_path,
    med.type,
    med.source_type,
    med.resolution_label,
    med.quality_score,
    med.is_3d,
    med.stereo_mode,
    med.has_dash,
    med.dash_manifest_path,
    med.transcoding_status,
    med.is_extra,
    med.date_added,
    med.date_modified,
    med.created_at,
    med.updated_at
FROM tv_episodes e
JOIN media med ON e.media_id = med.id
JOIN tv_shows s ON e.show_id = s.id
WHERE med.library_id = ?
  AND med.is_extra = 0
  AND (e.episode_title LIKE ? OR s.title LIKE ?)
ORDER BY COALESCE(NULLIF(s.sort_title, ''), s.title) COLLATE NOCASE, e.season_number, e.episode_number
`

type SearchTVEpisodesByTitleParams struct {
	LibraryID    int64          `json:"library_id"`
	EpisodeTitle sql.NullString `json:"episode_title"`
	Title        string         `json:"title"`
}

type SearchTVEpisodesByTitleRow struct {
	MediaID           int64           `json:"media_id"`
	ShowID            int64           `json:"show_id"`
	SeasonID          int64           `json:"season_id"`
	SeasonNumber      int64           `json:"season_number"`
	EpisodeNumber     int64           `json:"episode_number"`
	AbsoluteNumber    sql.NullInt64   `json:"absolute_number"`
	DvdSeason         sql.NullInt64   `json:"dvd_season"`
	DvdEpisode        sql.NullInt64   `json:"dvd_episode"`
	EpisodeTitle      sql.NullString  `json:"episode_title"`
	OriginalTitle     sql.NullString  `json:"original_title"`
	AirDate           sql.NullTime    `json:"air_date"`
	Plot              sql.NullString  `json:"plot"`
	ContentRating     sql.NullString  `json:"content_rating"`
	MaturityRating    sql.NullInt64   `json:"maturity_rating"`
	ImdbID            sql.NullString  `json:"imdb_id"`
	TmdbID            sql.NullInt64   `json:"tmdb_id"`
	TvdbID            sql.NullInt64   `json:"tvdb_id"`
	Rating            sql.NullFloat64 `json:"rating"`
	RatingVotes       sql.NullInt64   `json:"rating_votes"`
	RuntimeMinutes    sql.NullInt64   `json:"runtime_minutes"`
	MediaID_2         int64           `json:"media_id_2"`
	LibraryID         int64           `json:"library_id"`
	Title             string          `json:"title"`
	FilePath          string          `json:"file_path"`
	FileSize          sql.NullInt64   `json:"file_size"`
	FileHash          sql.NullString  `json:"file_hash"`
	ContainerFormat   sql.NullString  `json:"container_format"`
	Duration          sql.NullFloat64 `json:"duration"`
	Width             sql.NullInt64   `json:"width"`
	Height            sql.NullInt64   `json:"height"`
	AspectRatio       sql.NullString  `json:"aspect_ratio"`
	Codec             sql.NullString  `json:"codec"`
	AudioCodec        sql.NullString  `json:"audio_codec"`
	CodecProfile      sql.NullString  `json:"codec_profile"`
	BitRate           sql.NullInt64   `json:"bit_rate"`
	FrameRate         sql.NullFloat64 `json:"frame_rate"`
	ScanType          sql.NullString  `json:"scan_type"`
	HdrFormat         sql.NullString  `json:"hdr_format"`
	ColorSpace        sql.NullString  `json:"color_space"`
	ColorPrimaries    sql.NullString  `json:"color_primaries"`
	ThumbnailPath     sql.NullString  `json:"thumbnail_path"`
	Type              string          `json:"type"`
	SourceType        sql.NullString  `json:"source_type"`
	ResolutionLabel   sql.NullString  `json:"resolution_label"`
	QualityScore      sql.NullInt64   `json:"quality_score"`
	Is3d              sql.NullInt64   `json:"is_3d"`
	StereoMode        sql.NullString  `json:"stereo_mode"`
	HasDash           sql.NullInt64   `json:"has_dash"`
	DashManifestPath  sql.NullString  `json:"dash_manifest_path"`
	TranscodingStatus sql.NullString  `json:"transcoding_status"`
	IsExtra           int64           `json:"is_extra"`
	DateAdded         sql.NullTime    `json:"date_added"`
	DateModified      sql.NullTime    `json:"date_modified"`
	CreatedAt         sql.NullTime    `json:"created_at"`
	UpdatedAt         sql.NullTime    `json:"updated_at"`
}

func (q *Queries) SearchTVEpisodesByTitle(ctx context.Context, arg SearchTVEpisodesByTitleParams) ([]SearchTVEpisodesByTitleRow, error) {
	rows, err := q.db.QueryContext(ctx, searchTVEpisodesByTitle, arg.LibraryID, arg.EpisodeTitle, arg.Title)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchTVEpisodesByTitleRow{}
	for rows.Next() {
		var i SearchTVEpisodesByTitleRow
		if err := rows.Scan(
			&i.MediaID,
			&i.ShowID,
			&i.SeasonID,
			&i.SeasonNumber,
			&i.EpisodeNumber,
			&i.AbsoluteNumber,
			&i.DvdSeason,
			&i.DvdEpisode,
			&i.EpisodeTitle,
			&i.OriginalTitle,
			&i.AirDate,
			&i.Plot,
			&i.ContentRating,
			&i.MaturityRating,
			&i.ImdbID,
			&i.TmdbID,
			&i.TvdbID,
			&i.Rating,
			&i.RatingVotes,
			&i.RuntimeMinutes,
			&i.MediaID_2,
			&i.LibraryID,
			&i.Title,
			&i.FilePath,
			&i.FileSize,
			&i.FileHash,
			&i.ContainerFormat,
			&i.Duration,
			&i.Width,
			&i.Height,
			&i.AspectRatio,
			&i.Codec,
			&i.AudioCodec,
			&i.CodecProfile,
			&i.BitRate,
			&i.FrameRate,
			&i.ScanType,
			&i.HdrFormat,
			&i.ColorSpace,
			&i.ColorPrimaries,
			&i.ThumbnailPath,
			&i.Type,
			&i.SourceType,
			&i.ResolutionLabel,
			&i.QualityScore,
			&i.Is3d,
			&i.StereoMode,
			&i.HasDash,
			&i.DashManifestPath,
			&i.TranscodingStatus,
			&i.IsExtra,
			&i.DateAdded,
			&i.DateModified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTVShowsByTitle = `-- name: SearchTVShowsByTitle :many
SELECT id, library_id, title, original_title, sort_title, year, first_air_date, last_air_date, genre, plot, status, content_rating, maturity_rating, network, original_language, country_of_origin, imdb_id, tmdb_id, tvdb_id, created_at, updated_at, directory, rating, rating_votes, tagline FROM tv_shows
WHERE library_id = ?
  AND (title LIKE ? OR original_title LIKE ?)
ORDER BY COALESCE(NULLIF(sort_title, ''), title) COLLATE NOCASE
`

type SearchTVShowsByTitleParams struct {
	LibraryID     int64          `json:"library_id"`
	Title         string         `json:"title"`
	OriginalTitle sql.NullString `json:"original_title"`
}

func (q *Queries) SearchTVShowsByTitle(ctx context.Context, arg SearchTVShowsByTitleParams) ([]TvShow, error) {
	rows, err := q.db.QueryContext(ctx, searchTVShowsByTitle, arg.LibraryID, arg.Title, arg.OriginalTitle)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TvShow{}
	for rows.Next() {
		var i TvShow
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Title,
			&i.OriginalTitle,
			&i.SortTitle,
			&i.Year,
			&i.FirstAirDate,
			&i.LastAirDate,
			&i.Genre,
			&i.Plot,
			&i.Status,
			&i.ContentRating,
			&i.MaturityRating,
			&i.Network,
			&i.OriginalLanguage,
			&i.CountryOfOrigin,
			&i.ImdbID,
			&i.TmdbID,
			&i.TvdbID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Directory,
			&i.Rating,
			&i.RatingVotes,
			&i.Tagline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTVShowsByTitlePaginated = `-- name: SearchTVShowsByTitlePaginated :many
SELECT id, library_id, title, original_title, sort_title, year, first_air_date, last_air_date, genre, plot, status, content_rating, maturity_rating, network, original_language, country_of_origin, imdb_id, tmdb_id, tvdb_id, created_at, updated_at, directory, rating, rating_votes, tagline FROM tv_shows
WHERE library_id = ?
  AND (title LIKE ? OR original_title LIKE ?)
ORDER BY COALESCE(NULLIF(sort_title, ''), title) COLLATE NOCASE
LIMIT ? OFFSET ?
`

type SearchTVShowsByTitlePaginatedParams struct {
	LibraryID     int64          `json:"library_id"`
	Title         string         `json:"title"`
	OriginalTitle sql.NullString `json:"original_title"`
	Limit         int64          `json:"limit"`
	Offset        int64          `json:"offset"`
}

func (q *Queries) SearchTVShowsByTitlePaginated(ctx context.Context, arg SearchTVShowsByTitlePaginatedParams) ([]TvShow, error) {
	rows, err := q.db.QueryContext(ctx, searchTVShowsByTitlePaginated,
		arg.LibraryID,
		arg.Title,
		arg.OriginalTitle,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TvShow{}
	for rows.Next() {
		var i TvShow
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Title,
			&i.OriginalTitle,
			&i.SortTitle,
			&i.Year,
			&i.FirstAirDate,
			&i.LastAirDate,
			&i.Genre,
			&i.Plot,
			&i.Status,
			&i.ContentRating,
			&i.MaturityRating,
			&i.Network,
			&i.OriginalLanguage,
			&i.CountryOfOrigin,
			&i.ImdbID,
			&i.TmdbID,
			&i.TvdbID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Directory,
			&i.Rating,
			&i.RatingVotes,
			&i.Tagline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTVShowsGlobal = `-- name: SearchTVShowsGlobal :many
SELECT
    id,
    library_id,
    title,
    year,
    original_title
FROM tv_shows
WHERE (title LIKE ? OR original_title LIKE ?)
ORDER BY COALESCE(NULLIF(sort_title, ''), title) COLLATE NOCASE
LIMIT ?
`

type SearchTVShowsGlobalParams struct {
	Title         string         `json:"title"`
	OriginalTitle sql.NullString `json:"original_title"`
	Limit         int64          `json:"limit"`
}

type SearchTVShowsGlobalRow struct {
	ID            int64          `json:"id"`
	LibraryID     int64          `json:"library_id"`
	Title         string         `json:"title"`
	Year          sql.NullInt64  `json:"year"`
	OriginalTitle sql.NullString `json:"original_title"`
}

// Searches TV shows across all libraries (for plugin use)
func (q *Queries) SearchTVShowsGlobal(ctx context.Context, arg SearchTVShowsGlobalParams) ([]SearchTVShowsGlobalRow, error) {
	rows, err := q.db.QueryContext(ctx, searchTVShowsGlobal, arg.Title, arg.OriginalTitle, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchTVShowsGlobalRow{}
	for rows.Next() {
		var i SearchTVShowsGlobalRow
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Title,
			&i.Year,
			&i.OriginalTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTVShowsWithCountsByTitlePaginated = `-- name: SearchTVShowsWithCountsByTitlePaginated :many
SELECT
    s.id,
    s.library_id,
    s.title,
    s.year,
    s.genre,
    s.plot,
    s.content_rating,
    s.imdb_id,
    s.tmdb_id,
    s.created_at,
    COUNT(DISTINCT e.season_number) as season_count,
    COUNT(*) as episode_count
FROM tv_shows s
LEFT JOIN tv_episodes e ON s.id = e.show_id
LEFT JOIN media med ON e.media_id = med.id
WHERE s.library_id = ?
  AND (s.title LIKE ? OR s.original_title LIKE ?)
  AND (med.is_extra = 0 OR med.is_extra IS NULL)
GROUP BY s.id, s.library_id, s.title, s.year, s.genre, s.plot, s.content_rating, s.imdb_id, s.tmdb_id, s.created_at
ORDER BY COALESCE(NULLIF(s.sort_title, ''), s.title) COLLATE NOCASE ASC
LIMIT ? OFFSET ?
`

type SearchTVShowsWithCountsByTitlePaginatedParams struct {
	LibraryID     int64          `json:"library_id"`
	Title         string         `json:"title"`
	OriginalTitle sql.NullString `json:"original_title"`
	Limit         int64          `json:"limit"`
	Offset        int64          `json:"offset"`
}

type SearchTVShowsWithCountsByTitlePaginatedRow struct {
	ID            int64          `json:"id"`
	LibraryID     int64          `json:"library_id"`
	Title         string         `json:"title"`
	Year          sql.NullInt64  `json:"year"`
	Genre         sql.NullString `json:"genre"`
	Plot          sql.NullString `json:"plot"`
	ContentRating sql.NullString `json:"content_rating"`
	ImdbID        sql.NullString `json:"imdb_id"`
	TmdbID        sql.NullInt64  `json:"tmdb_id"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	SeasonCount   int64          `json:"season_count"`
	EpisodeCount  int64          `json:"episode_count"`
}

func (q *Queries) SearchTVShowsWithCountsByTitlePaginated(ctx context.Context, arg SearchTVShowsWithCountsByTitlePaginatedParams) ([]SearchTVShowsWithCountsByTitlePaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, searchTVShowsWithCountsByTitlePaginated,
		arg.LibraryID,
		arg.Title,
		arg.OriginalTitle,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchTVShowsWithCountsByTitlePaginatedRow{}
	for rows.Next() {
		var i SearchTVShowsWithCountsByTitlePaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Title,
			&i.Year,
			&i.Genre,
			&i.Plot,
			&i.ContentRating,
			&i.ImdbID,
			&i.TmdbID,
			&i.CreatedAt,
			&i.SeasonCount,
			&i.EpisodeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTVEpisode = `-- name: UpdateTVEpisode :exec
UPDATE tv_episodes
SET show_id = ?,
    season_id = ?,
    season_number = ?,
    episode_number = ?,
    absolute_number = ?,
    dvd_season = ?,
    dvd_episode = ?,
    episode_title = ?,
    original_title = ?,
    air_date = ?,
    plot = ?,
    content_rating = ?,
    maturity_rating = ?,
    imdb_id = ?,
    tmdb_id = ?,
    tvdb_id = ?,
    rating = ?,
    rating_votes = ?,
    runtime_minutes = ?
WHERE media_id = ?
`

type UpdateTVEpisodeParams struct {
	ShowID         int64           `json:"show_id"`
	SeasonID       int64           `json:"season_id"`
	SeasonNumber   int64           `json:"season_number"`
	EpisodeNumber  int64           `json:"episode_number"`
	AbsoluteNumber sql.NullInt64   `json:"absolute_number"`
	DvdSeason      sql.NullInt64   `json:"dvd_season"`
	DvdEpisode     sql.NullInt64   `json:"dvd_episode"`
	EpisodeTitle   sql.NullString  `json:"episode_title"`
	OriginalTitle  sql.NullString  `json:"original_title"`
	AirDate        sql.NullTime    `json:"air_date"`
	Plot           sql.NullString  `json:"plot"`
	ContentRating  sql.NullString  `json:"content_rating"`
	MaturityRating sql.NullInt64   `json:"maturity_rating"`
	ImdbID         sql.NullString  `json:"imdb_id"`
	TmdbID         sql.NullInt64   `json:"tmdb_id"`
	TvdbID         sql.NullInt64   `json:"tvdb_id"`
	Rating         sql.NullFloat64 `json:"rating"`
	RatingVotes    sql.NullInt64   `json:"rating_votes"`
	RuntimeMinutes sql.NullInt64   `json:"runtime_minutes"`
	MediaID        int64           `json:"media_id"`
}

func (q *Queries) UpdateTVEpisode(ctx context.Context, arg UpdateTVEpisodeParams) error {
	_, err := q.db.ExecContext(ctx, updateTVEpisode,
		arg.ShowID,
		arg.SeasonID,
		arg.SeasonNumber,
		arg.EpisodeNumber,
		arg.AbsoluteNumber,
		arg.DvdSeason,
		arg.DvdEpisode,
		arg.EpisodeTitle,
		arg.OriginalTitle,
		arg.AirDate,
		arg.Plot,
		arg.ContentRating,
		arg.MaturityRating,
		arg.ImdbID,
		arg.TmdbID,
		arg.TvdbID,
		arg.Rating,
		arg.RatingVotes,
		arg.RuntimeMinutes,
		arg.MediaID,
	)
	return err
}

const updateTVSeason = `-- name: UpdateTVSeason :exec
UPDATE tv_seasons
SET name = ?,
    overview = ?,
    air_date = ?,
    poster_path = ?,
    episode_count = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateTVSeasonParams struct {
	Name         sql.NullString `json:"name"`
	Overview     sql.NullString `json:"overview"`
	AirDate      sql.NullTime   `json:"air_date"`
	PosterPath   sql.NullString `json:"poster_path"`
	EpisodeCount sql.NullInt64  `json:"episode_count"`
	ID           int64          `json:"id"`
}

func (q *Queries) UpdateTVSeason(ctx context.Context, arg UpdateTVSeasonParams) error {
	_, err := q.db.ExecContext(ctx, updateTVSeason,
		arg.Name,
		arg.Overview,
		arg.AirDate,
		arg.PosterPath,
		arg.EpisodeCount,
		arg.ID,
	)
	return err
}

const updateTVShow = `-- name: UpdateTVShow :exec
UPDATE tv_shows
SET title = ?,
    original_title = ?,
    sort_title = ?,
    year = ?,
    first_air_date = ?,
    last_air_date = ?,
    genre = ?,
    plot = ?,
    status = ?,
    content_rating = ?,
    maturity_rating = ?,
    network = ?,
    original_language = ?,
    country_of_origin = ?,
    imdb_id = ?,
    tmdb_id = ?,
    tvdb_id = ?,
    directory = ?,
    rating = ?,
    rating_votes = ?,
    tagline = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateTVShowParams struct {
	Title            string          `json:"title"`
	OriginalTitle    sql.NullString  `json:"original_title"`
	SortTitle        sql.NullString  `json:"sort_title"`
	Year             sql.NullInt64   `json:"year"`
	FirstAirDate     sql.NullTime    `json:"first_air_date"`
	LastAirDate      sql.NullTime    `json:"last_air_date"`
	Genre            sql.NullString  `json:"genre"`
	Plot             sql.NullString  `json:"plot"`
	Status           sql.NullString  `json:"status"`
	ContentRating    sql.NullString  `json:"content_rating"`
	MaturityRating   sql.NullInt64   `json:"maturity_rating"`
	Network          sql.NullString  `json:"network"`
	OriginalLanguage sql.NullString  `json:"original_language"`
	CountryOfOrigin  sql.NullString  `json:"country_of_origin"`
	ImdbID           sql.NullString  `json:"imdb_id"`
	TmdbID           sql.NullInt64   `json:"tmdb_id"`
	TvdbID           sql.NullInt64   `json:"tvdb_id"`
	Directory        sql.NullString  `json:"directory"`
	Rating           sql.NullFloat64 `json:"rating"`
	RatingVotes      sql.NullInt64   `json:"rating_votes"`
	Tagline          sql.NullString  `json:"tagline"`
	ID               int64           `json:"id"`
}

func (q *Queries) UpdateTVShow(ctx context.Context, arg UpdateTVShowParams) error {
	_, err := q.db.ExecContext(ctx, updateTVShow,
		arg.Title,
		arg.OriginalTitle,
		arg.SortTitle,
		arg.Year,
		arg.FirstAirDate,
		arg.LastAirDate,
		arg.Genre,
		arg.Plot,
		arg.Status,
		arg.ContentRating,
		arg.MaturityRating,
		arg.Network,
		arg.OriginalLanguage,
		arg.CountryOfOrigin,
		arg.ImdbID,
		arg.TmdbID,
		arg.TvdbID,
		arg.Directory,
		arg.Rating,
		arg.RatingVotes,
		arg.Tagline,
		arg.ID,
	)
	return err
}

const upsertTVShow = `-- name: UpsertTVShow :one
INSERT INTO tv_shows (
    library_id, title, sort_title, directory
) VALUES (
    ?1, ?2, ?3, ?4
)
ON CONFLICT(library_id, LOWER(title)) DO UPDATE SET
    directory = CASE
        WHEN tv_shows.directory IS NULL OR tv_shows.directory = ''
        THEN excluded.directory
        ELSE tv_shows.directory
    END,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, library_id, title, original_title, sort_title, year, first_air_date, last_air_date, genre, plot, status, content_rating, maturity_rating, network, original_language, country_of_origin, imdb_id, tmdb_id, tvdb_id, created_at, updated_at, directory, rating, rating_votes, tagline
`

type UpsertTVShowParams struct {
	LibraryID int64          `json:"library_id"`
	Title     string         `json:"title"`
	SortTitle sql.NullString `json:"sort_title"`
	Directory sql.NullString `json:"directory"`
}

// Atomically creates a TV show or returns existing one if title already exists.
// Uses ON CONFLICT to handle race conditions during concurrent episode scans.
// On conflict, updates directory if it was previously empty.
func (q *Queries) UpsertTVShow(ctx context.Context, arg UpsertTVShowParams) (TvShow, error) {
	row := q.db.QueryRowContext(ctx, upsertTVShow,
		arg.LibraryID,
		arg.Title,
		arg.SortTitle,
		arg.Directory,
	)
	var i TvShow
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Title,
		&i.OriginalTitle,
		&i.SortTitle,
		&i.Year,
		&i.FirstAirDate,
		&i.LastAirDate,
		&i.Genre,
		&i.Plot,
		&i.Status,
		&i.ContentRating,
		&i.MaturityRating,
		&i.Network,
		&i.OriginalLanguage,
		&i.CountryOfOrigin,
		&i.ImdbID,
		&i.TmdbID,
		&i.TvdbID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Directory,
		&i.Rating,
		&i.RatingVotes,
		&i.Tagline,
	)
	return i, err
}
