// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc_sqlite

import (
	"context"
	"database/sql"
	"time"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (public_id, username, display_name, password_hash, is_admin, is_disabled, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, public_id, username, display_name, password_hash, is_admin, is_disabled, created_at, updated_at, location_latitude, location_longitude, location_timezone, location_enabled, location_name
`

type CreateUserParams struct {
	PublicID     string    `json:"public_id"`
	Username     string    `json:"username"`
	DisplayName  string    `json:"display_name"`
	PasswordHash string    `json:"password_hash"`
	IsAdmin      int64     `json:"is_admin"`
	IsDisabled   int64     `json:"is_disabled"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

// User queries for SQLite
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.PublicID,
		arg.Username,
		arg.DisplayName,
		arg.PasswordHash,
		arg.IsAdmin,
		arg.IsDisabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.IsDisabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LocationLatitude,
		&i.LocationLongitude,
		&i.LocationTimezone,
		&i.LocationEnabled,
		&i.LocationName,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const existsAnyUser = `-- name: ExistsAnyUser :one
SELECT EXISTS(SELECT 1 FROM users)
`

func (q *Queries) ExistsAnyUser(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, existsAnyUser)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, public_id, username, display_name, password_hash, is_admin, is_disabled, created_at, updated_at, location_latitude, location_longitude, location_timezone, location_enabled, location_name FROM users
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.IsDisabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LocationLatitude,
		&i.LocationLongitude,
		&i.LocationTimezone,
		&i.LocationEnabled,
		&i.LocationName,
	)
	return i, err
}

const getUserByPublicID = `-- name: GetUserByPublicID :one
SELECT id, public_id, username, display_name, password_hash, is_admin, is_disabled, created_at, updated_at, location_latitude, location_longitude, location_timezone, location_enabled, location_name FROM users
WHERE public_id = ?
LIMIT 1
`

func (q *Queries) GetUserByPublicID(ctx context.Context, publicID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByPublicID, publicID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.IsDisabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LocationLatitude,
		&i.LocationLongitude,
		&i.LocationTimezone,
		&i.LocationEnabled,
		&i.LocationName,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, public_id, username, display_name, password_hash, is_admin, is_disabled, created_at, updated_at, location_latitude, location_longitude, location_timezone, location_enabled, location_name FROM users
WHERE LOWER(username) = LOWER(?)
LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.IsDisabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LocationLatitude,
		&i.LocationLongitude,
		&i.LocationTimezone,
		&i.LocationEnabled,
		&i.LocationName,
	)
	return i, err
}

const getUserLocation = `-- name: GetUserLocation :one

SELECT id, location_latitude, location_longitude, location_timezone, location_enabled, location_name
FROM users
WHERE id = ?
`

type GetUserLocationRow struct {
	ID                int64           `json:"id"`
	LocationLatitude  sql.NullFloat64 `json:"location_latitude"`
	LocationLongitude sql.NullFloat64 `json:"location_longitude"`
	LocationTimezone  sql.NullString  `json:"location_timezone"`
	LocationEnabled   sql.NullInt64   `json:"location_enabled"`
	LocationName      sql.NullString  `json:"location_name"`
}

// Location Preferences (stored in users table)
func (q *Queries) GetUserLocation(ctx context.Context, id int64) (GetUserLocationRow, error) {
	row := q.db.QueryRowContext(ctx, getUserLocation, id)
	var i GetUserLocationRow
	err := row.Scan(
		&i.ID,
		&i.LocationLatitude,
		&i.LocationLongitude,
		&i.LocationTimezone,
		&i.LocationEnabled,
		&i.LocationName,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, public_id, username, display_name, password_hash, is_admin, is_disabled, created_at, updated_at, location_latitude, location_longitude, location_timezone, location_enabled, location_name FROM users
ORDER BY username
LIMIT ? OFFSET ?
`

type ListUsersParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Username,
			&i.DisplayName,
			&i.PasswordHash,
			&i.IsAdmin,
			&i.IsDisabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LocationLatitude,
			&i.LocationLongitude,
			&i.LocationTimezone,
			&i.LocationEnabled,
			&i.LocationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET display_name = ?,
    is_admin = ?,
    is_disabled = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, public_id, username, display_name, password_hash, is_admin, is_disabled, created_at, updated_at, location_latitude, location_longitude, location_timezone, location_enabled, location_name
`

type UpdateUserParams struct {
	DisplayName string    `json:"display_name"`
	IsAdmin     int64     `json:"is_admin"`
	IsDisabled  int64     `json:"is_disabled"`
	UpdatedAt   time.Time `json:"updated_at"`
	ID          int64     `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.DisplayName,
		arg.IsAdmin,
		arg.IsDisabled,
		arg.UpdatedAt,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.IsDisabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LocationLatitude,
		&i.LocationLongitude,
		&i.LocationTimezone,
		&i.LocationEnabled,
		&i.LocationName,
	)
	return i, err
}

const updateUserLocation = `-- name: UpdateUserLocation :exec
UPDATE users
SET location_latitude = ?,
    location_longitude = ?,
    location_timezone = ?,
    location_enabled = ?,
    location_name = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateUserLocationParams struct {
	LocationLatitude  sql.NullFloat64 `json:"location_latitude"`
	LocationLongitude sql.NullFloat64 `json:"location_longitude"`
	LocationTimezone  sql.NullString  `json:"location_timezone"`
	LocationEnabled   sql.NullInt64   `json:"location_enabled"`
	LocationName      sql.NullString  `json:"location_name"`
	UpdatedAt         time.Time       `json:"updated_at"`
	ID                int64           `json:"id"`
}

func (q *Queries) UpdateUserLocation(ctx context.Context, arg UpdateUserLocationParams) error {
	_, err := q.db.ExecContext(ctx, updateUserLocation,
		arg.LocationLatitude,
		arg.LocationLongitude,
		arg.LocationTimezone,
		arg.LocationEnabled,
		arg.LocationName,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateUserPasswordParams struct {
	PasswordHash string    `json:"password_hash"`
	UpdatedAt    time.Time `json:"updated_at"`
	ID           int64     `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.UpdatedAt, arg.ID)
	return err
}
