// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: enrichment_queue.sql

package sqlc_postgres

import (
	"context"
	"database/sql"
)

const claimEnrichmentJobs = `-- name: ClaimEnrichmentJobs :many
UPDATE enrichment_queue
SET
    status = 'processing',
    locked_by = $1,
    locked_at = NOW(),
    updated_at = NOW()
WHERE id IN (
    SELECT eq.id FROM enrichment_queue eq
    WHERE eq.stage = $2 AND eq.status = 'pending'
    ORDER BY eq.priority DESC, eq.created_at ASC
    LIMIT $3
    FOR UPDATE SKIP LOCKED
)
RETURNING id, media_id, stage, priority, status, attempts, max_attempts, error_message, error_category, next_retry_at, locked_by, locked_at, created_at, updated_at, media_type
`

type ClaimEnrichmentJobsParams struct {
	LockedBy sql.NullString `json:"locked_by"`
	Stage    string         `json:"stage"`
	Limit    int32          `json:"limit"`
}

func (q *Queries) ClaimEnrichmentJobs(ctx context.Context, arg ClaimEnrichmentJobsParams) ([]EnrichmentQueue, error) {
	rows, err := q.db.QueryContext(ctx, claimEnrichmentJobs, arg.LockedBy, arg.Stage, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnrichmentQueue{}
	for rows.Next() {
		var i EnrichmentQueue
		if err := rows.Scan(
			&i.ID,
			&i.MediaID,
			&i.Stage,
			&i.Priority,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.ErrorMessage,
			&i.ErrorCategory,
			&i.NextRetryAt,
			&i.LockedBy,
			&i.LockedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MediaType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeEnrichmentJob = `-- name: CompleteEnrichmentJob :exec
UPDATE enrichment_queue
SET
    status = 'completed',
    locked_by = NULL,
    locked_at = NULL,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) CompleteEnrichmentJob(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, completeEnrichmentJob, id)
	return err
}

const deleteEnrichmentJobsByMedia = `-- name: DeleteEnrichmentJobsByMedia :exec
DELETE FROM enrichment_queue WHERE media_id = $1 AND media_type = $2
`

type DeleteEnrichmentJobsByMediaParams struct {
	MediaID   int32  `json:"media_id"`
	MediaType string `json:"media_type"`
}

func (q *Queries) DeleteEnrichmentJobsByMedia(ctx context.Context, arg DeleteEnrichmentJobsByMediaParams) error {
	_, err := q.db.ExecContext(ctx, deleteEnrichmentJobsByMedia, arg.MediaID, arg.MediaType)
	return err
}

const enqueueEnrichmentJob = `-- name: EnqueueEnrichmentJob :one
INSERT INTO enrichment_queue (
    media_id,
    media_type,
    stage,
    priority,
    status,
    attempts,
    max_attempts,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, 'pending', 0, $5, NOW(), NOW())
ON CONFLICT(media_id, media_type, stage) DO UPDATE SET
    priority = CASE WHEN enrichment_queue.status IN ('completed', 'skipped') THEN EXCLUDED.priority ELSE enrichment_queue.priority END,
    status = CASE WHEN enrichment_queue.status IN ('completed', 'skipped') THEN 'pending' ELSE enrichment_queue.status END,
    updated_at = NOW()
WHERE enrichment_queue.status IN ('completed', 'skipped', 'failed')
RETURNING id, media_id, stage, priority, status, attempts, max_attempts, error_message, error_category, next_retry_at, locked_by, locked_at, created_at, updated_at, media_type
`

type EnqueueEnrichmentJobParams struct {
	MediaID     int32         `json:"media_id"`
	MediaType   string        `json:"media_type"`
	Stage       string        `json:"stage"`
	Priority    sql.NullInt32 `json:"priority"`
	MaxAttempts sql.NullInt32 `json:"max_attempts"`
}

func (q *Queries) EnqueueEnrichmentJob(ctx context.Context, arg EnqueueEnrichmentJobParams) (EnrichmentQueue, error) {
	row := q.db.QueryRowContext(ctx, enqueueEnrichmentJob,
		arg.MediaID,
		arg.MediaType,
		arg.Stage,
		arg.Priority,
		arg.MaxAttempts,
	)
	var i EnrichmentQueue
	err := row.Scan(
		&i.ID,
		&i.MediaID,
		&i.Stage,
		&i.Priority,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ErrorMessage,
		&i.ErrorCategory,
		&i.NextRetryAt,
		&i.LockedBy,
		&i.LockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MediaType,
	)
	return i, err
}

const failEnrichmentJob = `-- name: FailEnrichmentJob :exec
UPDATE enrichment_queue
SET
    status = CASE WHEN attempts + 1 >= max_attempts THEN 'failed' ELSE 'pending' END,
    attempts = attempts + 1,
    error_message = $1,
    error_category = $2,
    next_retry_at = $3,
    locked_by = NULL,
    locked_at = NULL,
    updated_at = NOW()
WHERE id = $4
`

type FailEnrichmentJobParams struct {
	ErrorMessage  sql.NullString `json:"error_message"`
	ErrorCategory sql.NullString `json:"error_category"`
	NextRetryAt   sql.NullTime   `json:"next_retry_at"`
	ID            int32          `json:"id"`
}

func (q *Queries) FailEnrichmentJob(ctx context.Context, arg FailEnrichmentJobParams) error {
	_, err := q.db.ExecContext(ctx, failEnrichmentJob,
		arg.ErrorMessage,
		arg.ErrorCategory,
		arg.NextRetryAt,
		arg.ID,
	)
	return err
}

const getEnrichmentJob = `-- name: GetEnrichmentJob :one
SELECT id, media_id, stage, priority, status, attempts, max_attempts, error_message, error_category, next_retry_at, locked_by, locked_at, created_at, updated_at, media_type FROM enrichment_queue WHERE id = $1
`

func (q *Queries) GetEnrichmentJob(ctx context.Context, id int32) (EnrichmentQueue, error) {
	row := q.db.QueryRowContext(ctx, getEnrichmentJob, id)
	var i EnrichmentQueue
	err := row.Scan(
		&i.ID,
		&i.MediaID,
		&i.Stage,
		&i.Priority,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ErrorMessage,
		&i.ErrorCategory,
		&i.NextRetryAt,
		&i.LockedBy,
		&i.LockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MediaType,
	)
	return i, err
}

const getEnrichmentJobByMediaAndStage = `-- name: GetEnrichmentJobByMediaAndStage :one
SELECT id, media_id, stage, priority, status, attempts, max_attempts, error_message, error_category, next_retry_at, locked_by, locked_at, created_at, updated_at, media_type FROM enrichment_queue WHERE media_id = $1 AND media_type = $2 AND stage = $3
`

type GetEnrichmentJobByMediaAndStageParams struct {
	MediaID   int32  `json:"media_id"`
	MediaType string `json:"media_type"`
	Stage     string `json:"stage"`
}

func (q *Queries) GetEnrichmentJobByMediaAndStage(ctx context.Context, arg GetEnrichmentJobByMediaAndStageParams) (EnrichmentQueue, error) {
	row := q.db.QueryRowContext(ctx, getEnrichmentJobByMediaAndStage, arg.MediaID, arg.MediaType, arg.Stage)
	var i EnrichmentQueue
	err := row.Scan(
		&i.ID,
		&i.MediaID,
		&i.Stage,
		&i.Priority,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ErrorMessage,
		&i.ErrorCategory,
		&i.NextRetryAt,
		&i.LockedBy,
		&i.LockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MediaType,
	)
	return i, err
}

const getEnrichmentQueueStats = `-- name: GetEnrichmentQueueStats :one
SELECT
    stage,
    SUM(CASE WHEN status = 'pending' THEN 1 ELSE 0 END)::bigint as pending_count,
    SUM(CASE WHEN status = 'processing' THEN 1 ELSE 0 END)::bigint as processing_count,
    SUM(CASE WHEN status = 'completed' THEN 1 ELSE 0 END)::bigint as completed_count,
    SUM(CASE WHEN status = 'failed' THEN 1 ELSE 0 END)::bigint as failed_count,
    SUM(CASE WHEN status = 'skipped' THEN 1 ELSE 0 END)::bigint as skipped_count,
    COUNT(*)::bigint as total_count
FROM enrichment_queue
WHERE stage = $1
GROUP BY stage
`

type GetEnrichmentQueueStatsRow struct {
	Stage           string `json:"stage"`
	PendingCount    int64  `json:"pending_count"`
	ProcessingCount int64  `json:"processing_count"`
	CompletedCount  int64  `json:"completed_count"`
	FailedCount     int64  `json:"failed_count"`
	SkippedCount    int64  `json:"skipped_count"`
	TotalCount      int64  `json:"total_count"`
}

func (q *Queries) GetEnrichmentQueueStats(ctx context.Context, stage string) (GetEnrichmentQueueStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getEnrichmentQueueStats, stage)
	var i GetEnrichmentQueueStatsRow
	err := row.Scan(
		&i.Stage,
		&i.PendingCount,
		&i.ProcessingCount,
		&i.CompletedCount,
		&i.FailedCount,
		&i.SkippedCount,
		&i.TotalCount,
	)
	return i, err
}

const getEnrichmentQueueStatsByMedia = `-- name: GetEnrichmentQueueStatsByMedia :many
SELECT
    stage,
    status,
    attempts,
    error_message,
    created_at,
    updated_at
FROM enrichment_queue
WHERE media_id = $1
ORDER BY created_at
`

type GetEnrichmentQueueStatsByMediaRow struct {
	Stage        string         `json:"stage"`
	Status       sql.NullString `json:"status"`
	Attempts     sql.NullInt32  `json:"attempts"`
	ErrorMessage sql.NullString `json:"error_message"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

func (q *Queries) GetEnrichmentQueueStatsByMedia(ctx context.Context, mediaID int32) ([]GetEnrichmentQueueStatsByMediaRow, error) {
	rows, err := q.db.QueryContext(ctx, getEnrichmentQueueStatsByMedia, mediaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEnrichmentQueueStatsByMediaRow{}
	for rows.Next() {
		var i GetEnrichmentQueueStatsByMediaRow
		if err := rows.Scan(
			&i.Stage,
			&i.Status,
			&i.Attempts,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRetryableEnrichmentJobs = `-- name: GetRetryableEnrichmentJobs :many
SELECT id, media_id, stage, priority, status, attempts, max_attempts, error_message, error_category, next_retry_at, locked_by, locked_at, created_at, updated_at, media_type FROM enrichment_queue
WHERE status = 'failed'
  AND next_retry_at IS NOT NULL
  AND next_retry_at <= NOW()
  AND stage = $1
ORDER BY next_retry_at ASC
LIMIT $2
`

type GetRetryableEnrichmentJobsParams struct {
	Stage string `json:"stage"`
	Limit int32  `json:"limit"`
}

func (q *Queries) GetRetryableEnrichmentJobs(ctx context.Context, arg GetRetryableEnrichmentJobsParams) ([]EnrichmentQueue, error) {
	rows, err := q.db.QueryContext(ctx, getRetryableEnrichmentJobs, arg.Stage, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnrichmentQueue{}
	for rows.Next() {
		var i EnrichmentQueue
		if err := rows.Scan(
			&i.ID,
			&i.MediaID,
			&i.Stage,
			&i.Priority,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.ErrorMessage,
			&i.ErrorCategory,
			&i.NextRetryAt,
			&i.LockedBy,
			&i.LockedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MediaType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseStuckEnrichmentJobs = `-- name: ReleaseStuckEnrichmentJobs :exec
UPDATE enrichment_queue
SET
    status = 'pending',
    locked_by = NULL,
    locked_at = NULL,
    updated_at = NOW()
WHERE status = 'processing'
  AND locked_at < NOW() - ($1 || ' seconds')::interval
`

func (q *Queries) ReleaseStuckEnrichmentJobs(ctx context.Context, dollar_1 sql.NullString) error {
	_, err := q.db.ExecContext(ctx, releaseStuckEnrichmentJobs, dollar_1)
	return err
}

const resetEnrichmentJobForRetry = `-- name: ResetEnrichmentJobForRetry :exec
UPDATE enrichment_queue
SET
    status = 'pending',
    error_message = NULL,
    error_category = NULL,
    next_retry_at = NULL,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ResetEnrichmentJobForRetry(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, resetEnrichmentJobForRetry, id)
	return err
}

const skipEnrichmentJob = `-- name: SkipEnrichmentJob :exec
UPDATE enrichment_queue
SET
    status = 'skipped',
    locked_by = NULL,
    locked_at = NULL,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SkipEnrichmentJob(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, skipEnrichmentJob, id)
	return err
}
