// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: external_ids.sql

package sqlc_postgres

import (
	"context"
	"database/sql"
)

const deleteExternalID = `-- name: DeleteExternalID :exec
DELETE FROM media_external_ids
WHERE media_id = $1 AND provider = $2
`

type DeleteExternalIDParams struct {
	MediaID  int32  `json:"media_id"`
	Provider string `json:"provider"`
}

func (q *Queries) DeleteExternalID(ctx context.Context, arg DeleteExternalIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteExternalID, arg.MediaID, arg.Provider)
	return err
}

const deleteExternalIDsByMedia = `-- name: DeleteExternalIDsByMedia :exec
DELETE FROM media_external_ids WHERE media_id = $1
`

func (q *Queries) DeleteExternalIDsByMedia(ctx context.Context, mediaID int32) error {
	_, err := q.db.ExecContext(ctx, deleteExternalIDsByMedia, mediaID)
	return err
}

const deleteMetadataSource = `-- name: DeleteMetadataSource :exec
DELETE FROM media_metadata_sources
WHERE media_id = $1 AND field_name = $2 AND plugin_id = $3
`

type DeleteMetadataSourceParams struct {
	MediaID   int32  `json:"media_id"`
	FieldName string `json:"field_name"`
	PluginID  string `json:"plugin_id"`
}

func (q *Queries) DeleteMetadataSource(ctx context.Context, arg DeleteMetadataSourceParams) error {
	_, err := q.db.ExecContext(ctx, deleteMetadataSource, arg.MediaID, arg.FieldName, arg.PluginID)
	return err
}

const deleteMetadataSourcesByMedia = `-- name: DeleteMetadataSourcesByMedia :exec
DELETE FROM media_metadata_sources WHERE media_id = $1
`

func (q *Queries) DeleteMetadataSourcesByMedia(ctx context.Context, mediaID int32) error {
	_, err := q.db.ExecContext(ctx, deleteMetadataSourcesByMedia, mediaID)
	return err
}

const deleteMetadataSourcesByPlugin = `-- name: DeleteMetadataSourcesByPlugin :exec
DELETE FROM media_metadata_sources WHERE plugin_id = $1
`

func (q *Queries) DeleteMetadataSourcesByPlugin(ctx context.Context, pluginID string) error {
	_, err := q.db.ExecContext(ctx, deleteMetadataSourcesByPlugin, pluginID)
	return err
}

const getExternalID = `-- name: GetExternalID :one
SELECT media_id, provider, external_id, created_at, updated_at FROM media_external_ids
WHERE media_id = $1 AND provider = $2
`

type GetExternalIDParams struct {
	MediaID  int32  `json:"media_id"`
	Provider string `json:"provider"`
}

func (q *Queries) GetExternalID(ctx context.Context, arg GetExternalIDParams) (MediaExternalID, error) {
	row := q.db.QueryRowContext(ctx, getExternalID, arg.MediaID, arg.Provider)
	var i MediaExternalID
	err := row.Scan(
		&i.MediaID,
		&i.Provider,
		&i.ExternalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExternalIDsByMedia = `-- name: GetExternalIDsByMedia :many
SELECT media_id, provider, external_id, created_at, updated_at FROM media_external_ids
WHERE media_id = $1
ORDER BY provider
`

func (q *Queries) GetExternalIDsByMedia(ctx context.Context, mediaID int32) ([]MediaExternalID, error) {
	rows, err := q.db.QueryContext(ctx, getExternalIDsByMedia, mediaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaExternalID{}
	for rows.Next() {
		var i MediaExternalID
		if err := rows.Scan(
			&i.MediaID,
			&i.Provider,
			&i.ExternalID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMediaByExternalID = `-- name: GetMediaByExternalID :one
SELECT media_id FROM media_external_ids
WHERE provider = $1 AND external_id = $2
`

type GetMediaByExternalIDParams struct {
	Provider   string `json:"provider"`
	ExternalID string `json:"external_id"`
}

func (q *Queries) GetMediaByExternalID(ctx context.Context, arg GetMediaByExternalIDParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, getMediaByExternalID, arg.Provider, arg.ExternalID)
	var media_id int32
	err := row.Scan(&media_id)
	return media_id, err
}

const getMetadataSource = `-- name: GetMetadataSource :one
SELECT media_id, field_name, plugin_id, raw_value, updated_at FROM media_metadata_sources
WHERE media_id = $1 AND field_name = $2 AND plugin_id = $3
`

type GetMetadataSourceParams struct {
	MediaID   int32  `json:"media_id"`
	FieldName string `json:"field_name"`
	PluginID  string `json:"plugin_id"`
}

func (q *Queries) GetMetadataSource(ctx context.Context, arg GetMetadataSourceParams) (MediaMetadataSource, error) {
	row := q.db.QueryRowContext(ctx, getMetadataSource, arg.MediaID, arg.FieldName, arg.PluginID)
	var i MediaMetadataSource
	err := row.Scan(
		&i.MediaID,
		&i.FieldName,
		&i.PluginID,
		&i.RawValue,
		&i.UpdatedAt,
	)
	return i, err
}

const getMetadataSourcesByField = `-- name: GetMetadataSourcesByField :many
SELECT media_id, field_name, plugin_id, raw_value, updated_at FROM media_metadata_sources
WHERE media_id = $1 AND field_name = $2
ORDER BY plugin_id
`

type GetMetadataSourcesByFieldParams struct {
	MediaID   int32  `json:"media_id"`
	FieldName string `json:"field_name"`
}

func (q *Queries) GetMetadataSourcesByField(ctx context.Context, arg GetMetadataSourcesByFieldParams) ([]MediaMetadataSource, error) {
	rows, err := q.db.QueryContext(ctx, getMetadataSourcesByField, arg.MediaID, arg.FieldName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaMetadataSource{}
	for rows.Next() {
		var i MediaMetadataSource
		if err := rows.Scan(
			&i.MediaID,
			&i.FieldName,
			&i.PluginID,
			&i.RawValue,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMetadataSourcesByMedia = `-- name: GetMetadataSourcesByMedia :many
SELECT media_id, field_name, plugin_id, raw_value, updated_at FROM media_metadata_sources
WHERE media_id = $1
ORDER BY field_name, plugin_id
`

func (q *Queries) GetMetadataSourcesByMedia(ctx context.Context, mediaID int32) ([]MediaMetadataSource, error) {
	rows, err := q.db.QueryContext(ctx, getMetadataSourcesByMedia, mediaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaMetadataSource{}
	for rows.Next() {
		var i MediaMetadataSource
		if err := rows.Scan(
			&i.MediaID,
			&i.FieldName,
			&i.PluginID,
			&i.RawValue,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExternalID = `-- name: UpsertExternalID :exec
INSERT INTO media_external_ids (
    media_id,
    provider,
    external_id,
    created_at,
    updated_at
) VALUES ($1, $2, $3, NOW(), NOW())
ON CONFLICT(media_id, provider) DO UPDATE SET
    external_id = EXCLUDED.external_id,
    updated_at = NOW()
`

type UpsertExternalIDParams struct {
	MediaID    int32  `json:"media_id"`
	Provider   string `json:"provider"`
	ExternalID string `json:"external_id"`
}

func (q *Queries) UpsertExternalID(ctx context.Context, arg UpsertExternalIDParams) error {
	_, err := q.db.ExecContext(ctx, upsertExternalID, arg.MediaID, arg.Provider, arg.ExternalID)
	return err
}

const upsertMetadataSource = `-- name: UpsertMetadataSource :exec
INSERT INTO media_metadata_sources (
    media_id,
    field_name,
    plugin_id,
    raw_value,
    updated_at
) VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT(media_id, field_name, plugin_id) DO UPDATE SET
    raw_value = EXCLUDED.raw_value,
    updated_at = NOW()
`

type UpsertMetadataSourceParams struct {
	MediaID   int32          `json:"media_id"`
	FieldName string         `json:"field_name"`
	PluginID  string         `json:"plugin_id"`
	RawValue  sql.NullString `json:"raw_value"`
}

func (q *Queries) UpsertMetadataSource(ctx context.Context, arg UpsertMetadataSourceParams) error {
	_, err := q.db.ExecContext(ctx, upsertMetadataSource,
		arg.MediaID,
		arg.FieldName,
		arg.PluginID,
		arg.RawValue,
	)
	return err
}
