// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: music_tracks.sql

package sqlc_postgres

import (
	"context"
	"database/sql"
)

const countAlbumsByLibrary = `-- name: CountAlbumsByLibrary :one

SELECT COUNT(DISTINCT mt.album || mt.album_artist)
FROM music_tracks mt
JOIN media med ON mt.media_id = med.id
WHERE med.library_id = $1
`

// ============================================================================
// Pagination Support Queries
// ============================================================================
func (q *Queries) CountAlbumsByLibrary(ctx context.Context, libraryID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAlbumsByLibrary, libraryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMusicTracksByLibrary = `-- name: CountMusicTracksByLibrary :one
SELECT COUNT(*)
FROM music_tracks mt
JOIN media med ON mt.media_id = med.id
WHERE med.library_id = $1
`

func (q *Queries) CountMusicTracksByLibrary(ctx context.Context, libraryID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMusicTracksByLibrary, libraryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMusicTrack = `-- name: CreateMusicTrack :exec
INSERT INTO music_tracks (
    media_id, artist, album, album_artist, track_number, disc_number,
    total_tracks, total_discs, genre, year, release_date, composer,
    lyricist, record_label, isrc, release_type, compilation,
    musicbrainz_track_id, musicbrainz_album_id, musicbrainz_artist_id,
    original_title, sort_title, album_id, artist_id
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12,
    $13, $14, $15, $16, $17,
    $18, $19, $20,
    $21, $22, $23, $24
)
`

type CreateMusicTrackParams struct {
	MediaID             int64          `json:"media_id"`
	Artist              sql.NullString `json:"artist"`
	Album               sql.NullString `json:"album"`
	AlbumArtist         sql.NullString `json:"album_artist"`
	TrackNumber         sql.NullInt64  `json:"track_number"`
	DiscNumber          sql.NullInt64  `json:"disc_number"`
	TotalTracks         sql.NullInt64  `json:"total_tracks"`
	TotalDiscs          sql.NullInt64  `json:"total_discs"`
	Genre               sql.NullString `json:"genre"`
	Year                sql.NullInt64  `json:"year"`
	ReleaseDate         sql.NullTime   `json:"release_date"`
	Composer            sql.NullString `json:"composer"`
	Lyricist            sql.NullString `json:"lyricist"`
	RecordLabel         sql.NullString `json:"record_label"`
	Isrc                sql.NullString `json:"isrc"`
	ReleaseType         sql.NullString `json:"release_type"`
	Compilation         sql.NullInt64  `json:"compilation"`
	MusicbrainzTrackID  sql.NullString `json:"musicbrainz_track_id"`
	MusicbrainzAlbumID  sql.NullString `json:"musicbrainz_album_id"`
	MusicbrainzArtistID sql.NullString `json:"musicbrainz_artist_id"`
	OriginalTitle       sql.NullString `json:"original_title"`
	SortTitle           sql.NullString `json:"sort_title"`
	AlbumID             sql.NullInt64  `json:"album_id"`
	ArtistID            sql.NullInt64  `json:"artist_id"`
}

func (q *Queries) CreateMusicTrack(ctx context.Context, arg CreateMusicTrackParams) error {
	_, err := q.db.ExecContext(ctx, createMusicTrack,
		arg.MediaID,
		arg.Artist,
		arg.Album,
		arg.AlbumArtist,
		arg.TrackNumber,
		arg.DiscNumber,
		arg.TotalTracks,
		arg.TotalDiscs,
		arg.Genre,
		arg.Year,
		arg.ReleaseDate,
		arg.Composer,
		arg.Lyricist,
		arg.RecordLabel,
		arg.Isrc,
		arg.ReleaseType,
		arg.Compilation,
		arg.MusicbrainzTrackID,
		arg.MusicbrainzAlbumID,
		arg.MusicbrainzArtistID,
		arg.OriginalTitle,
		arg.SortTitle,
		arg.AlbumID,
		arg.ArtistID,
	)
	return err
}

const deleteMusicTrack = `-- name: DeleteMusicTrack :exec
DELETE FROM music_tracks
WHERE media_id = $1
`

func (q *Queries) DeleteMusicTrack(ctx context.Context, mediaID int64) error {
	_, err := q.db.ExecContext(ctx, deleteMusicTrack, mediaID)
	return err
}

const getMusicTrackByMediaID = `-- name: GetMusicTrackByMediaID :one
SELECT
    mt.media_id, mt.artist, mt.album, mt.album_artist, mt.track_number, mt.disc_number, mt.total_tracks, mt.total_discs, mt.genre, mt.year, mt.release_date, mt.composer, mt.lyricist, mt.record_label, mt.isrc, mt.release_type, mt.compilation, mt.musicbrainz_track_id, mt.musicbrainz_album_id, mt.musicbrainz_artist_id, mt.original_title, mt.sort_title, mt.album_id, mt.artist_id,
    med.id as media_id,
    med.library_id,
    med.title,
    med.file_path,
    med.file_size,
    med.file_hash,
    med.container_format,
    med.duration,
    med.width,
    med.height,
    med.aspect_ratio,
    med.codec,
    med.audio_codec,
    med.codec_profile,
    med.bit_rate,
    med.frame_rate,
    med.scan_type,
    med.hdr_format,
    med.color_space,
    med.color_primaries,
    med.thumbnail_path,
    med.type,
    med.source_type,
    med.resolution_label,
    med.quality_score,
    med.is_3d,
    med.stereo_mode,
    med.has_dash,
    med.dash_manifest_path,
    med.transcoding_status,
    med.is_extra,
    med.date_added,
    med.date_modified,
    med.created_at,
    med.updated_at
FROM music_tracks mt
JOIN media med ON mt.media_id = med.id
WHERE mt.media_id = $1
`

type GetMusicTrackByMediaIDRow struct {
	MediaID             int64           `json:"media_id"`
	Artist              sql.NullString  `json:"artist"`
	Album               sql.NullString  `json:"album"`
	AlbumArtist         sql.NullString  `json:"album_artist"`
	TrackNumber         sql.NullInt64   `json:"track_number"`
	DiscNumber          sql.NullInt64   `json:"disc_number"`
	TotalTracks         sql.NullInt64   `json:"total_tracks"`
	TotalDiscs          sql.NullInt64   `json:"total_discs"`
	Genre               sql.NullString  `json:"genre"`
	Year                sql.NullInt64   `json:"year"`
	ReleaseDate         sql.NullTime    `json:"release_date"`
	Composer            sql.NullString  `json:"composer"`
	Lyricist            sql.NullString  `json:"lyricist"`
	RecordLabel         sql.NullString  `json:"record_label"`
	Isrc                sql.NullString  `json:"isrc"`
	ReleaseType         sql.NullString  `json:"release_type"`
	Compilation         sql.NullInt64   `json:"compilation"`
	MusicbrainzTrackID  sql.NullString  `json:"musicbrainz_track_id"`
	MusicbrainzAlbumID  sql.NullString  `json:"musicbrainz_album_id"`
	MusicbrainzArtistID sql.NullString  `json:"musicbrainz_artist_id"`
	OriginalTitle       sql.NullString  `json:"original_title"`
	SortTitle           sql.NullString  `json:"sort_title"`
	AlbumID             sql.NullInt64   `json:"album_id"`
	ArtistID            sql.NullInt64   `json:"artist_id"`
	MediaID_2           int64           `json:"media_id_2"`
	LibraryID           int64           `json:"library_id"`
	Title               string          `json:"title"`
	FilePath            string          `json:"file_path"`
	FileSize            sql.NullInt64   `json:"file_size"`
	FileHash            sql.NullString  `json:"file_hash"`
	ContainerFormat     sql.NullString  `json:"container_format"`
	Duration            sql.NullFloat64 `json:"duration"`
	Width               sql.NullInt64   `json:"width"`
	Height              sql.NullInt64   `json:"height"`
	AspectRatio         sql.NullString  `json:"aspect_ratio"`
	Codec               sql.NullString  `json:"codec"`
	AudioCodec          sql.NullString  `json:"audio_codec"`
	CodecProfile        sql.NullString  `json:"codec_profile"`
	BitRate             sql.NullInt64   `json:"bit_rate"`
	FrameRate           sql.NullFloat64 `json:"frame_rate"`
	ScanType            sql.NullString  `json:"scan_type"`
	HdrFormat           sql.NullString  `json:"hdr_format"`
	ColorSpace          sql.NullString  `json:"color_space"`
	ColorPrimaries      sql.NullString  `json:"color_primaries"`
	ThumbnailPath       sql.NullString  `json:"thumbnail_path"`
	Type                string          `json:"type"`
	SourceType          sql.NullString  `json:"source_type"`
	ResolutionLabel     sql.NullString  `json:"resolution_label"`
	QualityScore        sql.NullInt64   `json:"quality_score"`
	Is3d                sql.NullInt64   `json:"is_3d"`
	StereoMode          sql.NullString  `json:"stereo_mode"`
	HasDash             sql.NullInt64   `json:"has_dash"`
	DashManifestPath    sql.NullString  `json:"dash_manifest_path"`
	TranscodingStatus   sql.NullString  `json:"transcoding_status"`
	IsExtra             int64           `json:"is_extra"`
	DateAdded           sql.NullTime    `json:"date_added"`
	DateModified        sql.NullTime    `json:"date_modified"`
	CreatedAt           sql.NullTime    `json:"created_at"`
	UpdatedAt           sql.NullTime    `json:"updated_at"`
}

func (q *Queries) GetMusicTrackByMediaID(ctx context.Context, mediaID int64) (GetMusicTrackByMediaIDRow, error) {
	row := q.db.QueryRowContext(ctx, getMusicTrackByMediaID, mediaID)
	var i GetMusicTrackByMediaIDRow
	err := row.Scan(
		&i.MediaID,
		&i.Artist,
		&i.Album,
		&i.AlbumArtist,
		&i.TrackNumber,
		&i.DiscNumber,
		&i.TotalTracks,
		&i.TotalDiscs,
		&i.Genre,
		&i.Year,
		&i.ReleaseDate,
		&i.Composer,
		&i.Lyricist,
		&i.RecordLabel,
		&i.Isrc,
		&i.ReleaseType,
		&i.Compilation,
		&i.MusicbrainzTrackID,
		&i.MusicbrainzAlbumID,
		&i.MusicbrainzArtistID,
		&i.OriginalTitle,
		&i.SortTitle,
		&i.AlbumID,
		&i.ArtistID,
		&i.MediaID_2,
		&i.LibraryID,
		&i.Title,
		&i.FilePath,
		&i.FileSize,
		&i.FileHash,
		&i.ContainerFormat,
		&i.Duration,
		&i.Width,
		&i.Height,
		&i.AspectRatio,
		&i.Codec,
		&i.AudioCodec,
		&i.CodecProfile,
		&i.BitRate,
		&i.FrameRate,
		&i.ScanType,
		&i.HdrFormat,
		&i.ColorSpace,
		&i.ColorPrimaries,
		&i.ThumbnailPath,
		&i.Type,
		&i.SourceType,
		&i.ResolutionLabel,
		&i.QualityScore,
		&i.Is3d,
		&i.StereoMode,
		&i.HasDash,
		&i.DashManifestPath,
		&i.TranscodingStatus,
		&i.IsExtra,
		&i.DateAdded,
		&i.DateModified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAlbumsByLibraryGrouped = `-- name: ListAlbumsByLibraryGrouped :many
SELECT DISTINCT
    mt.album,
    mt.album_artist,
    mt.year,
    COUNT(*) as track_count,
    SUM(med.duration) as total_duration
FROM music_tracks mt
JOIN media med ON mt.media_id = med.id
WHERE med.library_id = $1
GROUP BY mt.album, mt.album_artist, mt.year
ORDER BY mt.album_artist, mt.album
`

type ListAlbumsByLibraryGroupedRow struct {
	Album         sql.NullString `json:"album"`
	AlbumArtist   sql.NullString `json:"album_artist"`
	Year          sql.NullInt64  `json:"year"`
	TrackCount    int64          `json:"track_count"`
	TotalDuration int64          `json:"total_duration"`
}

func (q *Queries) ListAlbumsByLibraryGrouped(ctx context.Context, libraryID int64) ([]ListAlbumsByLibraryGroupedRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlbumsByLibraryGrouped, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlbumsByLibraryGroupedRow{}
	for rows.Next() {
		var i ListAlbumsByLibraryGroupedRow
		if err := rows.Scan(
			&i.Album,
			&i.AlbumArtist,
			&i.Year,
			&i.TrackCount,
			&i.TotalDuration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumsByLibraryPaginated = `-- name: ListAlbumsByLibraryPaginated :many
SELECT DISTINCT
    mt.album,
    mt.album_artist,
    mt.year,
    COUNT(*) as track_count,
    SUM(med.duration) as total_duration
FROM music_tracks mt
JOIN media med ON mt.media_id = med.id
WHERE med.library_id = $1
GROUP BY mt.album, mt.album_artist, mt.year
ORDER BY mt.album_artist ASC, mt.album ASC
LIMIT $2::bigint OFFSET $3::bigint
`

type ListAlbumsByLibraryPaginatedParams struct {
	LibraryID int64 `json:"library_id"`

	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListAlbumsByLibraryPaginatedRow struct {
	Album         sql.NullString `json:"album"`
	AlbumArtist   sql.NullString `json:"album_artist"`
	Year          sql.NullInt64  `json:"year"`
	TrackCount    int64          `json:"track_count"`
	TotalDuration int64          `json:"total_duration"`
}

func (q *Queries) ListAlbumsByLibraryPaginated(ctx context.Context, arg ListAlbumsByLibraryPaginatedParams) ([]ListAlbumsByLibraryPaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlbumsByLibraryPaginated, arg.LibraryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlbumsByLibraryPaginatedRow{}
	for rows.Next() {
		var i ListAlbumsByLibraryPaginatedRow
		if err := rows.Scan(
			&i.Album,
			&i.AlbumArtist,
			&i.Year,
			&i.TrackCount,
			&i.TotalDuration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumsByLibraryPaginatedDesc = `-- name: ListAlbumsByLibraryPaginatedDesc :many
SELECT DISTINCT
    mt.album,
    mt.album_artist,
    mt.year,
    COUNT(*) as track_count,
    SUM(med.duration) as total_duration
FROM music_tracks mt
JOIN media med ON mt.media_id = med.id
WHERE med.library_id = $1
GROUP BY mt.album, mt.album_artist, mt.year
ORDER BY mt.album_artist DESC, mt.album DESC
LIMIT $2::bigint OFFSET $3::bigint
`

type ListAlbumsByLibraryPaginatedDescParams struct {
	LibraryID int64 `json:"library_id"`

	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListAlbumsByLibraryPaginatedDescRow struct {
	Album         sql.NullString `json:"album"`
	AlbumArtist   sql.NullString `json:"album_artist"`
	Year          sql.NullInt64  `json:"year"`
	TrackCount    int64          `json:"track_count"`
	TotalDuration int64          `json:"total_duration"`
}

func (q *Queries) ListAlbumsByLibraryPaginatedDesc(ctx context.Context, arg ListAlbumsByLibraryPaginatedDescParams) ([]ListAlbumsByLibraryPaginatedDescRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlbumsByLibraryPaginatedDesc, arg.LibraryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlbumsByLibraryPaginatedDescRow{}
	for rows.Next() {
		var i ListAlbumsByLibraryPaginatedDescRow
		if err := rows.Scan(
			&i.Album,
			&i.AlbumArtist,
			&i.Year,
			&i.TrackCount,
			&i.TotalDuration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtistIDsByLibraryPaginated = `-- name: ListArtistIDsByLibraryPaginated :many
SELECT mt.media_id as id
FROM music_tracks mt
JOIN media med ON mt.media_id = med.id
WHERE med.library_id = $1
GROUP BY mt.artist
ORDER BY COALESCE(mt.sort_artist, mt.artist) ASC
LIMIT $2::bigint OFFSET $3::bigint
`

type ListArtistIDsByLibraryPaginatedParams struct {
	LibraryID int64 `json:"library_id"`

	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListArtistIDsByLibraryPaginated(ctx context.Context, arg ListArtistIDsByLibraryPaginatedParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listArtistIDsByLibraryPaginated, arg.LibraryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtistIDsByLibraryPaginatedDesc = `-- name: ListArtistIDsByLibraryPaginatedDesc :many
SELECT mt.media_id as id
FROM music_tracks mt
JOIN media med ON mt.media_id = med.id
WHERE med.library_id = $1
GROUP BY mt.artist
ORDER BY COALESCE(mt.sort_artist, mt.artist) DESC
LIMIT $2::bigint OFFSET $3::bigint
`

type ListArtistIDsByLibraryPaginatedDescParams struct {
	LibraryID int64 `json:"library_id"`

	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListArtistIDsByLibraryPaginatedDesc(ctx context.Context, arg ListArtistIDsByLibraryPaginatedDescParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listArtistIDsByLibraryPaginatedDesc, arg.LibraryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMusicTracksByAlbum = `-- name: ListMusicTracksByAlbum :many
SELECT
    mt.media_id, mt.artist, mt.album, mt.album_artist, mt.track_number, mt.disc_number, mt.total_tracks, mt.total_discs, mt.genre, mt.year, mt.release_date, mt.composer, mt.lyricist, mt.record_label, mt.isrc, mt.release_type, mt.compilation, mt.musicbrainz_track_id, mt.musicbrainz_album_id, mt.musicbrainz_artist_id, mt.original_title, mt.sort_title, mt.album_id, mt.artist_id,
    med.id as media_id,
    med.library_id,
    med.title,
    med.file_path,
    med.file_size,
    med.file_hash,
    med.container_format,
    med.duration,
    med.width,
    med.height,
    med.aspect_ratio,
    med.codec,
    med.audio_codec,
    med.codec_profile,
    med.bit_rate,
    med.frame_rate,
    med.scan_type,
    med.hdr_format,
    med.color_space,
    med.color_primaries,
    med.thumbnail_path,
    med.type,
    med.source_type,
    med.resolution_label,
    med.quality_score,
    med.is_3d,
    med.stereo_mode,
    med.has_dash,
    med.dash_manifest_path,
    med.transcoding_status,
    med.is_extra,
    med.date_added,
    med.date_modified,
    med.created_at,
    med.updated_at
FROM music_tracks mt
JOIN media med ON mt.media_id = med.id
WHERE med.library_id = $1 AND mt.album = $2
ORDER BY mt.disc_number, mt.track_number
`

type ListMusicTracksByAlbumParams struct {
	LibraryID int64          `json:"library_id"`
	Album     sql.NullString `json:"album"`
}

type ListMusicTracksByAlbumRow struct {
	MediaID             int64           `json:"media_id"`
	Artist              sql.NullString  `json:"artist"`
	Album               sql.NullString  `json:"album"`
	AlbumArtist         sql.NullString  `json:"album_artist"`
	TrackNumber         sql.NullInt64   `json:"track_number"`
	DiscNumber          sql.NullInt64   `json:"disc_number"`
	TotalTracks         sql.NullInt64   `json:"total_tracks"`
	TotalDiscs          sql.NullInt64   `json:"total_discs"`
	Genre               sql.NullString  `json:"genre"`
	Year                sql.NullInt64   `json:"year"`
	ReleaseDate         sql.NullTime    `json:"release_date"`
	Composer            sql.NullString  `json:"composer"`
	Lyricist            sql.NullString  `json:"lyricist"`
	RecordLabel         sql.NullString  `json:"record_label"`
	Isrc                sql.NullString  `json:"isrc"`
	ReleaseType         sql.NullString  `json:"release_type"`
	Compilation         sql.NullInt64   `json:"compilation"`
	MusicbrainzTrackID  sql.NullString  `json:"musicbrainz_track_id"`
	MusicbrainzAlbumID  sql.NullString  `json:"musicbrainz_album_id"`
	MusicbrainzArtistID sql.NullString  `json:"musicbrainz_artist_id"`
	OriginalTitle       sql.NullString  `json:"original_title"`
	SortTitle           sql.NullString  `json:"sort_title"`
	AlbumID             sql.NullInt64   `json:"album_id"`
	ArtistID            sql.NullInt64   `json:"artist_id"`
	MediaID_2           int64           `json:"media_id_2"`
	LibraryID           int64           `json:"library_id"`
	Title               string          `json:"title"`
	FilePath            string          `json:"file_path"`
	FileSize            sql.NullInt64   `json:"file_size"`
	FileHash            sql.NullString  `json:"file_hash"`
	ContainerFormat     sql.NullString  `json:"container_format"`
	Duration            sql.NullFloat64 `json:"duration"`
	Width               sql.NullInt64   `json:"width"`
	Height              sql.NullInt64   `json:"height"`
	AspectRatio         sql.NullString  `json:"aspect_ratio"`
	Codec               sql.NullString  `json:"codec"`
	AudioCodec          sql.NullString  `json:"audio_codec"`
	CodecProfile        sql.NullString  `json:"codec_profile"`
	BitRate             sql.NullInt64   `json:"bit_rate"`
	FrameRate           sql.NullFloat64 `json:"frame_rate"`
	ScanType            sql.NullString  `json:"scan_type"`
	HdrFormat           sql.NullString  `json:"hdr_format"`
	ColorSpace          sql.NullString  `json:"color_space"`
	ColorPrimaries      sql.NullString  `json:"color_primaries"`
	ThumbnailPath       sql.NullString  `json:"thumbnail_path"`
	Type                string          `json:"type"`
	SourceType          sql.NullString  `json:"source_type"`
	ResolutionLabel     sql.NullString  `json:"resolution_label"`
	QualityScore        sql.NullInt64   `json:"quality_score"`
	Is3d                sql.NullInt64   `json:"is_3d"`
	StereoMode          sql.NullString  `json:"stereo_mode"`
	HasDash             sql.NullInt64   `json:"has_dash"`
	DashManifestPath    sql.NullString  `json:"dash_manifest_path"`
	TranscodingStatus   sql.NullString  `json:"transcoding_status"`
	IsExtra             int64           `json:"is_extra"`
	DateAdded           sql.NullTime    `json:"date_added"`
	DateModified        sql.NullTime    `json:"date_modified"`
	CreatedAt           sql.NullTime    `json:"created_at"`
	UpdatedAt           sql.NullTime    `json:"updated_at"`
}

func (q *Queries) ListMusicTracksByAlbum(ctx context.Context, arg ListMusicTracksByAlbumParams) ([]ListMusicTracksByAlbumRow, error) {
	rows, err := q.db.QueryContext(ctx, listMusicTracksByAlbum, arg.LibraryID, arg.Album)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMusicTracksByAlbumRow{}
	for rows.Next() {
		var i ListMusicTracksByAlbumRow
		if err := rows.Scan(
			&i.MediaID,
			&i.Artist,
			&i.Album,
			&i.AlbumArtist,
			&i.TrackNumber,
			&i.DiscNumber,
			&i.TotalTracks,
			&i.TotalDiscs,
			&i.Genre,
			&i.Year,
			&i.ReleaseDate,
			&i.Composer,
			&i.Lyricist,
			&i.RecordLabel,
			&i.Isrc,
			&i.ReleaseType,
			&i.Compilation,
			&i.MusicbrainzTrackID,
			&i.MusicbrainzAlbumID,
			&i.MusicbrainzArtistID,
			&i.OriginalTitle,
			&i.SortTitle,
			&i.AlbumID,
			&i.ArtistID,
			&i.MediaID_2,
			&i.LibraryID,
			&i.Title,
			&i.FilePath,
			&i.FileSize,
			&i.FileHash,
			&i.ContainerFormat,
			&i.Duration,
			&i.Width,
			&i.Height,
			&i.AspectRatio,
			&i.Codec,
			&i.AudioCodec,
			&i.CodecProfile,
			&i.BitRate,
			&i.FrameRate,
			&i.ScanType,
			&i.HdrFormat,
			&i.ColorSpace,
			&i.ColorPrimaries,
			&i.ThumbnailPath,
			&i.Type,
			&i.SourceType,
			&i.ResolutionLabel,
			&i.QualityScore,
			&i.Is3d,
			&i.StereoMode,
			&i.HasDash,
			&i.DashManifestPath,
			&i.TranscodingStatus,
			&i.IsExtra,
			&i.DateAdded,
			&i.DateModified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMusicTracksByAlbumArtist = `-- name: ListMusicTracksByAlbumArtist :many
SELECT
    mt.media_id, mt.artist, mt.album, mt.album_artist, mt.track_number, mt.disc_number, mt.total_tracks, mt.total_discs, mt.genre, mt.year, mt.release_date, mt.composer, mt.lyricist, mt.record_label, mt.isrc, mt.release_type, mt.compilation, mt.musicbrainz_track_id, mt.musicbrainz_album_id, mt.musicbrainz_artist_id, mt.original_title, mt.sort_title, mt.album_id, mt.artist_id,
    med.id as media_id,
    med.library_id,
    med.title,
    med.file_path,
    med.file_size,
    med.file_hash,
    med.container_format,
    med.duration,
    med.width,
    med.height,
    med.aspect_ratio,
    med.codec,
    med.audio_codec,
    med.codec_profile,
    med.bit_rate,
    med.frame_rate,
    med.scan_type,
    med.hdr_format,
    med.color_space,
    med.color_primaries,
    med.thumbnail_path,
    med.type,
    med.source_type,
    med.resolution_label,
    med.quality_score,
    med.is_3d,
    med.stereo_mode,
    med.has_dash,
    med.dash_manifest_path,
    med.transcoding_status,
    med.is_extra,
    med.date_added,
    med.date_modified,
    med.created_at,
    med.updated_at
FROM music_tracks mt
JOIN media med ON mt.media_id = med.id
WHERE med.library_id = $1 AND mt.album_artist = $2
ORDER BY mt.album, mt.disc_number, mt.track_number
`

type ListMusicTracksByAlbumArtistParams struct {
	LibraryID   int64          `json:"library_id"`
	AlbumArtist sql.NullString `json:"album_artist"`
}

type ListMusicTracksByAlbumArtistRow struct {
	MediaID             int64           `json:"media_id"`
	Artist              sql.NullString  `json:"artist"`
	Album               sql.NullString  `json:"album"`
	AlbumArtist         sql.NullString  `json:"album_artist"`
	TrackNumber         sql.NullInt64   `json:"track_number"`
	DiscNumber          sql.NullInt64   `json:"disc_number"`
	TotalTracks         sql.NullInt64   `json:"total_tracks"`
	TotalDiscs          sql.NullInt64   `json:"total_discs"`
	Genre               sql.NullString  `json:"genre"`
	Year                sql.NullInt64   `json:"year"`
	ReleaseDate         sql.NullTime    `json:"release_date"`
	Composer            sql.NullString  `json:"composer"`
	Lyricist            sql.NullString  `json:"lyricist"`
	RecordLabel         sql.NullString  `json:"record_label"`
	Isrc                sql.NullString  `json:"isrc"`
	ReleaseType         sql.NullString  `json:"release_type"`
	Compilation         sql.NullInt64   `json:"compilation"`
	MusicbrainzTrackID  sql.NullString  `json:"musicbrainz_track_id"`
	MusicbrainzAlbumID  sql.NullString  `json:"musicbrainz_album_id"`
	MusicbrainzArtistID sql.NullString  `json:"musicbrainz_artist_id"`
	OriginalTitle       sql.NullString  `json:"original_title"`
	SortTitle           sql.NullString  `json:"sort_title"`
	AlbumID             sql.NullInt64   `json:"album_id"`
	ArtistID            sql.NullInt64   `json:"artist_id"`
	MediaID_2           int64           `json:"media_id_2"`
	LibraryID           int64           `json:"library_id"`
	Title               string          `json:"title"`
	FilePath            string          `json:"file_path"`
	FileSize            sql.NullInt64   `json:"file_size"`
	FileHash            sql.NullString  `json:"file_hash"`
	ContainerFormat     sql.NullString  `json:"container_format"`
	Duration            sql.NullFloat64 `json:"duration"`
	Width               sql.NullInt64   `json:"width"`
	Height              sql.NullInt64   `json:"height"`
	AspectRatio         sql.NullString  `json:"aspect_ratio"`
	Codec               sql.NullString  `json:"codec"`
	AudioCodec          sql.NullString  `json:"audio_codec"`
	CodecProfile        sql.NullString  `json:"codec_profile"`
	BitRate             sql.NullInt64   `json:"bit_rate"`
	FrameRate           sql.NullFloat64 `json:"frame_rate"`
	ScanType            sql.NullString  `json:"scan_type"`
	HdrFormat           sql.NullString  `json:"hdr_format"`
	ColorSpace          sql.NullString  `json:"color_space"`
	ColorPrimaries      sql.NullString  `json:"color_primaries"`
	ThumbnailPath       sql.NullString  `json:"thumbnail_path"`
	Type                string          `json:"type"`
	SourceType          sql.NullString  `json:"source_type"`
	ResolutionLabel     sql.NullString  `json:"resolution_label"`
	QualityScore        sql.NullInt64   `json:"quality_score"`
	Is3d                sql.NullInt64   `json:"is_3d"`
	StereoMode          sql.NullString  `json:"stereo_mode"`
	HasDash             sql.NullInt64   `json:"has_dash"`
	DashManifestPath    sql.NullString  `json:"dash_manifest_path"`
	TranscodingStatus   sql.NullString  `json:"transcoding_status"`
	IsExtra             int64           `json:"is_extra"`
	DateAdded           sql.NullTime    `json:"date_added"`
	DateModified        sql.NullTime    `json:"date_modified"`
	CreatedAt           sql.NullTime    `json:"created_at"`
	UpdatedAt           sql.NullTime    `json:"updated_at"`
}

func (q *Queries) ListMusicTracksByAlbumArtist(ctx context.Context, arg ListMusicTracksByAlbumArtistParams) ([]ListMusicTracksByAlbumArtistRow, error) {
	rows, err := q.db.QueryContext(ctx, listMusicTracksByAlbumArtist, arg.LibraryID, arg.AlbumArtist)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMusicTracksByAlbumArtistRow{}
	for rows.Next() {
		var i ListMusicTracksByAlbumArtistRow
		if err := rows.Scan(
			&i.MediaID,
			&i.Artist,
			&i.Album,
			&i.AlbumArtist,
			&i.TrackNumber,
			&i.DiscNumber,
			&i.TotalTracks,
			&i.TotalDiscs,
			&i.Genre,
			&i.Year,
			&i.ReleaseDate,
			&i.Composer,
			&i.Lyricist,
			&i.RecordLabel,
			&i.Isrc,
			&i.ReleaseType,
			&i.Compilation,
			&i.MusicbrainzTrackID,
			&i.MusicbrainzAlbumID,
			&i.MusicbrainzArtistID,
			&i.OriginalTitle,
			&i.SortTitle,
			&i.AlbumID,
			&i.ArtistID,
			&i.MediaID_2,
			&i.LibraryID,
			&i.Title,
			&i.FilePath,
			&i.FileSize,
			&i.FileHash,
			&i.ContainerFormat,
			&i.Duration,
			&i.Width,
			&i.Height,
			&i.AspectRatio,
			&i.Codec,
			&i.AudioCodec,
			&i.CodecProfile,
			&i.BitRate,
			&i.FrameRate,
			&i.ScanType,
			&i.HdrFormat,
			&i.ColorSpace,
			&i.ColorPrimaries,
			&i.ThumbnailPath,
			&i.Type,
			&i.SourceType,
			&i.ResolutionLabel,
			&i.QualityScore,
			&i.Is3d,
			&i.StereoMode,
			&i.HasDash,
			&i.DashManifestPath,
			&i.TranscodingStatus,
			&i.IsExtra,
			&i.DateAdded,
			&i.DateModified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMusicTracksByAlbumID = `-- name: ListMusicTracksByAlbumID :many
SELECT
    mt.media_id, mt.artist, mt.album, mt.album_artist, mt.track_number, mt.disc_number, mt.total_tracks, mt.total_discs, mt.genre, mt.year, mt.release_date, mt.composer, mt.lyricist, mt.record_label, mt.isrc, mt.release_type, mt.compilation, mt.musicbrainz_track_id, mt.musicbrainz_album_id, mt.musicbrainz_artist_id, mt.original_title, mt.sort_title, mt.album_id, mt.artist_id,
    med.id as media_id,
    med.library_id,
    med.title,
    med.file_path,
    med.file_size,
    med.file_hash,
    med.container_format,
    med.duration,
    med.width,
    med.height,
    med.aspect_ratio,
    med.codec,
    med.audio_codec,
    med.codec_profile,
    med.bit_rate,
    med.frame_rate,
    med.scan_type,
    med.hdr_format,
    med.color_space,
    med.color_primaries,
    med.thumbnail_path,
    med.type,
    med.source_type,
    med.resolution_label,
    med.quality_score,
    med.is_3d,
    med.stereo_mode,
    med.has_dash,
    med.dash_manifest_path,
    med.transcoding_status,
    med.is_extra,
    med.date_added,
    med.date_modified,
    med.created_at,
    med.updated_at
FROM music_tracks mt
JOIN media med ON mt.media_id = med.id
WHERE mt.album_id = $1
ORDER BY mt.disc_number, mt.track_number
`

type ListMusicTracksByAlbumIDRow struct {
	MediaID             int64           `json:"media_id"`
	Artist              sql.NullString  `json:"artist"`
	Album               sql.NullString  `json:"album"`
	AlbumArtist         sql.NullString  `json:"album_artist"`
	TrackNumber         sql.NullInt64   `json:"track_number"`
	DiscNumber          sql.NullInt64   `json:"disc_number"`
	TotalTracks         sql.NullInt64   `json:"total_tracks"`
	TotalDiscs          sql.NullInt64   `json:"total_discs"`
	Genre               sql.NullString  `json:"genre"`
	Year                sql.NullInt64   `json:"year"`
	ReleaseDate         sql.NullTime    `json:"release_date"`
	Composer            sql.NullString  `json:"composer"`
	Lyricist            sql.NullString  `json:"lyricist"`
	RecordLabel         sql.NullString  `json:"record_label"`
	Isrc                sql.NullString  `json:"isrc"`
	ReleaseType         sql.NullString  `json:"release_type"`
	Compilation         sql.NullInt64   `json:"compilation"`
	MusicbrainzTrackID  sql.NullString  `json:"musicbrainz_track_id"`
	MusicbrainzAlbumID  sql.NullString  `json:"musicbrainz_album_id"`
	MusicbrainzArtistID sql.NullString  `json:"musicbrainz_artist_id"`
	OriginalTitle       sql.NullString  `json:"original_title"`
	SortTitle           sql.NullString  `json:"sort_title"`
	AlbumID             sql.NullInt64   `json:"album_id"`
	ArtistID            sql.NullInt64   `json:"artist_id"`
	MediaID_2           int64           `json:"media_id_2"`
	LibraryID           int64           `json:"library_id"`
	Title               string          `json:"title"`
	FilePath            string          `json:"file_path"`
	FileSize            sql.NullInt64   `json:"file_size"`
	FileHash            sql.NullString  `json:"file_hash"`
	ContainerFormat     sql.NullString  `json:"container_format"`
	Duration            sql.NullFloat64 `json:"duration"`
	Width               sql.NullInt64   `json:"width"`
	Height              sql.NullInt64   `json:"height"`
	AspectRatio         sql.NullString  `json:"aspect_ratio"`
	Codec               sql.NullString  `json:"codec"`
	AudioCodec          sql.NullString  `json:"audio_codec"`
	CodecProfile        sql.NullString  `json:"codec_profile"`
	BitRate             sql.NullInt64   `json:"bit_rate"`
	FrameRate           sql.NullFloat64 `json:"frame_rate"`
	ScanType            sql.NullString  `json:"scan_type"`
	HdrFormat           sql.NullString  `json:"hdr_format"`
	ColorSpace          sql.NullString  `json:"color_space"`
	ColorPrimaries      sql.NullString  `json:"color_primaries"`
	ThumbnailPath       sql.NullString  `json:"thumbnail_path"`
	Type                string          `json:"type"`
	SourceType          sql.NullString  `json:"source_type"`
	ResolutionLabel     sql.NullString  `json:"resolution_label"`
	QualityScore        sql.NullInt64   `json:"quality_score"`
	Is3d                sql.NullInt64   `json:"is_3d"`
	StereoMode          sql.NullString  `json:"stereo_mode"`
	HasDash             sql.NullInt64   `json:"has_dash"`
	DashManifestPath    sql.NullString  `json:"dash_manifest_path"`
	TranscodingStatus   sql.NullString  `json:"transcoding_status"`
	IsExtra             int64           `json:"is_extra"`
	DateAdded           sql.NullTime    `json:"date_added"`
	DateModified        sql.NullTime    `json:"date_modified"`
	CreatedAt           sql.NullTime    `json:"created_at"`
	UpdatedAt           sql.NullTime    `json:"updated_at"`
}

func (q *Queries) ListMusicTracksByAlbumID(ctx context.Context, albumID sql.NullInt64) ([]ListMusicTracksByAlbumIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listMusicTracksByAlbumID, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMusicTracksByAlbumIDRow{}
	for rows.Next() {
		var i ListMusicTracksByAlbumIDRow
		if err := rows.Scan(
			&i.MediaID,
			&i.Artist,
			&i.Album,
			&i.AlbumArtist,
			&i.TrackNumber,
			&i.DiscNumber,
			&i.TotalTracks,
			&i.TotalDiscs,
			&i.Genre,
			&i.Year,
			&i.ReleaseDate,
			&i.Composer,
			&i.Lyricist,
			&i.RecordLabel,
			&i.Isrc,
			&i.ReleaseType,
			&i.Compilation,
			&i.MusicbrainzTrackID,
			&i.MusicbrainzAlbumID,
			&i.MusicbrainzArtistID,
			&i.OriginalTitle,
			&i.SortTitle,
			&i.AlbumID,
			&i.ArtistID,
			&i.MediaID_2,
			&i.LibraryID,
			&i.Title,
			&i.FilePath,
			&i.FileSize,
			&i.FileHash,
			&i.ContainerFormat,
			&i.Duration,
			&i.Width,
			&i.Height,
			&i.AspectRatio,
			&i.Codec,
			&i.AudioCodec,
			&i.CodecProfile,
			&i.BitRate,
			&i.FrameRate,
			&i.ScanType,
			&i.HdrFormat,
			&i.ColorSpace,
			&i.ColorPrimaries,
			&i.ThumbnailPath,
			&i.Type,
			&i.SourceType,
			&i.ResolutionLabel,
			&i.QualityScore,
			&i.Is3d,
			&i.StereoMode,
			&i.HasDash,
			&i.DashManifestPath,
			&i.TranscodingStatus,
			&i.IsExtra,
			&i.DateAdded,
			&i.DateModified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMusicTracksByArtist = `-- name: ListMusicTracksByArtist :many
SELECT
    mt.media_id, mt.artist, mt.album, mt.album_artist, mt.track_number, mt.disc_number, mt.total_tracks, mt.total_discs, mt.genre, mt.year, mt.release_date, mt.composer, mt.lyricist, mt.record_label, mt.isrc, mt.release_type, mt.compilation, mt.musicbrainz_track_id, mt.musicbrainz_album_id, mt.musicbrainz_artist_id, mt.original_title, mt.sort_title, mt.album_id, mt.artist_id,
    med.id as media_id,
    med.library_id,
    med.title,
    med.file_path,
    med.file_size,
    med.file_hash,
    med.container_format,
    med.duration,
    med.width,
    med.height,
    med.aspect_ratio,
    med.codec,
    med.audio_codec,
    med.codec_profile,
    med.bit_rate,
    med.frame_rate,
    med.scan_type,
    med.hdr_format,
    med.color_space,
    med.color_primaries,
    med.thumbnail_path,
    med.type,
    med.source_type,
    med.resolution_label,
    med.quality_score,
    med.is_3d,
    med.stereo_mode,
    med.has_dash,
    med.dash_manifest_path,
    med.transcoding_status,
    med.is_extra,
    med.date_added,
    med.date_modified,
    med.created_at,
    med.updated_at
FROM music_tracks mt
JOIN media med ON mt.media_id = med.id
WHERE med.library_id = $1
  AND (mt.artist ILIKE $2 OR mt.album_artist ILIKE $3)
ORDER BY mt.album, mt.disc_number, mt.track_number
`

type ListMusicTracksByArtistParams struct {
	LibraryID   int64          `json:"library_id"`
	Artist      sql.NullString `json:"artist"`
	AlbumArtist sql.NullString `json:"album_artist"`
}

type ListMusicTracksByArtistRow struct {
	MediaID             int64           `json:"media_id"`
	Artist              sql.NullString  `json:"artist"`
	Album               sql.NullString  `json:"album"`
	AlbumArtist         sql.NullString  `json:"album_artist"`
	TrackNumber         sql.NullInt64   `json:"track_number"`
	DiscNumber          sql.NullInt64   `json:"disc_number"`
	TotalTracks         sql.NullInt64   `json:"total_tracks"`
	TotalDiscs          sql.NullInt64   `json:"total_discs"`
	Genre               sql.NullString  `json:"genre"`
	Year                sql.NullInt64   `json:"year"`
	ReleaseDate         sql.NullTime    `json:"release_date"`
	Composer            sql.NullString  `json:"composer"`
	Lyricist            sql.NullString  `json:"lyricist"`
	RecordLabel         sql.NullString  `json:"record_label"`
	Isrc                sql.NullString  `json:"isrc"`
	ReleaseType         sql.NullString  `json:"release_type"`
	Compilation         sql.NullInt64   `json:"compilation"`
	MusicbrainzTrackID  sql.NullString  `json:"musicbrainz_track_id"`
	MusicbrainzAlbumID  sql.NullString  `json:"musicbrainz_album_id"`
	MusicbrainzArtistID sql.NullString  `json:"musicbrainz_artist_id"`
	OriginalTitle       sql.NullString  `json:"original_title"`
	SortTitle           sql.NullString  `json:"sort_title"`
	AlbumID             sql.NullInt64   `json:"album_id"`
	ArtistID            sql.NullInt64   `json:"artist_id"`
	MediaID_2           int64           `json:"media_id_2"`
	LibraryID           int64           `json:"library_id"`
	Title               string          `json:"title"`
	FilePath            string          `json:"file_path"`
	FileSize            sql.NullInt64   `json:"file_size"`
	FileHash            sql.NullString  `json:"file_hash"`
	ContainerFormat     sql.NullString  `json:"container_format"`
	Duration            sql.NullFloat64 `json:"duration"`
	Width               sql.NullInt64   `json:"width"`
	Height              sql.NullInt64   `json:"height"`
	AspectRatio         sql.NullString  `json:"aspect_ratio"`
	Codec               sql.NullString  `json:"codec"`
	AudioCodec          sql.NullString  `json:"audio_codec"`
	CodecProfile        sql.NullString  `json:"codec_profile"`
	BitRate             sql.NullInt64   `json:"bit_rate"`
	FrameRate           sql.NullFloat64 `json:"frame_rate"`
	ScanType            sql.NullString  `json:"scan_type"`
	HdrFormat           sql.NullString  `json:"hdr_format"`
	ColorSpace          sql.NullString  `json:"color_space"`
	ColorPrimaries      sql.NullString  `json:"color_primaries"`
	ThumbnailPath       sql.NullString  `json:"thumbnail_path"`
	Type                string          `json:"type"`
	SourceType          sql.NullString  `json:"source_type"`
	ResolutionLabel     sql.NullString  `json:"resolution_label"`
	QualityScore        sql.NullInt64   `json:"quality_score"`
	Is3d                sql.NullInt64   `json:"is_3d"`
	StereoMode          sql.NullString  `json:"stereo_mode"`
	HasDash             sql.NullInt64   `json:"has_dash"`
	DashManifestPath    sql.NullString  `json:"dash_manifest_path"`
	TranscodingStatus   sql.NullString  `json:"transcoding_status"`
	IsExtra             int64           `json:"is_extra"`
	DateAdded           sql.NullTime    `json:"date_added"`
	DateModified        sql.NullTime    `json:"date_modified"`
	CreatedAt           sql.NullTime    `json:"created_at"`
	UpdatedAt           sql.NullTime    `json:"updated_at"`
}

func (q *Queries) ListMusicTracksByArtist(ctx context.Context, arg ListMusicTracksByArtistParams) ([]ListMusicTracksByArtistRow, error) {
	rows, err := q.db.QueryContext(ctx, listMusicTracksByArtist, arg.LibraryID, arg.Artist, arg.AlbumArtist)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMusicTracksByArtistRow{}
	for rows.Next() {
		var i ListMusicTracksByArtistRow
		if err := rows.Scan(
			&i.MediaID,
			&i.Artist,
			&i.Album,
			&i.AlbumArtist,
			&i.TrackNumber,
			&i.DiscNumber,
			&i.TotalTracks,
			&i.TotalDiscs,
			&i.Genre,
			&i.Year,
			&i.ReleaseDate,
			&i.Composer,
			&i.Lyricist,
			&i.RecordLabel,
			&i.Isrc,
			&i.ReleaseType,
			&i.Compilation,
			&i.MusicbrainzTrackID,
			&i.MusicbrainzAlbumID,
			&i.MusicbrainzArtistID,
			&i.OriginalTitle,
			&i.SortTitle,
			&i.AlbumID,
			&i.ArtistID,
			&i.MediaID_2,
			&i.LibraryID,
			&i.Title,
			&i.FilePath,
			&i.FileSize,
			&i.FileHash,
			&i.ContainerFormat,
			&i.Duration,
			&i.Width,
			&i.Height,
			&i.AspectRatio,
			&i.Codec,
			&i.AudioCodec,
			&i.CodecProfile,
			&i.BitRate,
			&i.FrameRate,
			&i.ScanType,
			&i.HdrFormat,
			&i.ColorSpace,
			&i.ColorPrimaries,
			&i.ThumbnailPath,
			&i.Type,
			&i.SourceType,
			&i.ResolutionLabel,
			&i.QualityScore,
			&i.Is3d,
			&i.StereoMode,
			&i.HasDash,
			&i.DashManifestPath,
			&i.TranscodingStatus,
			&i.IsExtra,
			&i.DateAdded,
			&i.DateModified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMusicTracksByLibrary = `-- name: ListMusicTracksByLibrary :many
SELECT
    mt.media_id, mt.artist, mt.album, mt.album_artist, mt.track_number, mt.disc_number, mt.total_tracks, mt.total_discs, mt.genre, mt.year, mt.release_date, mt.composer, mt.lyricist, mt.record_label, mt.isrc, mt.release_type, mt.compilation, mt.musicbrainz_track_id, mt.musicbrainz_album_id, mt.musicbrainz_artist_id, mt.original_title, mt.sort_title, mt.album_id, mt.artist_id,
    med.id as media_id,
    med.library_id,
    med.title,
    med.file_path,
    med.file_size,
    med.file_hash,
    med.container_format,
    med.duration,
    med.width,
    med.height,
    med.aspect_ratio,
    med.codec,
    med.audio_codec,
    med.codec_profile,
    med.bit_rate,
    med.frame_rate,
    med.scan_type,
    med.hdr_format,
    med.color_space,
    med.color_primaries,
    med.thumbnail_path,
    med.type,
    med.source_type,
    med.resolution_label,
    med.quality_score,
    med.is_3d,
    med.stereo_mode,
    med.has_dash,
    med.dash_manifest_path,
    med.transcoding_status,
    med.is_extra,
    med.date_added,
    med.date_modified,
    med.created_at,
    med.updated_at
FROM music_tracks mt
JOIN media med ON mt.media_id = med.id
WHERE med.library_id = $1
ORDER BY mt.album_artist, mt.album, mt.disc_number, mt.track_number
`

type ListMusicTracksByLibraryRow struct {
	MediaID             int64           `json:"media_id"`
	Artist              sql.NullString  `json:"artist"`
	Album               sql.NullString  `json:"album"`
	AlbumArtist         sql.NullString  `json:"album_artist"`
	TrackNumber         sql.NullInt64   `json:"track_number"`
	DiscNumber          sql.NullInt64   `json:"disc_number"`
	TotalTracks         sql.NullInt64   `json:"total_tracks"`
	TotalDiscs          sql.NullInt64   `json:"total_discs"`
	Genre               sql.NullString  `json:"genre"`
	Year                sql.NullInt64   `json:"year"`
	ReleaseDate         sql.NullTime    `json:"release_date"`
	Composer            sql.NullString  `json:"composer"`
	Lyricist            sql.NullString  `json:"lyricist"`
	RecordLabel         sql.NullString  `json:"record_label"`
	Isrc                sql.NullString  `json:"isrc"`
	ReleaseType         sql.NullString  `json:"release_type"`
	Compilation         sql.NullInt64   `json:"compilation"`
	MusicbrainzTrackID  sql.NullString  `json:"musicbrainz_track_id"`
	MusicbrainzAlbumID  sql.NullString  `json:"musicbrainz_album_id"`
	MusicbrainzArtistID sql.NullString  `json:"musicbrainz_artist_id"`
	OriginalTitle       sql.NullString  `json:"original_title"`
	SortTitle           sql.NullString  `json:"sort_title"`
	AlbumID             sql.NullInt64   `json:"album_id"`
	ArtistID            sql.NullInt64   `json:"artist_id"`
	MediaID_2           int64           `json:"media_id_2"`
	LibraryID           int64           `json:"library_id"`
	Title               string          `json:"title"`
	FilePath            string          `json:"file_path"`
	FileSize            sql.NullInt64   `json:"file_size"`
	FileHash            sql.NullString  `json:"file_hash"`
	ContainerFormat     sql.NullString  `json:"container_format"`
	Duration            sql.NullFloat64 `json:"duration"`
	Width               sql.NullInt64   `json:"width"`
	Height              sql.NullInt64   `json:"height"`
	AspectRatio         sql.NullString  `json:"aspect_ratio"`
	Codec               sql.NullString  `json:"codec"`
	AudioCodec          sql.NullString  `json:"audio_codec"`
	CodecProfile        sql.NullString  `json:"codec_profile"`
	BitRate             sql.NullInt64   `json:"bit_rate"`
	FrameRate           sql.NullFloat64 `json:"frame_rate"`
	ScanType            sql.NullString  `json:"scan_type"`
	HdrFormat           sql.NullString  `json:"hdr_format"`
	ColorSpace          sql.NullString  `json:"color_space"`
	ColorPrimaries      sql.NullString  `json:"color_primaries"`
	ThumbnailPath       sql.NullString  `json:"thumbnail_path"`
	Type                string          `json:"type"`
	SourceType          sql.NullString  `json:"source_type"`
	ResolutionLabel     sql.NullString  `json:"resolution_label"`
	QualityScore        sql.NullInt64   `json:"quality_score"`
	Is3d                sql.NullInt64   `json:"is_3d"`
	StereoMode          sql.NullString  `json:"stereo_mode"`
	HasDash             sql.NullInt64   `json:"has_dash"`
	DashManifestPath    sql.NullString  `json:"dash_manifest_path"`
	TranscodingStatus   sql.NullString  `json:"transcoding_status"`
	IsExtra             int64           `json:"is_extra"`
	DateAdded           sql.NullTime    `json:"date_added"`
	DateModified        sql.NullTime    `json:"date_modified"`
	CreatedAt           sql.NullTime    `json:"created_at"`
	UpdatedAt           sql.NullTime    `json:"updated_at"`
}

func (q *Queries) ListMusicTracksByLibrary(ctx context.Context, libraryID int64) ([]ListMusicTracksByLibraryRow, error) {
	rows, err := q.db.QueryContext(ctx, listMusicTracksByLibrary, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMusicTracksByLibraryRow{}
	for rows.Next() {
		var i ListMusicTracksByLibraryRow
		if err := rows.Scan(
			&i.MediaID,
			&i.Artist,
			&i.Album,
			&i.AlbumArtist,
			&i.TrackNumber,
			&i.DiscNumber,
			&i.TotalTracks,
			&i.TotalDiscs,
			&i.Genre,
			&i.Year,
			&i.ReleaseDate,
			&i.Composer,
			&i.Lyricist,
			&i.RecordLabel,
			&i.Isrc,
			&i.ReleaseType,
			&i.Compilation,
			&i.MusicbrainzTrackID,
			&i.MusicbrainzAlbumID,
			&i.MusicbrainzArtistID,
			&i.OriginalTitle,
			&i.SortTitle,
			&i.AlbumID,
			&i.ArtistID,
			&i.MediaID_2,
			&i.LibraryID,
			&i.Title,
			&i.FilePath,
			&i.FileSize,
			&i.FileHash,
			&i.ContainerFormat,
			&i.Duration,
			&i.Width,
			&i.Height,
			&i.AspectRatio,
			&i.Codec,
			&i.AudioCodec,
			&i.CodecProfile,
			&i.BitRate,
			&i.FrameRate,
			&i.ScanType,
			&i.HdrFormat,
			&i.ColorSpace,
			&i.ColorPrimaries,
			&i.ThumbnailPath,
			&i.Type,
			&i.SourceType,
			&i.ResolutionLabel,
			&i.QualityScore,
			&i.Is3d,
			&i.StereoMode,
			&i.HasDash,
			&i.DashManifestPath,
			&i.TranscodingStatus,
			&i.IsExtra,
			&i.DateAdded,
			&i.DateModified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMusicTracksByLibraryPaginated = `-- name: ListMusicTracksByLibraryPaginated :many
SELECT
    mt.media_id, mt.artist, mt.album, mt.album_artist, mt.track_number, mt.disc_number, mt.total_tracks, mt.total_discs, mt.genre, mt.year, mt.release_date, mt.composer, mt.lyricist, mt.record_label, mt.isrc, mt.release_type, mt.compilation, mt.musicbrainz_track_id, mt.musicbrainz_album_id, mt.musicbrainz_artist_id, mt.original_title, mt.sort_title, mt.album_id, mt.artist_id,
    med.id as media_id,
    med.library_id,
    med.title,
    med.file_path,
    med.file_size,
    med.file_hash,
    med.container_format,
    med.duration,
    med.width,
    med.height,
    med.aspect_ratio,
    med.codec,
    med.audio_codec,
    med.codec_profile,
    med.bit_rate,
    med.frame_rate,
    med.scan_type,
    med.hdr_format,
    med.color_space,
    med.color_primaries,
    med.thumbnail_path,
    med.type,
    med.source_type,
    med.resolution_label,
    med.quality_score,
    med.is_3d,
    med.stereo_mode,
    med.has_dash,
    med.dash_manifest_path,
    med.transcoding_status,
    med.is_extra,
    med.date_added,
    med.date_modified,
    med.created_at,
    med.updated_at
FROM music_tracks mt
JOIN media med ON mt.media_id = med.id
WHERE med.library_id = $1
ORDER BY COALESCE(mt.sort_title, med.title) ASC
LIMIT $2::bigint OFFSET $3::bigint
`

type ListMusicTracksByLibraryPaginatedParams struct {
	LibraryID int64 `json:"library_id"`

	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListMusicTracksByLibraryPaginatedRow struct {
	MediaID             int64           `json:"media_id"`
	Artist              sql.NullString  `json:"artist"`
	Album               sql.NullString  `json:"album"`
	AlbumArtist         sql.NullString  `json:"album_artist"`
	TrackNumber         sql.NullInt64   `json:"track_number"`
	DiscNumber          sql.NullInt64   `json:"disc_number"`
	TotalTracks         sql.NullInt64   `json:"total_tracks"`
	TotalDiscs          sql.NullInt64   `json:"total_discs"`
	Genre               sql.NullString  `json:"genre"`
	Year                sql.NullInt64   `json:"year"`
	ReleaseDate         sql.NullTime    `json:"release_date"`
	Composer            sql.NullString  `json:"composer"`
	Lyricist            sql.NullString  `json:"lyricist"`
	RecordLabel         sql.NullString  `json:"record_label"`
	Isrc                sql.NullString  `json:"isrc"`
	ReleaseType         sql.NullString  `json:"release_type"`
	Compilation         sql.NullInt64   `json:"compilation"`
	MusicbrainzTrackID  sql.NullString  `json:"musicbrainz_track_id"`
	MusicbrainzAlbumID  sql.NullString  `json:"musicbrainz_album_id"`
	MusicbrainzArtistID sql.NullString  `json:"musicbrainz_artist_id"`
	OriginalTitle       sql.NullString  `json:"original_title"`
	SortTitle           sql.NullString  `json:"sort_title"`
	AlbumID             sql.NullInt64   `json:"album_id"`
	ArtistID            sql.NullInt64   `json:"artist_id"`
	MediaID_2           int64           `json:"media_id_2"`
	LibraryID           int64           `json:"library_id"`
	Title               string          `json:"title"`
	FilePath            string          `json:"file_path"`
	FileSize            sql.NullInt64   `json:"file_size"`
	FileHash            sql.NullString  `json:"file_hash"`
	ContainerFormat     sql.NullString  `json:"container_format"`
	Duration            sql.NullFloat64 `json:"duration"`
	Width               sql.NullInt64   `json:"width"`
	Height              sql.NullInt64   `json:"height"`
	AspectRatio         sql.NullString  `json:"aspect_ratio"`
	Codec               sql.NullString  `json:"codec"`
	AudioCodec          sql.NullString  `json:"audio_codec"`
	CodecProfile        sql.NullString  `json:"codec_profile"`
	BitRate             sql.NullInt64   `json:"bit_rate"`
	FrameRate           sql.NullFloat64 `json:"frame_rate"`
	ScanType            sql.NullString  `json:"scan_type"`
	HdrFormat           sql.NullString  `json:"hdr_format"`
	ColorSpace          sql.NullString  `json:"color_space"`
	ColorPrimaries      sql.NullString  `json:"color_primaries"`
	ThumbnailPath       sql.NullString  `json:"thumbnail_path"`
	Type                string          `json:"type"`
	SourceType          sql.NullString  `json:"source_type"`
	ResolutionLabel     sql.NullString  `json:"resolution_label"`
	QualityScore        sql.NullInt64   `json:"quality_score"`
	Is3d                sql.NullInt64   `json:"is_3d"`
	StereoMode          sql.NullString  `json:"stereo_mode"`
	HasDash             sql.NullInt64   `json:"has_dash"`
	DashManifestPath    sql.NullString  `json:"dash_manifest_path"`
	TranscodingStatus   sql.NullString  `json:"transcoding_status"`
	IsExtra             int64           `json:"is_extra"`
	DateAdded           sql.NullTime    `json:"date_added"`
	DateModified        sql.NullTime    `json:"date_modified"`
	CreatedAt           sql.NullTime    `json:"created_at"`
	UpdatedAt           sql.NullTime    `json:"updated_at"`
}

func (q *Queries) ListMusicTracksByLibraryPaginated(ctx context.Context, arg ListMusicTracksByLibraryPaginatedParams) ([]ListMusicTracksByLibraryPaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, listMusicTracksByLibraryPaginated, arg.LibraryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMusicTracksByLibraryPaginatedRow{}
	for rows.Next() {
		var i ListMusicTracksByLibraryPaginatedRow
		if err := rows.Scan(
			&i.MediaID,
			&i.Artist,
			&i.Album,
			&i.AlbumArtist,
			&i.TrackNumber,
			&i.DiscNumber,
			&i.TotalTracks,
			&i.TotalDiscs,
			&i.Genre,
			&i.Year,
			&i.ReleaseDate,
			&i.Composer,
			&i.Lyricist,
			&i.RecordLabel,
			&i.Isrc,
			&i.ReleaseType,
			&i.Compilation,
			&i.MusicbrainzTrackID,
			&i.MusicbrainzAlbumID,
			&i.MusicbrainzArtistID,
			&i.OriginalTitle,
			&i.SortTitle,
			&i.AlbumID,
			&i.ArtistID,
			&i.MediaID_2,
			&i.LibraryID,
			&i.Title,
			&i.FilePath,
			&i.FileSize,
			&i.FileHash,
			&i.ContainerFormat,
			&i.Duration,
			&i.Width,
			&i.Height,
			&i.AspectRatio,
			&i.Codec,
			&i.AudioCodec,
			&i.CodecProfile,
			&i.BitRate,
			&i.FrameRate,
			&i.ScanType,
			&i.HdrFormat,
			&i.ColorSpace,
			&i.ColorPrimaries,
			&i.ThumbnailPath,
			&i.Type,
			&i.SourceType,
			&i.ResolutionLabel,
			&i.QualityScore,
			&i.Is3d,
			&i.StereoMode,
			&i.HasDash,
			&i.DashManifestPath,
			&i.TranscodingStatus,
			&i.IsExtra,
			&i.DateAdded,
			&i.DateModified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMusicTracksByLibraryPaginatedDesc = `-- name: ListMusicTracksByLibraryPaginatedDesc :many
SELECT
    mt.media_id, mt.artist, mt.album, mt.album_artist, mt.track_number, mt.disc_number, mt.total_tracks, mt.total_discs, mt.genre, mt.year, mt.release_date, mt.composer, mt.lyricist, mt.record_label, mt.isrc, mt.release_type, mt.compilation, mt.musicbrainz_track_id, mt.musicbrainz_album_id, mt.musicbrainz_artist_id, mt.original_title, mt.sort_title, mt.album_id, mt.artist_id,
    med.id as media_id,
    med.library_id,
    med.title,
    med.file_path,
    med.file_size,
    med.file_hash,
    med.container_format,
    med.duration,
    med.width,
    med.height,
    med.aspect_ratio,
    med.codec,
    med.audio_codec,
    med.codec_profile,
    med.bit_rate,
    med.frame_rate,
    med.scan_type,
    med.hdr_format,
    med.color_space,
    med.color_primaries,
    med.thumbnail_path,
    med.type,
    med.source_type,
    med.resolution_label,
    med.quality_score,
    med.is_3d,
    med.stereo_mode,
    med.has_dash,
    med.dash_manifest_path,
    med.transcoding_status,
    med.is_extra,
    med.date_added,
    med.date_modified,
    med.created_at,
    med.updated_at
FROM music_tracks mt
JOIN media med ON mt.media_id = med.id
WHERE med.library_id = $1
ORDER BY COALESCE(mt.sort_title, med.title) DESC
LIMIT $2::bigint OFFSET $3::bigint
`

type ListMusicTracksByLibraryPaginatedDescParams struct {
	LibraryID int64 `json:"library_id"`

	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListMusicTracksByLibraryPaginatedDescRow struct {
	MediaID             int64           `json:"media_id"`
	Artist              sql.NullString  `json:"artist"`
	Album               sql.NullString  `json:"album"`
	AlbumArtist         sql.NullString  `json:"album_artist"`
	TrackNumber         sql.NullInt64   `json:"track_number"`
	DiscNumber          sql.NullInt64   `json:"disc_number"`
	TotalTracks         sql.NullInt64   `json:"total_tracks"`
	TotalDiscs          sql.NullInt64   `json:"total_discs"`
	Genre               sql.NullString  `json:"genre"`
	Year                sql.NullInt64   `json:"year"`
	ReleaseDate         sql.NullTime    `json:"release_date"`
	Composer            sql.NullString  `json:"composer"`
	Lyricist            sql.NullString  `json:"lyricist"`
	RecordLabel         sql.NullString  `json:"record_label"`
	Isrc                sql.NullString  `json:"isrc"`
	ReleaseType         sql.NullString  `json:"release_type"`
	Compilation         sql.NullInt64   `json:"compilation"`
	MusicbrainzTrackID  sql.NullString  `json:"musicbrainz_track_id"`
	MusicbrainzAlbumID  sql.NullString  `json:"musicbrainz_album_id"`
	MusicbrainzArtistID sql.NullString  `json:"musicbrainz_artist_id"`
	OriginalTitle       sql.NullString  `json:"original_title"`
	SortTitle           sql.NullString  `json:"sort_title"`
	AlbumID             sql.NullInt64   `json:"album_id"`
	ArtistID            sql.NullInt64   `json:"artist_id"`
	MediaID_2           int64           `json:"media_id_2"`
	LibraryID           int64           `json:"library_id"`
	Title               string          `json:"title"`
	FilePath            string          `json:"file_path"`
	FileSize            sql.NullInt64   `json:"file_size"`
	FileHash            sql.NullString  `json:"file_hash"`
	ContainerFormat     sql.NullString  `json:"container_format"`
	Duration            sql.NullFloat64 `json:"duration"`
	Width               sql.NullInt64   `json:"width"`
	Height              sql.NullInt64   `json:"height"`
	AspectRatio         sql.NullString  `json:"aspect_ratio"`
	Codec               sql.NullString  `json:"codec"`
	AudioCodec          sql.NullString  `json:"audio_codec"`
	CodecProfile        sql.NullString  `json:"codec_profile"`
	BitRate             sql.NullInt64   `json:"bit_rate"`
	FrameRate           sql.NullFloat64 `json:"frame_rate"`
	ScanType            sql.NullString  `json:"scan_type"`
	HdrFormat           sql.NullString  `json:"hdr_format"`
	ColorSpace          sql.NullString  `json:"color_space"`
	ColorPrimaries      sql.NullString  `json:"color_primaries"`
	ThumbnailPath       sql.NullString  `json:"thumbnail_path"`
	Type                string          `json:"type"`
	SourceType          sql.NullString  `json:"source_type"`
	ResolutionLabel     sql.NullString  `json:"resolution_label"`
	QualityScore        sql.NullInt64   `json:"quality_score"`
	Is3d                sql.NullInt64   `json:"is_3d"`
	StereoMode          sql.NullString  `json:"stereo_mode"`
	HasDash             sql.NullInt64   `json:"has_dash"`
	DashManifestPath    sql.NullString  `json:"dash_manifest_path"`
	TranscodingStatus   sql.NullString  `json:"transcoding_status"`
	IsExtra             int64           `json:"is_extra"`
	DateAdded           sql.NullTime    `json:"date_added"`
	DateModified        sql.NullTime    `json:"date_modified"`
	CreatedAt           sql.NullTime    `json:"created_at"`
	UpdatedAt           sql.NullTime    `json:"updated_at"`
}

func (q *Queries) ListMusicTracksByLibraryPaginatedDesc(ctx context.Context, arg ListMusicTracksByLibraryPaginatedDescParams) ([]ListMusicTracksByLibraryPaginatedDescRow, error) {
	rows, err := q.db.QueryContext(ctx, listMusicTracksByLibraryPaginatedDesc, arg.LibraryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMusicTracksByLibraryPaginatedDescRow{}
	for rows.Next() {
		var i ListMusicTracksByLibraryPaginatedDescRow
		if err := rows.Scan(
			&i.MediaID,
			&i.Artist,
			&i.Album,
			&i.AlbumArtist,
			&i.TrackNumber,
			&i.DiscNumber,
			&i.TotalTracks,
			&i.TotalDiscs,
			&i.Genre,
			&i.Year,
			&i.ReleaseDate,
			&i.Composer,
			&i.Lyricist,
			&i.RecordLabel,
			&i.Isrc,
			&i.ReleaseType,
			&i.Compilation,
			&i.MusicbrainzTrackID,
			&i.MusicbrainzAlbumID,
			&i.MusicbrainzArtistID,
			&i.OriginalTitle,
			&i.SortTitle,
			&i.AlbumID,
			&i.ArtistID,
			&i.MediaID_2,
			&i.LibraryID,
			&i.Title,
			&i.FilePath,
			&i.FileSize,
			&i.FileHash,
			&i.ContainerFormat,
			&i.Duration,
			&i.Width,
			&i.Height,
			&i.AspectRatio,
			&i.Codec,
			&i.AudioCodec,
			&i.CodecProfile,
			&i.BitRate,
			&i.FrameRate,
			&i.ScanType,
			&i.HdrFormat,
			&i.ColorSpace,
			&i.ColorPrimaries,
			&i.ThumbnailPath,
			&i.Type,
			&i.SourceType,
			&i.ResolutionLabel,
			&i.QualityScore,
			&i.Is3d,
			&i.StereoMode,
			&i.HasDash,
			&i.DashManifestPath,
			&i.TranscodingStatus,
			&i.IsExtra,
			&i.DateAdded,
			&i.DateModified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMusicTracks = `-- name: SearchMusicTracks :many
SELECT
    mt.media_id, mt.artist, mt.album, mt.album_artist, mt.track_number, mt.disc_number, mt.total_tracks, mt.total_discs, mt.genre, mt.year, mt.release_date, mt.composer, mt.lyricist, mt.record_label, mt.isrc, mt.release_type, mt.compilation, mt.musicbrainz_track_id, mt.musicbrainz_album_id, mt.musicbrainz_artist_id, mt.original_title, mt.sort_title, mt.album_id, mt.artist_id,
    med.id as media_id,
    med.library_id,
    med.title,
    med.file_path,
    med.file_size,
    med.file_hash,
    med.container_format,
    med.duration,
    med.width,
    med.height,
    med.aspect_ratio,
    med.codec,
    med.audio_codec,
    med.codec_profile,
    med.bit_rate,
    med.frame_rate,
    med.scan_type,
    med.hdr_format,
    med.color_space,
    med.color_primaries,
    med.thumbnail_path,
    med.type,
    med.source_type,
    med.resolution_label,
    med.quality_score,
    med.is_3d,
    med.stereo_mode,
    med.has_dash,
    med.dash_manifest_path,
    med.transcoding_status,
    med.is_extra,
    med.date_added,
    med.date_modified,
    med.created_at,
    med.updated_at
FROM music_tracks mt
JOIN media med ON mt.media_id = med.id
WHERE med.library_id = $1
  AND (med.title ILIKE $2 OR mt.artist ILIKE $3 OR mt.album ILIKE $4)
ORDER BY mt.album_artist, mt.album, mt.disc_number, mt.track_number
`

type SearchMusicTracksParams struct {
	LibraryID int64          `json:"library_id"`
	Title     string         `json:"title"`
	Artist    sql.NullString `json:"artist"`
	Album     sql.NullString `json:"album"`
}

type SearchMusicTracksRow struct {
	MediaID             int64           `json:"media_id"`
	Artist              sql.NullString  `json:"artist"`
	Album               sql.NullString  `json:"album"`
	AlbumArtist         sql.NullString  `json:"album_artist"`
	TrackNumber         sql.NullInt64   `json:"track_number"`
	DiscNumber          sql.NullInt64   `json:"disc_number"`
	TotalTracks         sql.NullInt64   `json:"total_tracks"`
	TotalDiscs          sql.NullInt64   `json:"total_discs"`
	Genre               sql.NullString  `json:"genre"`
	Year                sql.NullInt64   `json:"year"`
	ReleaseDate         sql.NullTime    `json:"release_date"`
	Composer            sql.NullString  `json:"composer"`
	Lyricist            sql.NullString  `json:"lyricist"`
	RecordLabel         sql.NullString  `json:"record_label"`
	Isrc                sql.NullString  `json:"isrc"`
	ReleaseType         sql.NullString  `json:"release_type"`
	Compilation         sql.NullInt64   `json:"compilation"`
	MusicbrainzTrackID  sql.NullString  `json:"musicbrainz_track_id"`
	MusicbrainzAlbumID  sql.NullString  `json:"musicbrainz_album_id"`
	MusicbrainzArtistID sql.NullString  `json:"musicbrainz_artist_id"`
	OriginalTitle       sql.NullString  `json:"original_title"`
	SortTitle           sql.NullString  `json:"sort_title"`
	AlbumID             sql.NullInt64   `json:"album_id"`
	ArtistID            sql.NullInt64   `json:"artist_id"`
	MediaID_2           int64           `json:"media_id_2"`
	LibraryID           int64           `json:"library_id"`
	Title               string          `json:"title"`
	FilePath            string          `json:"file_path"`
	FileSize            sql.NullInt64   `json:"file_size"`
	FileHash            sql.NullString  `json:"file_hash"`
	ContainerFormat     sql.NullString  `json:"container_format"`
	Duration            sql.NullFloat64 `json:"duration"`
	Width               sql.NullInt64   `json:"width"`
	Height              sql.NullInt64   `json:"height"`
	AspectRatio         sql.NullString  `json:"aspect_ratio"`
	Codec               sql.NullString  `json:"codec"`
	AudioCodec          sql.NullString  `json:"audio_codec"`
	CodecProfile        sql.NullString  `json:"codec_profile"`
	BitRate             sql.NullInt64   `json:"bit_rate"`
	FrameRate           sql.NullFloat64 `json:"frame_rate"`
	ScanType            sql.NullString  `json:"scan_type"`
	HdrFormat           sql.NullString  `json:"hdr_format"`
	ColorSpace          sql.NullString  `json:"color_space"`
	ColorPrimaries      sql.NullString  `json:"color_primaries"`
	ThumbnailPath       sql.NullString  `json:"thumbnail_path"`
	Type                string          `json:"type"`
	SourceType          sql.NullString  `json:"source_type"`
	ResolutionLabel     sql.NullString  `json:"resolution_label"`
	QualityScore        sql.NullInt64   `json:"quality_score"`
	Is3d                sql.NullInt64   `json:"is_3d"`
	StereoMode          sql.NullString  `json:"stereo_mode"`
	HasDash             sql.NullInt64   `json:"has_dash"`
	DashManifestPath    sql.NullString  `json:"dash_manifest_path"`
	TranscodingStatus   sql.NullString  `json:"transcoding_status"`
	IsExtra             int64           `json:"is_extra"`
	DateAdded           sql.NullTime    `json:"date_added"`
	DateModified        sql.NullTime    `json:"date_modified"`
	CreatedAt           sql.NullTime    `json:"created_at"`
	UpdatedAt           sql.NullTime    `json:"updated_at"`
}

func (q *Queries) SearchMusicTracks(ctx context.Context, arg SearchMusicTracksParams) ([]SearchMusicTracksRow, error) {
	rows, err := q.db.QueryContext(ctx, searchMusicTracks,
		arg.LibraryID,
		arg.Title,
		arg.Artist,
		arg.Album,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchMusicTracksRow{}
	for rows.Next() {
		var i SearchMusicTracksRow
		if err := rows.Scan(
			&i.MediaID,
			&i.Artist,
			&i.Album,
			&i.AlbumArtist,
			&i.TrackNumber,
			&i.DiscNumber,
			&i.TotalTracks,
			&i.TotalDiscs,
			&i.Genre,
			&i.Year,
			&i.ReleaseDate,
			&i.Composer,
			&i.Lyricist,
			&i.RecordLabel,
			&i.Isrc,
			&i.ReleaseType,
			&i.Compilation,
			&i.MusicbrainzTrackID,
			&i.MusicbrainzAlbumID,
			&i.MusicbrainzArtistID,
			&i.OriginalTitle,
			&i.SortTitle,
			&i.AlbumID,
			&i.ArtistID,
			&i.MediaID_2,
			&i.LibraryID,
			&i.Title,
			&i.FilePath,
			&i.FileSize,
			&i.FileHash,
			&i.ContainerFormat,
			&i.Duration,
			&i.Width,
			&i.Height,
			&i.AspectRatio,
			&i.Codec,
			&i.AudioCodec,
			&i.CodecProfile,
			&i.BitRate,
			&i.FrameRate,
			&i.ScanType,
			&i.HdrFormat,
			&i.ColorSpace,
			&i.ColorPrimaries,
			&i.ThumbnailPath,
			&i.Type,
			&i.SourceType,
			&i.ResolutionLabel,
			&i.QualityScore,
			&i.Is3d,
			&i.StereoMode,
			&i.HasDash,
			&i.DashManifestPath,
			&i.TranscodingStatus,
			&i.IsExtra,
			&i.DateAdded,
			&i.DateModified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMusicTrack = `-- name: UpdateMusicTrack :exec
UPDATE music_tracks
SET artist = $1,
    album = $2,
    album_artist = $3,
    track_number = $4,
    disc_number = $5,
    total_tracks = $6,
    total_discs = $7,
    genre = $8,
    year = $9,
    release_date = $10,
    composer = $11,
    lyricist = $12,
    record_label = $13,
    isrc = $14,
    release_type = $15,
    compilation = $16,
    musicbrainz_track_id = $17,
    musicbrainz_album_id = $18,
    musicbrainz_artist_id = $19,
    original_title = $20,
    sort_title = $21,
    album_id = $22,
    artist_id = $23
WHERE media_id = $24
`

type UpdateMusicTrackParams struct {
	Artist              sql.NullString `json:"artist"`
	Album               sql.NullString `json:"album"`
	AlbumArtist         sql.NullString `json:"album_artist"`
	TrackNumber         sql.NullInt64  `json:"track_number"`
	DiscNumber          sql.NullInt64  `json:"disc_number"`
	TotalTracks         sql.NullInt64  `json:"total_tracks"`
	TotalDiscs          sql.NullInt64  `json:"total_discs"`
	Genre               sql.NullString `json:"genre"`
	Year                sql.NullInt64  `json:"year"`
	ReleaseDate         sql.NullTime   `json:"release_date"`
	Composer            sql.NullString `json:"composer"`
	Lyricist            sql.NullString `json:"lyricist"`
	RecordLabel         sql.NullString `json:"record_label"`
	Isrc                sql.NullString `json:"isrc"`
	ReleaseType         sql.NullString `json:"release_type"`
	Compilation         sql.NullInt64  `json:"compilation"`
	MusicbrainzTrackID  sql.NullString `json:"musicbrainz_track_id"`
	MusicbrainzAlbumID  sql.NullString `json:"musicbrainz_album_id"`
	MusicbrainzArtistID sql.NullString `json:"musicbrainz_artist_id"`
	OriginalTitle       sql.NullString `json:"original_title"`
	SortTitle           sql.NullString `json:"sort_title"`
	AlbumID             sql.NullInt64  `json:"album_id"`
	ArtistID            sql.NullInt64  `json:"artist_id"`
	MediaID             int64          `json:"media_id"`
}

func (q *Queries) UpdateMusicTrack(ctx context.Context, arg UpdateMusicTrackParams) error {
	_, err := q.db.ExecContext(ctx, updateMusicTrack,
		arg.Artist,
		arg.Album,
		arg.AlbumArtist,
		arg.TrackNumber,
		arg.DiscNumber,
		arg.TotalTracks,
		arg.TotalDiscs,
		arg.Genre,
		arg.Year,
		arg.ReleaseDate,
		arg.Composer,
		arg.Lyricist,
		arg.RecordLabel,
		arg.Isrc,
		arg.ReleaseType,
		arg.Compilation,
		arg.MusicbrainzTrackID,
		arg.MusicbrainzAlbumID,
		arg.MusicbrainzArtistID,
		arg.OriginalTitle,
		arg.SortTitle,
		arg.AlbumID,
		arg.ArtistID,
		arg.MediaID,
	)
	return err
}
