// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: playback_analytics.sql

package sqlc_postgres

import (
	"context"
	"database/sql"
)

const countPlaybackSessionsByMediaID = `-- name: CountPlaybackSessionsByMediaID :one
SELECT COUNT(*) as count
FROM playback_sessions
WHERE media_id = $1
`

func (q *Queries) CountPlaybackSessionsByMediaID(ctx context.Context, mediaID int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlaybackSessionsByMediaID, mediaID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createQualitySwitchEvent = `-- name: CreateQualitySwitchEvent :one
INSERT INTO quality_switch_events (
    session_id,
    media_id,
    from_quality,
    to_quality,
    switch_reason,
    position_seconds,
    network_speed_mbps,
    buffer_seconds,
    caused_stall,
    device_type,
    connection_type,
    timestamp
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, session_id, media_id, from_quality, to_quality, switch_reason, position_seconds, network_speed_mbps, buffer_seconds, caused_stall, device_type, connection_type, timestamp, created_at
`

type CreateQualitySwitchEventParams struct {
	SessionID        string          `json:"session_id"`
	MediaID          int32           `json:"media_id"`
	FromQuality      sql.NullString  `json:"from_quality"`
	ToQuality        string          `json:"to_quality"`
	SwitchReason     string          `json:"switch_reason"`
	PositionSeconds  float32         `json:"position_seconds"`
	NetworkSpeedMbps sql.NullFloat64 `json:"network_speed_mbps"`
	BufferSeconds    sql.NullFloat64 `json:"buffer_seconds"`
	CausedStall      sql.NullBool    `json:"caused_stall"`
	DeviceType       sql.NullString  `json:"device_type"`
	ConnectionType   sql.NullString  `json:"connection_type"`
	Timestamp        int64           `json:"timestamp"`
}

func (q *Queries) CreateQualitySwitchEvent(ctx context.Context, arg CreateQualitySwitchEventParams) (QualitySwitchEvent, error) {
	row := q.db.QueryRowContext(ctx, createQualitySwitchEvent,
		arg.SessionID,
		arg.MediaID,
		arg.FromQuality,
		arg.ToQuality,
		arg.SwitchReason,
		arg.PositionSeconds,
		arg.NetworkSpeedMbps,
		arg.BufferSeconds,
		arg.CausedStall,
		arg.DeviceType,
		arg.ConnectionType,
		arg.Timestamp,
	)
	var i QualitySwitchEvent
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.MediaID,
		&i.FromQuality,
		&i.ToQuality,
		&i.SwitchReason,
		&i.PositionSeconds,
		&i.NetworkSpeedMbps,
		&i.BufferSeconds,
		&i.CausedStall,
		&i.DeviceType,
		&i.ConnectionType,
		&i.Timestamp,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOldPlaybackSessions = `-- name: DeleteOldPlaybackSessions :exec
DELETE FROM playback_sessions
WHERE start_time < $1
`

func (q *Queries) DeleteOldPlaybackSessions(ctx context.Context, startTime int64) error {
	_, err := q.db.ExecContext(ctx, deleteOldPlaybackSessions, startTime)
	return err
}

const deleteOldQualitySwitchEvents = `-- name: DeleteOldQualitySwitchEvents :exec
DELETE FROM quality_switch_events
WHERE timestamp < $1
`

func (q *Queries) DeleteOldQualitySwitchEvents(ctx context.Context, timestamp int64) error {
	_, err := q.db.ExecContext(ctx, deleteOldQualitySwitchEvents, timestamp)
	return err
}

const getOverallPlaybackSummary = `-- name: GetOverallPlaybackSummary :one
SELECT
    COUNT(*) as total_sessions,
    COUNT(DISTINCT media_id) as unique_media,
    COALESCE(AVG(total_play_time_ms), 0) as avg_play_time_ms,
    COALESCE(AVG(total_buffer_time_ms), 0) as avg_buffer_time_ms,
    COALESCE(SUM(stall_count), 0) as total_stalls,
    COALESCE(AVG(stall_count), 0) as avg_stalls_per_session,
    COALESCE(AVG(startup_time_ms), 0) as avg_startup_time_ms,
    MIN(startup_time_ms) as min_startup_time_ms,
    MAX(startup_time_ms) as max_startup_time_ms
FROM playback_sessions
`

type GetOverallPlaybackSummaryRow struct {
	TotalSessions       int64       `json:"total_sessions"`
	UniqueMedia         int64       `json:"unique_media"`
	AvgPlayTimeMs       interface{} `json:"avg_play_time_ms"`
	AvgBufferTimeMs     interface{} `json:"avg_buffer_time_ms"`
	TotalStalls         interface{} `json:"total_stalls"`
	AvgStallsPerSession interface{} `json:"avg_stalls_per_session"`
	AvgStartupTimeMs    interface{} `json:"avg_startup_time_ms"`
	MinStartupTimeMs    interface{} `json:"min_startup_time_ms"`
	MaxStartupTimeMs    interface{} `json:"max_startup_time_ms"`
}

func (q *Queries) GetOverallPlaybackSummary(ctx context.Context) (GetOverallPlaybackSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getOverallPlaybackSummary)
	var i GetOverallPlaybackSummaryRow
	err := row.Scan(
		&i.TotalSessions,
		&i.UniqueMedia,
		&i.AvgPlayTimeMs,
		&i.AvgBufferTimeMs,
		&i.TotalStalls,
		&i.AvgStallsPerSession,
		&i.AvgStartupTimeMs,
		&i.MinStartupTimeMs,
		&i.MaxStartupTimeMs,
	)
	return i, err
}

const getPlaybackSessionByID = `-- name: GetPlaybackSessionByID :one
SELECT id, session_id, media_id, start_time, end_time, total_play_time_ms, total_buffer_time_ms, stall_count, quality_switch_count, average_quality, device_type, connection_type, created_at, startup_time_ms FROM playback_sessions
WHERE session_id = $1
`

func (q *Queries) GetPlaybackSessionByID(ctx context.Context, sessionID string) (PlaybackSession, error) {
	row := q.db.QueryRowContext(ctx, getPlaybackSessionByID, sessionID)
	var i PlaybackSession
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.MediaID,
		&i.StartTime,
		&i.EndTime,
		&i.TotalPlayTimeMs,
		&i.TotalBufferTimeMs,
		&i.StallCount,
		&i.QualitySwitchCount,
		&i.AverageQuality,
		&i.DeviceType,
		&i.ConnectionType,
		&i.CreatedAt,
		&i.StartupTimeMs,
	)
	return i, err
}

const getPlaybackSummaryByMediaID = `-- name: GetPlaybackSummaryByMediaID :one
SELECT
    COUNT(*) as total_sessions,
    COALESCE(AVG(total_play_time_ms), 0) as avg_play_time_ms,
    COALESCE(AVG(total_buffer_time_ms), 0) as avg_buffer_time_ms,
    COALESCE(SUM(stall_count), 0) as total_stalls,
    COALESCE(AVG(stall_count), 0) as avg_stalls_per_session,
    COALESCE(AVG(startup_time_ms), 0) as avg_startup_time_ms,
    MIN(startup_time_ms) as min_startup_time_ms,
    MAX(startup_time_ms) as max_startup_time_ms
FROM playback_sessions
WHERE media_id = $1
`

type GetPlaybackSummaryByMediaIDRow struct {
	TotalSessions       int64       `json:"total_sessions"`
	AvgPlayTimeMs       interface{} `json:"avg_play_time_ms"`
	AvgBufferTimeMs     interface{} `json:"avg_buffer_time_ms"`
	TotalStalls         interface{} `json:"total_stalls"`
	AvgStallsPerSession interface{} `json:"avg_stalls_per_session"`
	AvgStartupTimeMs    interface{} `json:"avg_startup_time_ms"`
	MinStartupTimeMs    interface{} `json:"min_startup_time_ms"`
	MaxStartupTimeMs    interface{} `json:"max_startup_time_ms"`
}

func (q *Queries) GetPlaybackSummaryByMediaID(ctx context.Context, mediaID int32) (GetPlaybackSummaryByMediaIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPlaybackSummaryByMediaID, mediaID)
	var i GetPlaybackSummaryByMediaIDRow
	err := row.Scan(
		&i.TotalSessions,
		&i.AvgPlayTimeMs,
		&i.AvgBufferTimeMs,
		&i.TotalStalls,
		&i.AvgStallsPerSession,
		&i.AvgStartupTimeMs,
		&i.MinStartupTimeMs,
		&i.MaxStartupTimeMs,
	)
	return i, err
}

const getQualitySwitchStats = `-- name: GetQualitySwitchStats :one
SELECT
    COUNT(*) as total_switches,
    SUM(CASE WHEN caused_stall = true THEN 1 ELSE 0 END) as switches_with_stall,
    COUNT(DISTINCT session_id) as unique_sessions
FROM quality_switch_events
WHERE media_id = $1
`

type GetQualitySwitchStatsRow struct {
	TotalSwitches     int64 `json:"total_switches"`
	SwitchesWithStall int64 `json:"switches_with_stall"`
	UniqueSessions    int64 `json:"unique_sessions"`
}

func (q *Queries) GetQualitySwitchStats(ctx context.Context, mediaID int32) (GetQualitySwitchStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getQualitySwitchStats, mediaID)
	var i GetQualitySwitchStatsRow
	err := row.Scan(&i.TotalSwitches, &i.SwitchesWithStall, &i.UniqueSessions)
	return i, err
}

const listPlaybackSessionsByMediaID = `-- name: ListPlaybackSessionsByMediaID :many
SELECT id, session_id, media_id, start_time, end_time, total_play_time_ms, total_buffer_time_ms, stall_count, quality_switch_count, average_quality, device_type, connection_type, created_at, startup_time_ms FROM playback_sessions
WHERE media_id = $1
ORDER BY start_time DESC
LIMIT $2 OFFSET $3
`

type ListPlaybackSessionsByMediaIDParams struct {
	MediaID int32 `json:"media_id"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

func (q *Queries) ListPlaybackSessionsByMediaID(ctx context.Context, arg ListPlaybackSessionsByMediaIDParams) ([]PlaybackSession, error) {
	rows, err := q.db.QueryContext(ctx, listPlaybackSessionsByMediaID, arg.MediaID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlaybackSession{}
	for rows.Next() {
		var i PlaybackSession
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.MediaID,
			&i.StartTime,
			&i.EndTime,
			&i.TotalPlayTimeMs,
			&i.TotalBufferTimeMs,
			&i.StallCount,
			&i.QualitySwitchCount,
			&i.AverageQuality,
			&i.DeviceType,
			&i.ConnectionType,
			&i.CreatedAt,
			&i.StartupTimeMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQualitySwitchEventsBySessionID = `-- name: ListQualitySwitchEventsBySessionID :many
SELECT id, session_id, media_id, from_quality, to_quality, switch_reason, position_seconds, network_speed_mbps, buffer_seconds, caused_stall, device_type, connection_type, timestamp, created_at FROM quality_switch_events
WHERE session_id = $1
ORDER BY timestamp ASC
`

func (q *Queries) ListQualitySwitchEventsBySessionID(ctx context.Context, sessionID string) ([]QualitySwitchEvent, error) {
	rows, err := q.db.QueryContext(ctx, listQualitySwitchEventsBySessionID, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QualitySwitchEvent{}
	for rows.Next() {
		var i QualitySwitchEvent
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.MediaID,
			&i.FromQuality,
			&i.ToQuality,
			&i.SwitchReason,
			&i.PositionSeconds,
			&i.NetworkSpeedMbps,
			&i.BufferSeconds,
			&i.CausedStall,
			&i.DeviceType,
			&i.ConnectionType,
			&i.Timestamp,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPlaybackSession = `-- name: UpsertPlaybackSession :one
INSERT INTO playback_sessions (
    session_id,
    media_id,
    start_time,
    end_time,
    total_play_time_ms,
    total_buffer_time_ms,
    stall_count,
    quality_switch_count,
    average_quality,
    device_type,
    connection_type,
    startup_time_ms
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT(session_id)
DO UPDATE SET
    end_time = COALESCE(EXCLUDED.end_time, playback_sessions.end_time),
    total_play_time_ms = EXCLUDED.total_play_time_ms,
    total_buffer_time_ms = EXCLUDED.total_buffer_time_ms,
    stall_count = EXCLUDED.stall_count,
    quality_switch_count = EXCLUDED.quality_switch_count,
    average_quality = COALESCE(EXCLUDED.average_quality, playback_sessions.average_quality),
    startup_time_ms = COALESCE(EXCLUDED.startup_time_ms, playback_sessions.startup_time_ms)
RETURNING id, session_id, media_id, start_time, end_time, total_play_time_ms, total_buffer_time_ms, stall_count, quality_switch_count, average_quality, device_type, connection_type, created_at, startup_time_ms
`

type UpsertPlaybackSessionParams struct {
	SessionID          string         `json:"session_id"`
	MediaID            int32          `json:"media_id"`
	StartTime          int64          `json:"start_time"`
	EndTime            sql.NullInt64  `json:"end_time"`
	TotalPlayTimeMs    sql.NullInt32  `json:"total_play_time_ms"`
	TotalBufferTimeMs  sql.NullInt32  `json:"total_buffer_time_ms"`
	StallCount         sql.NullInt32  `json:"stall_count"`
	QualitySwitchCount sql.NullInt32  `json:"quality_switch_count"`
	AverageQuality     sql.NullString `json:"average_quality"`
	DeviceType         sql.NullString `json:"device_type"`
	ConnectionType     sql.NullString `json:"connection_type"`
	StartupTimeMs      sql.NullInt32  `json:"startup_time_ms"`
}

func (q *Queries) UpsertPlaybackSession(ctx context.Context, arg UpsertPlaybackSessionParams) (PlaybackSession, error) {
	row := q.db.QueryRowContext(ctx, upsertPlaybackSession,
		arg.SessionID,
		arg.MediaID,
		arg.StartTime,
		arg.EndTime,
		arg.TotalPlayTimeMs,
		arg.TotalBufferTimeMs,
		arg.StallCount,
		arg.QualitySwitchCount,
		arg.AverageQuality,
		arg.DeviceType,
		arg.ConnectionType,
		arg.StartupTimeMs,
	)
	var i PlaybackSession
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.MediaID,
		&i.StartTime,
		&i.EndTime,
		&i.TotalPlayTimeMs,
		&i.TotalBufferTimeMs,
		&i.StallCount,
		&i.QualitySwitchCount,
		&i.AverageQuality,
		&i.DeviceType,
		&i.ConnectionType,
		&i.CreatedAt,
		&i.StartupTimeMs,
	)
	return i, err
}
