// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plugin_user_metadata.sql

package sqlc_postgres

import (
	"context"
	"time"
)

const countPluginUserMetadata = `-- name: CountPluginUserMetadata :one
SELECT COUNT(*) as count FROM plugin_user_metadata
WHERE plugin_id = $1 AND user_id = $2
`

type CountPluginUserMetadataParams struct {
	PluginID string `json:"plugin_id"`
	UserID   int32  `json:"user_id"`
}

func (q *Queries) CountPluginUserMetadata(ctx context.Context, arg CountPluginUserMetadataParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPluginUserMetadata, arg.PluginID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePluginUserMetadata = `-- name: DeletePluginUserMetadata :exec
DELETE FROM plugin_user_metadata WHERE plugin_id = $1 AND user_id = $2 AND key = $3
`

type DeletePluginUserMetadataParams struct {
	PluginID string `json:"plugin_id"`
	UserID   int32  `json:"user_id"`
	Key      string `json:"key"`
}

func (q *Queries) DeletePluginUserMetadata(ctx context.Context, arg DeletePluginUserMetadataParams) error {
	_, err := q.db.ExecContext(ctx, deletePluginUserMetadata, arg.PluginID, arg.UserID, arg.Key)
	return err
}

const deletePluginUserMetadataByPlugin = `-- name: DeletePluginUserMetadataByPlugin :exec
DELETE FROM plugin_user_metadata WHERE plugin_id = $1
`

func (q *Queries) DeletePluginUserMetadataByPlugin(ctx context.Context, pluginID string) error {
	_, err := q.db.ExecContext(ctx, deletePluginUserMetadataByPlugin, pluginID)
	return err
}

const deletePluginUserMetadataByUser = `-- name: DeletePluginUserMetadataByUser :exec
DELETE FROM plugin_user_metadata WHERE user_id = $1
`

func (q *Queries) DeletePluginUserMetadataByUser(ctx context.Context, userID int32) error {
	_, err := q.db.ExecContext(ctx, deletePluginUserMetadataByUser, userID)
	return err
}

const getPluginUserMetadata = `-- name: GetPluginUserMetadata :one
SELECT value, created_at, updated_at
FROM plugin_user_metadata
WHERE plugin_id = $1 AND user_id = $2 AND key = $3
`

type GetPluginUserMetadataParams struct {
	PluginID string `json:"plugin_id"`
	UserID   int32  `json:"user_id"`
	Key      string `json:"key"`
}

type GetPluginUserMetadataRow struct {
	Value     []byte    `json:"value"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) GetPluginUserMetadata(ctx context.Context, arg GetPluginUserMetadataParams) (GetPluginUserMetadataRow, error) {
	row := q.db.QueryRowContext(ctx, getPluginUserMetadata, arg.PluginID, arg.UserID, arg.Key)
	var i GetPluginUserMetadataRow
	err := row.Scan(&i.Value, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const listPluginUserMetadataKeys = `-- name: ListPluginUserMetadataKeys :many
SELECT key FROM plugin_user_metadata
WHERE plugin_id = $1 AND user_id = $2
ORDER BY key
`

type ListPluginUserMetadataKeysParams struct {
	PluginID string `json:"plugin_id"`
	UserID   int32  `json:"user_id"`
}

func (q *Queries) ListPluginUserMetadataKeys(ctx context.Context, arg ListPluginUserMetadataKeysParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPluginUserMetadataKeys, arg.PluginID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPluginUserMetadata = `-- name: SetPluginUserMetadata :exec
INSERT INTO plugin_user_metadata (plugin_id, user_id, key, value, created_at, updated_at)
VALUES ($1, $2, $3, $4, NOW(), NOW())
ON CONFLICT(plugin_id, user_id, key) DO UPDATE SET
    value = excluded.value,
    updated_at = NOW()
`

type SetPluginUserMetadataParams struct {
	PluginID string `json:"plugin_id"`
	UserID   int32  `json:"user_id"`
	Key      string `json:"key"`
	Value    []byte `json:"value"`
}

func (q *Queries) SetPluginUserMetadata(ctx context.Context, arg SetPluginUserMetadataParams) error {
	_, err := q.db.ExecContext(ctx, setPluginUserMetadata,
		arg.PluginID,
		arg.UserID,
		arg.Key,
		arg.Value,
	)
	return err
}
