// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc_postgres

import (
	"context"
	"database/sql"
)

type Querier interface {
	ClearScanStateError(ctx context.Context, arg ClearScanStateErrorParams) error
	ClearScanStateWarning(ctx context.Context, arg ClearScanStateWarningParams) error
	CompleteScanJob(ctx context.Context, arg CompleteScanJobParams) error
	// ============================================================================
	// Pagination Support Queries
	// ============================================================================
	CountAlbumsByLibrary(ctx context.Context, libraryID int32) (int64, error)
	CountAlbumsInLibrary(ctx context.Context, libraryID int32) (int64, error)
	CountArtistsInLibrary(ctx context.Context, libraryID int32) (int64, error)
	CountFailedScanCheckpoints(ctx context.Context, scanJobID int32) (int64, error)
	CountImagesByEntity(ctx context.Context, arg CountImagesByEntityParams) (int64, error)
	CountImagesByMediaID(ctx context.Context, mediaID sql.NullInt32) (int64, error)
	CountLibraries(ctx context.Context) (int64, error)
	CountLibrariesByType(ctx context.Context, type_ string) (int64, error)
	CountLibraryErrors(ctx context.Context, libraryID int32) (int64, error)
	CountLibraryIssues(ctx context.Context, libraryID int32) (CountLibraryIssuesRow, error)
	CountLibraryScanState(ctx context.Context, libraryID int32) (int64, error)
	CountLibraryWarnings(ctx context.Context, libraryID int32) (int64, error)
	CountMediaByType(ctx context.Context, arg CountMediaByTypeParams) (int64, error)
	CountMediaInLibrary(ctx context.Context, libraryID int32) (int64, error)
	CountMoviesByLibrary(ctx context.Context, libraryID int32) (int64, error)
	CountMusicTracksByLibrary(ctx context.Context, libraryID int32) (int64, error)
	CountScanJobsByLibrary(ctx context.Context, libraryID int32) (int64, error)
	CountSearchArtistsByName(ctx context.Context, arg CountSearchArtistsByNameParams) (int64, error)
	CountSearchMoviesByTitle(ctx context.Context, arg CountSearchMoviesByTitleParams) (int64, error)
	CountSearchTVShowsByTitle(ctx context.Context, arg CountSearchTVShowsByTitleParams) (int64, error)
	// ============================================================================
	// Pagination Support Queries
	// ============================================================================
	CountTVShowsByLibrary(ctx context.Context, libraryID int32) (int64, error)
	CountTranscodeJobsByStatus(ctx context.Context, status string) (int64, error)
	CreateAlbum(ctx context.Context, arg CreateAlbumParams) (MusicAlbum, error)
	CreateArtist(ctx context.Context, arg CreateArtistParams) (MusicArtist, error)
	CreateImage(ctx context.Context, arg CreateImageParams) (MediaImage, error)
	// Library queries for PostgreSQL
	CreateLibrary(ctx context.Context, arg CreateLibraryParams) (Library, error)
	// Media queries for PostgreSQL
	CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error)
	CreateMovie(ctx context.Context, arg CreateMovieParams) error
	CreateMusicTrack(ctx context.Context, arg CreateMusicTrackParams) error
	CreateQualitySwitchEvent(ctx context.Context, arg CreateQualitySwitchEventParams) (QualitySwitchEvent, error)
	CreateScanCheckpoint(ctx context.Context, arg CreateScanCheckpointParams) (ScanCheckpoint, error)
	CreateScanCheckpointBatch(ctx context.Context, arg CreateScanCheckpointBatchParams) error
	CreateScanJob(ctx context.Context, arg CreateScanJobParams) (ScanJob, error)
	// ============================================================================
	// TV Episodes
	// ============================================================================
	CreateTVEpisode(ctx context.Context, arg CreateTVEpisodeParams) error
	// ============================================================================
	// TV Seasons
	// ============================================================================
	CreateTVSeason(ctx context.Context, arg CreateTVSeasonParams) (TvSeason, error)
	// ============================================================================
	// TV Shows
	// ============================================================================
	CreateTVShow(ctx context.Context, arg CreateTVShowParams) (TvShow, error)
	CreateTranscodeJob(ctx context.Context, arg CreateTranscodeJobParams) (TranscodeJob, error)
	CreateWatchProgress(ctx context.Context, arg CreateWatchProgressParams) (WatchProgress, error)
	DeleteAlbum(ctx context.Context, id int32) error
	DeleteArtist(ctx context.Context, id int32) error
	DeleteImage(ctx context.Context, id int32) error
	DeleteImagesByEntity(ctx context.Context, arg DeleteImagesByEntityParams) error
	DeleteImagesByHash(ctx context.Context, fileHash sql.NullString) error
	DeleteImagesByMediaID(ctx context.Context, mediaID sql.NullInt32) error
	DeleteLibrary(ctx context.Context, id int32) error
	DeleteMedia(ctx context.Context, id int32) error
	DeleteMovie(ctx context.Context, mediaID int32) error
	DeleteMusicTrack(ctx context.Context, mediaID int32) error
	DeleteOldPlaybackSessions(ctx context.Context, startTime int64) error
	DeleteOldQualitySwitchEvents(ctx context.Context, timestamp int64) error
	// sqlc.arg(retention_days): the number of days to retain completed/failed jobs
	DeleteOldScanJobs(ctx context.Context, arg DeleteOldScanJobsParams) error
	DeleteScanCheckpointsByJobID(ctx context.Context, scanJobID int32) error
	DeleteScanJob(ctx context.Context, id int32) error
	DeleteScanStateByLibrary(ctx context.Context, libraryID int32) error
	DeleteScanStateByPath(ctx context.Context, arg DeleteScanStateByPathParams) error
	DeleteTVEpisode(ctx context.Context, mediaID int32) error
	DeleteTVSeason(ctx context.Context, id int32) error
	DeleteTVShow(ctx context.Context, id int32) error
	DeleteTranscodeJob(ctx context.Context, id int32) error
	DeleteTranscodeJobsByMediaID(ctx context.Context, mediaID int32) error
	DeleteWatchProgress(ctx context.Context, id int32) error
	DeleteWatchProgressByMediaID(ctx context.Context, mediaID int32) error
	FindAlbumByTitle(ctx context.Context, arg FindAlbumByTitleParams) (MusicAlbum, error)
	FindArtistByName(ctx context.Context, arg FindArtistByNameParams) (MusicArtist, error)
	GetAlbumByID(ctx context.Context, id int32) (MusicAlbum, error)
	GetAlbumByMusicBrainzID(ctx context.Context, musicbrainzAlbumID sql.NullString) (MusicAlbum, error)
	GetAllFileHashes(ctx context.Context) ([]sql.NullString, error)
	GetArtistByID(ctx context.Context, id int32) (MusicArtist, error)
	GetArtistByMusicBrainzID(ctx context.Context, musicbrainzArtistID sql.NullString) (MusicArtist, error)
	// ============================================================================
	// Aggregation Queries for API (optimized)
	// ============================================================================
	GetArtistsWithCountsByLibrary(ctx context.Context, libraryID int32) ([]GetArtistsWithCountsByLibraryRow, error)
	GetArtistsWithCountsByLibraryPaginated(ctx context.Context, arg GetArtistsWithCountsByLibraryPaginatedParams) ([]GetArtistsWithCountsByLibraryPaginatedRow, error)
	GetArtistsWithCountsByLibraryPaginatedDesc(ctx context.Context, arg GetArtistsWithCountsByLibraryPaginatedDescParams) ([]GetArtistsWithCountsByLibraryPaginatedDescRow, error)
	GetBatchWatchProgressByMediaIDs(ctx context.Context, arg GetBatchWatchProgressByMediaIDsParams) ([]WatchProgress, error)
	GetFilePathCache(ctx context.Context, libraryID int32) ([]GetFilePathCacheRow, error)
	GetImageByFilePath(ctx context.Context, filePath sql.NullString) (MediaImage, error)
	GetImageByID(ctx context.Context, id int32) (MediaImage, error)
	GetImageByTypeAndEntity(ctx context.Context, arg GetImageByTypeAndEntityParams) (MediaImage, error)
	GetImageByTypeAndMediaID(ctx context.Context, arg GetImageByTypeAndMediaIDParams) (MediaImage, error)
	GetImagesByHash(ctx context.Context, fileHash sql.NullString) ([]MediaImage, error)
	GetLatestScanJobByLibrary(ctx context.Context, libraryID int32) (ScanJob, error)
	GetLibraryByID(ctx context.Context, id int32) (Library, error)
	GetLibraryByPath(ctx context.Context, path string) (Library, error)
	GetLibraryErrors(ctx context.Context, libraryID int32) ([]ScanState, error)
	GetLibraryIssues(ctx context.Context, libraryID int32) ([]ScanState, error)
	GetLibraryScanState(ctx context.Context, libraryID int32) ([]ScanState, error)
	GetLibraryWarnings(ctx context.Context, libraryID int32) ([]ScanState, error)
	GetMediaByFilePath(ctx context.Context, arg GetMediaByFilePathParams) (Medium, error)
	GetMediaByID(ctx context.Context, id int32) (Medium, error)
	GetMovieByMediaID(ctx context.Context, mediaID int32) (GetMovieByMediaIDRow, error)
	GetMusicTrackByMediaID(ctx context.Context, mediaID int32) (GetMusicTrackByMediaIDRow, error)
	GetPendingScanCheckpoints(ctx context.Context, arg GetPendingScanCheckpointsParams) ([]ScanCheckpoint, error)
	GetPlaybackSessionByID(ctx context.Context, sessionID string) (PlaybackSession, error)
	GetQualitySwitchStats(ctx context.Context, mediaID int32) (GetQualitySwitchStatsRow, error)
	GetScanCheckpointByID(ctx context.Context, id int32) (ScanCheckpoint, error)
	GetScanCheckpointByPath(ctx context.Context, arg GetScanCheckpointByPathParams) (ScanCheckpoint, error)
	GetScanCheckpointErrorsByCategory(ctx context.Context, scanJobID int32) ([]GetScanCheckpointErrorsByCategoryRow, error)
	GetScanCheckpointProgress(ctx context.Context, scanJobID int32) (GetScanCheckpointProgressRow, error)
	GetScanCheckpointStats(ctx context.Context, scanJobID int32) (GetScanCheckpointStatsRow, error)
	GetScanJob(ctx context.Context, id int32) (ScanJob, error)
	GetScanJobStats(ctx context.Context, libraryID int32) (GetScanJobStatsRow, error)
	GetScanStateByPath(ctx context.Context, arg GetScanStateByPathParams) (ScanState, error)
	GetScanStateModifiedSince(ctx context.Context, arg GetScanStateModifiedSinceParams) ([]ScanState, error)
	GetTVEpisodeByMediaID(ctx context.Context, mediaID int32) (GetTVEpisodeByMediaIDRow, error)
	GetTVEpisodeByShowSeasonEpisode(ctx context.Context, arg GetTVEpisodeByShowSeasonEpisodeParams) (GetTVEpisodeByShowSeasonEpisodeRow, error)
	GetTVSeasonByID(ctx context.Context, id int32) (TvSeason, error)
	GetTVSeasonByShowAndNumber(ctx context.Context, arg GetTVSeasonByShowAndNumberParams) (TvSeason, error)
	GetTVShowByID(ctx context.Context, id int32) (TvShow, error)
	GetTVShowByTitle(ctx context.Context, arg GetTVShowByTitleParams) (TvShow, error)
	// ============================================================================
	// Aggregation Queries for API
	// ============================================================================
	GetTVShowsWithCountsByLibrary(ctx context.Context, libraryID int32) ([]GetTVShowsWithCountsByLibraryRow, error)
	GetTVShowsWithCountsByLibraryPaginated(ctx context.Context, arg GetTVShowsWithCountsByLibraryPaginatedParams) ([]GetTVShowsWithCountsByLibraryPaginatedRow, error)
	GetTVShowsWithCountsByLibraryPaginatedDesc(ctx context.Context, arg GetTVShowsWithCountsByLibraryPaginatedDescParams) ([]GetTVShowsWithCountsByLibraryPaginatedDescRow, error)
	GetTotalTranscodeSize(ctx context.Context) (interface{}, error)
	GetTranscodeJobByID(ctx context.Context, id int32) (TranscodeJob, error)
	GetTranscodeJobByMediaIDAndQuality(ctx context.Context, arg GetTranscodeJobByMediaIDAndQualityParams) (TranscodeJob, error)
	GetWatchProgressByID(ctx context.Context, id int32) (WatchProgress, error)
	GetWatchProgressByMediaID(ctx context.Context, mediaID int32) (WatchProgress, error)
	GetWatchProgressByMediaIDAndUserID(ctx context.Context, arg GetWatchProgressByMediaIDAndUserIDParams) (WatchProgress, error)
	IncrementSeasonEpisodeCount(ctx context.Context, id int32) error
	LibraryExistsByID(ctx context.Context, id int32) (bool, error)
	LibraryExistsByPath(ctx context.Context, path string) (bool, error)
	ListAlbumsByArtist(ctx context.Context, arg ListAlbumsByArtistParams) ([]MusicAlbum, error)
	ListAlbumsByLibrary(ctx context.Context, libraryID int32) ([]MusicAlbum, error)
	ListAlbumsByLibraryGrouped(ctx context.Context, libraryID int32) ([]ListAlbumsByLibraryGroupedRow, error)
	ListAlbumsByLibraryPaginated(ctx context.Context, arg ListAlbumsByLibraryPaginatedParams) ([]ListAlbumsByLibraryPaginatedRow, error)
	ListAlbumsByLibraryPaginatedDesc(ctx context.Context, arg ListAlbumsByLibraryPaginatedDescParams) ([]ListAlbumsByLibraryPaginatedDescRow, error)
	ListAllMedia(ctx context.Context) ([]Medium, error)
	ListAllTranscodeJobs(ctx context.Context) ([]TranscodeJob, error)
	ListArtistIDsByLibraryPaginated(ctx context.Context, arg ListArtistIDsByLibraryPaginatedParams) ([]int32, error)
	ListArtistIDsByLibraryPaginatedDesc(ctx context.Context, arg ListArtistIDsByLibraryPaginatedDescParams) ([]int32, error)
	ListArtistsByLibrary(ctx context.Context, libraryID int32) ([]MusicArtist, error)
	ListFailedScanCheckpoints(ctx context.Context, arg ListFailedScanCheckpointsParams) ([]ScanCheckpoint, error)
	ListImagesByEntity(ctx context.Context, arg ListImagesByEntityParams) ([]MediaImage, error)
	ListImagesByMediaID(ctx context.Context, mediaID sql.NullInt32) ([]MediaImage, error)
	ListImagesBySource(ctx context.Context, sourceType string) ([]MediaImage, error)
	ListInProgressByUserID(ctx context.Context, arg ListInProgressByUserIDParams) ([]WatchProgress, error)
	ListLibraries(ctx context.Context) ([]Library, error)
	ListLibrariesByType(ctx context.Context, type_ string) ([]Library, error)
	ListMediaByLibrary(ctx context.Context, libraryID int32) ([]Medium, error)
	ListMediaByType(ctx context.Context, arg ListMediaByTypeParams) ([]Medium, error)
	ListMovieIDsByLibraryPaginated(ctx context.Context, arg ListMovieIDsByLibraryPaginatedParams) ([]int32, error)
	ListMovieIDsByLibraryPaginatedDesc(ctx context.Context, arg ListMovieIDsByLibraryPaginatedDescParams) ([]int32, error)
	ListMoviesByGenre(ctx context.Context, arg ListMoviesByGenreParams) ([]ListMoviesByGenreRow, error)
	ListMoviesByLibrary(ctx context.Context, libraryID int32) ([]ListMoviesByLibraryRow, error)
	ListMoviesByLibraryPaginated(ctx context.Context, arg ListMoviesByLibraryPaginatedParams) ([]ListMoviesByLibraryPaginatedRow, error)
	ListMoviesByLibraryPaginatedDesc(ctx context.Context, arg ListMoviesByLibraryPaginatedDescParams) ([]ListMoviesByLibraryPaginatedDescRow, error)
	ListMoviesByYear(ctx context.Context, arg ListMoviesByYearParams) ([]ListMoviesByYearRow, error)
	ListMusicTracksByAlbum(ctx context.Context, arg ListMusicTracksByAlbumParams) ([]ListMusicTracksByAlbumRow, error)
	ListMusicTracksByAlbumArtist(ctx context.Context, arg ListMusicTracksByAlbumArtistParams) ([]ListMusicTracksByAlbumArtistRow, error)
	ListMusicTracksByAlbumID(ctx context.Context, albumID sql.NullInt32) ([]ListMusicTracksByAlbumIDRow, error)
	ListMusicTracksByArtist(ctx context.Context, arg ListMusicTracksByArtistParams) ([]ListMusicTracksByArtistRow, error)
	ListMusicTracksByLibrary(ctx context.Context, libraryID int32) ([]ListMusicTracksByLibraryRow, error)
	ListMusicTracksByLibraryPaginated(ctx context.Context, arg ListMusicTracksByLibraryPaginatedParams) ([]ListMusicTracksByLibraryPaginatedRow, error)
	ListMusicTracksByLibraryPaginatedDesc(ctx context.Context, arg ListMusicTracksByLibraryPaginatedDescParams) ([]ListMusicTracksByLibraryPaginatedDescRow, error)
	// This query returns all images for validation in application code
	// The application will check if files actually exist
	ListOrphanImages(ctx context.Context) ([]MediaImage, error)
	ListPlaybackSessionsByMediaID(ctx context.Context, arg ListPlaybackSessionsByMediaIDParams) ([]PlaybackSession, error)
	ListProcessingTranscodeJobs(ctx context.Context) ([]TranscodeJob, error)
	ListQualitySwitchEventsBySessionID(ctx context.Context, sessionID string) ([]QualitySwitchEvent, error)
	ListQueuedTranscodeJobs(ctx context.Context, limit int32) ([]TranscodeJob, error)
	ListRunningScanJobs(ctx context.Context) ([]ScanJob, error)
	ListScanJobsByLibrary(ctx context.Context, arg ListScanJobsByLibraryParams) ([]ScanJob, error)
	ListTVEpisodesByLibrary(ctx context.Context, libraryID int32) ([]ListTVEpisodesByLibraryRow, error)
	ListTVEpisodesBySeason(ctx context.Context, seasonID int32) ([]ListTVEpisodesBySeasonRow, error)
	ListTVEpisodesByShow(ctx context.Context, showID int32) ([]ListTVEpisodesByShowRow, error)
	ListTVSeasonsByShow(ctx context.Context, showID int32) ([]TvSeason, error)
	ListTVShowIDsByLibraryPaginated(ctx context.Context, arg ListTVShowIDsByLibraryPaginatedParams) ([]int32, error)
	ListTVShowIDsByLibraryPaginatedDesc(ctx context.Context, arg ListTVShowIDsByLibraryPaginatedDescParams) ([]int32, error)
	ListTVShowsByLibrary(ctx context.Context, libraryID int32) ([]TvShow, error)
	ListTVShowsByLibraryPaginated(ctx context.Context, arg ListTVShowsByLibraryPaginatedParams) ([]TvShow, error)
	ListTVShowsByLibraryPaginatedDesc(ctx context.Context, arg ListTVShowsByLibraryPaginatedDescParams) ([]TvShow, error)
	ListTranscodeJobsByLRU(ctx context.Context, limit int32) ([]TranscodeJob, error)
	ListTranscodeJobsByMediaID(ctx context.Context, mediaID int32) ([]TranscodeJob, error)
	ListTranscodeJobsByStatus(ctx context.Context, status string) ([]TranscodeJob, error)
	ListWatchProgressByUserID(ctx context.Context, arg ListWatchProgressByUserIDParams) ([]WatchProgress, error)
	ListWatchedByUserID(ctx context.Context, arg ListWatchedByUserIDParams) ([]WatchProgress, error)
	MediaExistsInLibrary(ctx context.Context, arg MediaExistsInLibraryParams) (bool, error)
	ResetFailedScanCheckpoints(ctx context.Context, scanJobID int32) error
	SearchArtistsByName(ctx context.Context, arg SearchArtistsByNameParams) ([]MusicArtist, error)
	SearchArtistsWithCountsByNamePaginated(ctx context.Context, arg SearchArtistsWithCountsByNamePaginatedParams) ([]SearchArtistsWithCountsByNamePaginatedRow, error)
	SearchMoviesByTitle(ctx context.Context, arg SearchMoviesByTitleParams) ([]SearchMoviesByTitleRow, error)
	SearchMoviesByTitlePaginated(ctx context.Context, arg SearchMoviesByTitlePaginatedParams) ([]SearchMoviesByTitlePaginatedRow, error)
	SearchMusicTracks(ctx context.Context, arg SearchMusicTracksParams) ([]SearchMusicTracksRow, error)
	SearchTVEpisodesByTitle(ctx context.Context, arg SearchTVEpisodesByTitleParams) ([]SearchTVEpisodesByTitleRow, error)
	SearchTVShowsByTitle(ctx context.Context, arg SearchTVShowsByTitleParams) ([]TvShow, error)
	SearchTVShowsByTitlePaginated(ctx context.Context, arg SearchTVShowsByTitlePaginatedParams) ([]TvShow, error)
	SearchTVShowsWithCountsByTitlePaginated(ctx context.Context, arg SearchTVShowsWithCountsByTitlePaginatedParams) ([]SearchTVShowsWithCountsByTitlePaginatedRow, error)
	SetScanStateError(ctx context.Context, arg SetScanStateErrorParams) error
	SetScanStateWarning(ctx context.Context, arg SetScanStateWarningParams) error
	UpdateAlbum(ctx context.Context, arg UpdateAlbumParams) error
	UpdateArtist(ctx context.Context, arg UpdateArtistParams) error
	UpdateImage(ctx context.Context, arg UpdateImageParams) error
	UpdateLibrary(ctx context.Context, arg UpdateLibraryParams) (Library, error)
	UpdateMedia(ctx context.Context, arg UpdateMediaParams) (Medium, error)
	UpdateMovie(ctx context.Context, arg UpdateMovieParams) error
	UpdateMusicTrack(ctx context.Context, arg UpdateMusicTrackParams) error
	UpdateScanCheckpointRetryCount(ctx context.Context, arg UpdateScanCheckpointRetryCountParams) error
	UpdateScanCheckpointStatus(ctx context.Context, arg UpdateScanCheckpointStatusParams) error
	UpdateScanJobProgress(ctx context.Context, arg UpdateScanJobProgressParams) error
	UpdateScanJobStatus(ctx context.Context, arg UpdateScanJobStatusParams) error
	UpdateTVEpisode(ctx context.Context, arg UpdateTVEpisodeParams) error
	UpdateTVSeason(ctx context.Context, arg UpdateTVSeasonParams) error
	UpdateTVShow(ctx context.Context, arg UpdateTVShowParams) error
	UpdateTranscodeJob(ctx context.Context, arg UpdateTranscodeJobParams) error
	UpdateTranscodeJobAccess(ctx context.Context, arg UpdateTranscodeJobAccessParams) error
	UpdateTranscodeJobAccessByMediaAndQuality(ctx context.Context, arg UpdateTranscodeJobAccessByMediaAndQualityParams) error
	UpdateWatchProgress(ctx context.Context, arg UpdateWatchProgressParams) (WatchProgress, error)
	UpsertPlaybackSession(ctx context.Context, arg UpsertPlaybackSessionParams) (PlaybackSession, error)
	UpsertScanState(ctx context.Context, arg UpsertScanStateParams) error
	UpsertWatchProgress(ctx context.Context, arg UpsertWatchProgressParams) (WatchProgress, error)
}

var _ Querier = (*Queries)(nil)
