// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: watch_progress.sql

package sqlc_postgres

import (
	"context"
	"database/sql"
)

const createWatchProgress = `-- name: CreateWatchProgress :one
INSERT INTO watch_progress (
    media_id,
    user_id,
    position,
    duration,
    watched,
    last_watched,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, media_id, user_id, position, duration, watched, last_watched, created_at, updated_at
`

type CreateWatchProgressParams struct {
	MediaID     int32           `json:"media_id"`
	UserID      sql.NullInt32   `json:"user_id"`
	Position    float64         `json:"position"`
	Duration    sql.NullFloat64 `json:"duration"`
	Watched     sql.NullBool    `json:"watched"`
	LastWatched sql.NullTime    `json:"last_watched"`
	CreatedAt   sql.NullTime    `json:"created_at"`
	UpdatedAt   sql.NullTime    `json:"updated_at"`
}

func (q *Queries) CreateWatchProgress(ctx context.Context, arg CreateWatchProgressParams) (WatchProgress, error) {
	row := q.db.QueryRowContext(ctx, createWatchProgress,
		arg.MediaID,
		arg.UserID,
		arg.Position,
		arg.Duration,
		arg.Watched,
		arg.LastWatched,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i WatchProgress
	err := row.Scan(
		&i.ID,
		&i.MediaID,
		&i.UserID,
		&i.Position,
		&i.Duration,
		&i.Watched,
		&i.LastWatched,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWatchProgress = `-- name: DeleteWatchProgress :exec
DELETE FROM watch_progress
WHERE id = $1
`

func (q *Queries) DeleteWatchProgress(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteWatchProgress, id)
	return err
}

const deleteWatchProgressByMediaID = `-- name: DeleteWatchProgressByMediaID :exec
DELETE FROM watch_progress
WHERE media_id = $1
`

func (q *Queries) DeleteWatchProgressByMediaID(ctx context.Context, mediaID int32) error {
	_, err := q.db.ExecContext(ctx, deleteWatchProgressByMediaID, mediaID)
	return err
}

const getWatchProgressByID = `-- name: GetWatchProgressByID :one
SELECT id, media_id, user_id, position, duration, watched, last_watched, created_at, updated_at FROM watch_progress
WHERE id = $1
`

func (q *Queries) GetWatchProgressByID(ctx context.Context, id int32) (WatchProgress, error) {
	row := q.db.QueryRowContext(ctx, getWatchProgressByID, id)
	var i WatchProgress
	err := row.Scan(
		&i.ID,
		&i.MediaID,
		&i.UserID,
		&i.Position,
		&i.Duration,
		&i.Watched,
		&i.LastWatched,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWatchProgressByMediaID = `-- name: GetWatchProgressByMediaID :one
SELECT id, media_id, user_id, position, duration, watched, last_watched, created_at, updated_at FROM watch_progress
WHERE media_id = $1
LIMIT 1
`

func (q *Queries) GetWatchProgressByMediaID(ctx context.Context, mediaID int32) (WatchProgress, error) {
	row := q.db.QueryRowContext(ctx, getWatchProgressByMediaID, mediaID)
	var i WatchProgress
	err := row.Scan(
		&i.ID,
		&i.MediaID,
		&i.UserID,
		&i.Position,
		&i.Duration,
		&i.Watched,
		&i.LastWatched,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWatchProgressByMediaIDAndUserID = `-- name: GetWatchProgressByMediaIDAndUserID :one
SELECT id, media_id, user_id, position, duration, watched, last_watched, created_at, updated_at FROM watch_progress
WHERE media_id = $1 AND user_id = $2
LIMIT 1
`

type GetWatchProgressByMediaIDAndUserIDParams struct {
	MediaID int32         `json:"media_id"`
	UserID  sql.NullInt32 `json:"user_id"`
}

func (q *Queries) GetWatchProgressByMediaIDAndUserID(ctx context.Context, arg GetWatchProgressByMediaIDAndUserIDParams) (WatchProgress, error) {
	row := q.db.QueryRowContext(ctx, getWatchProgressByMediaIDAndUserID, arg.MediaID, arg.UserID)
	var i WatchProgress
	err := row.Scan(
		&i.ID,
		&i.MediaID,
		&i.UserID,
		&i.Position,
		&i.Duration,
		&i.Watched,
		&i.LastWatched,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInProgressByUserID = `-- name: ListInProgressByUserID :many
SELECT id, media_id, user_id, position, duration, watched, last_watched, created_at, updated_at FROM watch_progress
WHERE user_id = $1
  AND watched = FALSE
  AND position > 0
ORDER BY last_watched DESC
LIMIT $2 OFFSET $3
`

type ListInProgressByUserIDParams struct {
	UserID sql.NullInt32 `json:"user_id"`
	Limit  int32         `json:"limit"`
	Offset int32         `json:"offset"`
}

func (q *Queries) ListInProgressByUserID(ctx context.Context, arg ListInProgressByUserIDParams) ([]WatchProgress, error) {
	rows, err := q.db.QueryContext(ctx, listInProgressByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WatchProgress{}
	for rows.Next() {
		var i WatchProgress
		if err := rows.Scan(
			&i.ID,
			&i.MediaID,
			&i.UserID,
			&i.Position,
			&i.Duration,
			&i.Watched,
			&i.LastWatched,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWatchProgressByUserID = `-- name: ListWatchProgressByUserID :many
SELECT id, media_id, user_id, position, duration, watched, last_watched, created_at, updated_at FROM watch_progress
WHERE user_id = $1
ORDER BY last_watched DESC
LIMIT $2 OFFSET $3
`

type ListWatchProgressByUserIDParams struct {
	UserID sql.NullInt32 `json:"user_id"`
	Limit  int32         `json:"limit"`
	Offset int32         `json:"offset"`
}

func (q *Queries) ListWatchProgressByUserID(ctx context.Context, arg ListWatchProgressByUserIDParams) ([]WatchProgress, error) {
	rows, err := q.db.QueryContext(ctx, listWatchProgressByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WatchProgress{}
	for rows.Next() {
		var i WatchProgress
		if err := rows.Scan(
			&i.ID,
			&i.MediaID,
			&i.UserID,
			&i.Position,
			&i.Duration,
			&i.Watched,
			&i.LastWatched,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWatchedByUserID = `-- name: ListWatchedByUserID :many
SELECT id, media_id, user_id, position, duration, watched, last_watched, created_at, updated_at FROM watch_progress
WHERE user_id = $1
  AND watched = TRUE
ORDER BY last_watched DESC
LIMIT $2 OFFSET $3
`

type ListWatchedByUserIDParams struct {
	UserID sql.NullInt32 `json:"user_id"`
	Limit  int32         `json:"limit"`
	Offset int32         `json:"offset"`
}

func (q *Queries) ListWatchedByUserID(ctx context.Context, arg ListWatchedByUserIDParams) ([]WatchProgress, error) {
	rows, err := q.db.QueryContext(ctx, listWatchedByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WatchProgress{}
	for rows.Next() {
		var i WatchProgress
		if err := rows.Scan(
			&i.ID,
			&i.MediaID,
			&i.UserID,
			&i.Position,
			&i.Duration,
			&i.Watched,
			&i.LastWatched,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWatchProgress = `-- name: UpdateWatchProgress :one
UPDATE watch_progress
SET position = $1,
    duration = $2,
    watched = $3,
    last_watched = $4,
    updated_at = $5
WHERE id = $6
RETURNING id, media_id, user_id, position, duration, watched, last_watched, created_at, updated_at
`

type UpdateWatchProgressParams struct {
	Position    float64         `json:"position"`
	Duration    sql.NullFloat64 `json:"duration"`
	Watched     sql.NullBool    `json:"watched"`
	LastWatched sql.NullTime    `json:"last_watched"`
	UpdatedAt   sql.NullTime    `json:"updated_at"`
	ID          int32           `json:"id"`
}

func (q *Queries) UpdateWatchProgress(ctx context.Context, arg UpdateWatchProgressParams) (WatchProgress, error) {
	row := q.db.QueryRowContext(ctx, updateWatchProgress,
		arg.Position,
		arg.Duration,
		arg.Watched,
		arg.LastWatched,
		arg.UpdatedAt,
		arg.ID,
	)
	var i WatchProgress
	err := row.Scan(
		&i.ID,
		&i.MediaID,
		&i.UserID,
		&i.Position,
		&i.Duration,
		&i.Watched,
		&i.LastWatched,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertWatchProgress = `-- name: UpsertWatchProgress :one
INSERT INTO watch_progress (
    media_id,
    user_id,
    position,
    duration,
    watched,
    last_watched,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT(media_id, user_id)
DO UPDATE SET
    position = EXCLUDED.position,
    duration = EXCLUDED.duration,
    watched = EXCLUDED.watched,
    last_watched = EXCLUDED.last_watched,
    updated_at = EXCLUDED.updated_at
RETURNING id, media_id, user_id, position, duration, watched, last_watched, created_at, updated_at
`

type UpsertWatchProgressParams struct {
	MediaID     int32           `json:"media_id"`
	UserID      sql.NullInt32   `json:"user_id"`
	Position    float64         `json:"position"`
	Duration    sql.NullFloat64 `json:"duration"`
	Watched     sql.NullBool    `json:"watched"`
	LastWatched sql.NullTime    `json:"last_watched"`
	CreatedAt   sql.NullTime    `json:"created_at"`
	UpdatedAt   sql.NullTime    `json:"updated_at"`
}

func (q *Queries) UpsertWatchProgress(ctx context.Context, arg UpsertWatchProgressParams) (WatchProgress, error) {
	row := q.db.QueryRowContext(ctx, upsertWatchProgress,
		arg.MediaID,
		arg.UserID,
		arg.Position,
		arg.Duration,
		arg.Watched,
		arg.LastWatched,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i WatchProgress
	err := row.Scan(
		&i.ID,
		&i.MediaID,
		&i.UserID,
		&i.Position,
		&i.Duration,
		&i.Watched,
		&i.LastWatched,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
