/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as LayoutImport } from './routes/_layout'

// Create Virtual Routes

const LayoutMediaLazyImport = createFileRoute('/_layout/media')()
const LayoutLibrariesLazyImport = createFileRoute('/_layout/libraries')()

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutMediaLazyRoute = LayoutMediaLazyImport.update({
  path: '/media',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() => import('./routes/_layout/media').then((d) => d.Route))

const LayoutLibrariesLazyRoute = LayoutLibrariesLazyImport.update({
  path: '/libraries',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() => import('./routes/_layout/libraries').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/libraries': {
      id: '/_layout/libraries'
      path: '/libraries'
      fullPath: '/libraries'
      preLoaderRoute: typeof LayoutLibrariesLazyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/media': {
      id: '/_layout/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof LayoutMediaLazyImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutLibrariesLazyRoute: typeof LayoutLibrariesLazyRoute
  LayoutMediaLazyRoute: typeof LayoutMediaLazyRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutLibrariesLazyRoute: LayoutLibrariesLazyRoute,
  LayoutMediaLazyRoute: LayoutMediaLazyRoute,
}

const LayoutRouteWithChildren = LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof LayoutRouteWithChildren
  '/libraries': typeof LayoutLibrariesLazyRoute
  '/media': typeof LayoutMediaLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof LayoutRouteWithChildren
  '/libraries': typeof LayoutLibrariesLazyRoute
  '/media': typeof LayoutMediaLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/libraries': typeof LayoutLibrariesLazyRoute
  '/_layout/media': typeof LayoutMediaLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/libraries' | '/media'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/libraries' | '/media'
  id: '__root__' | '/' | '/_layout' | '/_layout/libraries' | '/_layout/media'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/libraries",
        "/_layout/media"
      ]
    },
    "/_layout/libraries": {
      "filePath": "_layout/libraries.tsx",
      "parent": "/_layout"
    },
    "/_layout/media": {
      "filePath": "_layout/media.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
